### ISSUE TITLE
Actor state Invariance over cross-channel state causes inverse timelock foobar

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1000]
This could lead to some major conflicts later on, I'd recommend FVM (maybe FIL team?) team does a deep dive into this pre m2.2

ref: https://r.mtdv.me/articles/Effects-of-Invariant-State-on-Timelock-FooBar

**Comment by raulk** [comment]
How did I not see that coming

**Comment by mriise** [comment]
Reopening for the next ~week for more discussion.
