### ISSUE TITLE
EVM: Minimal IPLD Parameter/Return Checking

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1001]
The EVM allows sending/receiving _arbitrary_ CBOR messages so that EVM actors can implement native APIs.

However, this means we need at least _some_ IPLD checking. Or at least we might?

Concerns:

1. Backwards compatibility. If we introduce better checking _later_, we might break existing actors. Ideally users will only use the `callactor` instruction to call native actors, but some might try to use it for EVM -> EVM calls with random paramters.
2. Reachability. Most actor APIs don't pass around CIDs (at least they don't pass around CIDs that are ever _loaded_. However, the new `GetBytecode` and `InvokeContractDelegate` methods _do_.

This isn't currently a _state_ hazard as we'd never actually link one of these CIDs into state. However, at least in the case of `InvokeContractDelegate`, we _will_ try to load the CID.

Fir the backwards compatibility problem, we can either:

1. Say "you were warned".
2. Do some minimal validation. Unfortunately, we likely won't have a great way to _charge_ for said validation (the hope was to eventually do this in wasm, but that's not on M2.2's roadmap).

A "minimal" solution to the reachability problem would be to change `InvokeContractDelegate` and `GetBytecode` to not use CIDs:

1. `InvokeContractDelegate` could take the EVM address of the contract we're delegating to, instead of taking the code itself.
3. `GetBytecode` could return the actual bytecode, instead of the CID. I.e., we could call `ipld::open` on the CID, then return the handle (would require some actor runtime shuffling to avoid a bunch of unnecessary copying).

---

If you're wondering "what changed?" or "why is this now an issue?":

1. `GetBytecode`/`InvokeContractDelegate` were introduced.
2. Actors are allowed to handle _arbitrary_ methods (which wasn't in the initial design).

**Comment by Stebalien** [comment]
Ok, there's a dead-simple solution: do this inside the EVM itself. It's not perfect, but it prevents anyone from building applications that try to pass raw bytes as cbor and such.

**Comment by Stebalien** [comment]
Ok, my current approach will be to replace DAG_CBOR with just CBOR, because we don't need to check CBOR. I.e., The "dag" part will be a flag to the system that we need to check reachability.

**Comment by arajasek** [comment]
Open until actors 1076 lands
