### ISSUE TITLE
EVM: CALL on an embryo from the EVM will fail because all methods are rejected (bare value transfers)

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1004]
This is the inverse of the EVM, where all methods are accepted. We have two options:

1. Lookup the receiver's code before sending in EVM's call. Special-case embryos.
2. Just ignore all inputs.

**Comment by vyzo** [comment]
Is it not an error to call an embryo?
We can only send it funds in until it metastasizes.

**Comment by Stebalien** [comment]
>  We can only send it funds in until it metastasizes.

Yes, but sending funds is done by "calling".

**Comment by vyzo** [comment]
yeah, thats a problem.

**Comment by vyzo** [comment]
how about we accept sends with value>0?
That way we can transfer funds and still have a bug catcher in place.

**Comment by raulk** [comment]
Fixed by https://github.com/filecoin-project/builtin-actors/pull/773.
