### ISSUE TITLE
EVM: Audit CALLACTOR instruction

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1018]
- It should take a _filecoin_ address, not an _eth_ address.
- We may want a precompile instead for easier integration (and to avoid sitting on an opcode that may be taken by a future EIP).

**Comment by mriise** [comment]
specifically a filecoin id address

**Comment by Stebalien** [comment]
> specifically a filecoin id address

I think it needs to be a full filecoin address? Otherwise, we can't use it to create non-existing accounts.

**Comment by mriise** [comment]
yeah... sucks a lot to represent this in EVM though...

**Comment by maciejwitowski** [comment]
@mriise I'm adding this to Sapphire. Please let me know if I shouldn't.

**Comment by Stebalien** [comment]
The precompile fixes this (and was just merged).
