### ISSUE TITLE
Consider not allowing one to get the tipset CID for the current epoch

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1023]
Currently, we allow the user to get the tipset CID from the current epoch. However:

1. The EVM (as far as I can tell) only allows getting the blockhash from the _previous_ epoch.
2. If we allow getting the tipset CID from the current epoch, we'll need to know it before we begin execution. That's fine for _now_, but may change if we remove tipsets.

**Comment by maciejwitowski** [comment]
@Stebalien is this part of JSON-RPC or syscalls, I don't know from the description only?

**Comment by Stebalien** [comment]
Syscalls.
