### ISSUE TITLE
Lotus: fix eth address to f4 conversions

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1030]
We have several places where we're directly constructing a "delegated" address from an eth address where we _should_ be calling `api.EthAddress(...).ToFilecoinAddress()` (to correctly handle ID addresses).

**Comment by ychiaoli18** [comment]
@Stebalien after checking all the occurrences of `address.NewDelegatedAddress`, it seems that they all appear after hashing the pubkey to get the Ethereum address, so the Ethereum address will not start with a [12]byte{0xff}, so I don't think changing `address.NewDelegatedAddress` to `ethtypes.EthAddress().ToFilecoinAddress()` will solve any issue. Could you elaborate more about what you want to achieve?

**Comment by ychiaoli18** [comment]
@Stebalien after checking all the occurrences of `address.NewDelegatedAddress`, it seems that they all appear after hashing the pubkey to get the Ethereum address, so the Ethereum address will not start with a [12]byte{0xff}, so I don't think changing `address.NewDelegatedAddress` to `ethtypes.EthAddress().ToFilecoinAddress()` will solve any issue. Could you elaborate more about what you want to achieve?

**Comment by ychiaoli18** [comment]
@Stebalien I still pushed a PR that changed all the NewDelegatedAddress to ToFilecoinAddress(). It doesn't make much difference in functionality but creates f4 addresses more consistently. Do you think this should be merged?

**Comment by Stebalien** [comment]
I think it makes sense anyways just for consistency. Otherwise, someone is likely to copy code and get it wrong.

**Comment by raulk** [comment]
Merged in https://github.com/filecoin-project/lotus/pull/9970.
