### ISSUE TITLE
msg.sender inside the constructor should be the actual sender

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#1034]
`msg.sender` returns `0xff00000000000000000000000000000000000001` inside constructor because Filecoin actors are constructed through init actor (f01, which translates to the above `0xff...1` address). However, it should return the actual sender of the message.

**Comment by Stebalien** [comment]
To be clear: this is an issue for _native_ actors, not EVM contracts.

**Comment by Stebalien** [comment]
Hm. I think this must have been for EVM contracts given how it was described. It has since been fixed.

**Comment by Stebalien** [comment]
Well, and it's covered by https://github.com/filecoin-project/ref-fvm/issues/746.
