### ISSUE TITLE
Audits: Addressing

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1040]
- F4 Assignment
- Embryo Creation
- Predictable Address Storage

Includes (some of these names/links may change, but the code should mostly be where you'd expect).

- [`Kernel::create_actor`](https://github.com/filecoin-project/ref-fvm/blob/cf5ba35f12c74cf425ed71ded568e506290e1db2/fvm/src/kernel/default.rs#L748)
- [`Kernel::new_actor_address`](https://github.com/filecoin-project/ref-fvm/blob/cf5ba35f12c74cf425ed71ded568e506290e1db2/fvm/src/kernel/default.rs#L729)
- [Automatic actor creation on send](https://github.com/filecoin-project/ref-fvm/blob/cf5ba35f12c74cf425ed71ded568e506290e1db2/fvm/src/call_manager/default.rs#L334-L350)
- [Ethereum Address Manager](https://github.com/filecoin-project/builtin-actors/tree/next/actors/eam)
    - Assigns addresses to EVM actors/Ethereum accounts with CREATE/CREATE2 logic.
- [`Init::exec4`](https://github.com/filecoin-project/builtin-actors/blob/a5bf14e2447cab732b58b35931ca87384c715f0b/actors/init/src/lib.rs#L111)

**Comment by anorth** [comment]
I have completed this. Notes are at https://www.notion.so/pl-strflt/Alex-North-notes-and-findings-for-FEVM-M2-1-02994797788e43f6b101c53f4584242a (private). I will try to file a couple more issues too

**Comment by BlocksOnAChain** [comment]
@anorth Thanks. this is great news.

**Comment by BlocksOnAChain** [comment]
closing the issue, since @anorth is done with his audit and shared the findings
