### ISSUE TITLE
Audits: Account Abstraction

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1042]
Specifically, the entire flow.

- Message Validation.
- Block Creation.
- Syntactic Block Validation.
- Block Execution.

And before that, try to break the proposal (we'll link to that here once we've nailed down the details).

**Comment by Stebalien** [comment]
Interest group includes: @anorth.

**Comment by BlocksOnAChain** [comment]
@Kubuxu - useful for when you start your audits:  more context on the implementation path we are taking is here: https://github.com/filecoin-project/FIPs/discussions/490

**Comment by BlocksOnAChain** [comment]
I will close this issue since @Kubuxu submitted his report and it was shared by me in the core devs talks
