### ISSUE TITLE
Audits: Syscall Changes

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1044]
FVM v3 is changing a few syscalls.

Adding:

- Gas premium, limit, used.
- Block timestamp.
- Tipset CID.
- Balance of (other actor).
- Address of (other actor). Inverse of "resolve address".

Changing:

- `create_actor` takes a "persistent address".
- `send` will (likely) take a gas limit, and maybe a "readonly" flag?

Start by comparing the `fvm::syscalls` module between the `release/v2` branch and master`.

Make sure:

- There are no strange undocumented edge cases.
- The syscalls make sense as implemented.
- The error handling is correct.

**Comment by Stebalien** [comment]
Interest group includes: @anorth and @arajasek.

**Comment by BlocksOnAChain** [comment]
@ZenGround0 reported this audit as completed so I will close the issue.
 Findings shared here(private): https://www.notion.so/pl-strflt/Zen-and-his-findings-a7aa3b628517431a90cb355766e094c2
