### ISSUE TITLE
Support batched JSON-RPC requests in Lotus

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1047]
## Context

[Batched requests](https://www.jsonrpc.org/specification#batch) are an optional feature in the JSON-RPC 2.0 specification. However, Ethereum clients offer this feature and downstream users like block explorers (e.g. Blockscout) depend on it. 

In the past, the Lotus team [rejected](https://github.com/filecoin-project/go-jsonrpc/pull/46) this feature and redirected users to using the WebSockets endpoint, on the grounds that it would have similar network properties. However, the desire to have Ethereum applications interact seamlessly with Lotus brings about an added motivation to build this feature.

## Proposed plan

1. Implement batching in [go-jsonrpc](https://github.com/filecoin-project/go-jsonrpc) with sequential processing of individual requests.
2. If necessary, in the near future we can optimise by adding a worker pool for fork-join concurrency.

**Comment by alvin-reyes** [comment]
Hi @Stebalien, @raulk 

I was trying to hook the wallaby testnet on to my local blockscout and its seems to fail due to the lack of support for batch json-rpc requests. I'd be interested to know when can we have this so I can deploy a blockscout instance for FEVM.

**Comment by maciejwitowski** [comment]
I'm considering assigning it to @geoff-vball.
What do you think @geoff-vball @jennijuju @raulk?

**Comment by maciejwitowski** [comment]
Discussed on slack to deprioritise it for now.
