### ISSUE TITLE
Lotus: splitstore and snapshots preparedness for tipset CIDs

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1053]
A user has reported that the attached program run against Wallaby is unable to resolve a tipset that the node provided in the first place.

- The tipset CID in this case was `bafy2bzacecwnr6sbpqvo6hcezvkqdi5unnd4t4mwa7zqyljtxtfzacy2ojgi6`.
- The current epoch on Wallaby is 36100.
- The user was able to successfully resolve tipsets for more recent heights, e.g. 34539.

## Theory

The Wallaby JSON-RPC endpoint is running the Lotus splitstore (pending confirmation). Tipset keys are not linked to the state tree or the chain in any manner, nor to one another; therefore the splitstore discards them. That would explain why more recent heights are available, while older ones aren't.

## Solution

Maybe add the ability to inform the splitstore about CIDs bound by time, not by linkage?

## Repro

```go
	ctx := context.Background()
	api2, _, err := client.NewFullNodeRPCV1(ctx, "http://18.224.22.146:1234/rpc/v1", nil)
	if err != nil {
		panic(err)
	}
	tipSet, err := api2.ChainGetTipSetByHeight(ctx, abi.ChainEpoch(6905), types.EmptyTSK)
	if err != nil {
		panic(err)
	}
	tipSetCid, err := tipSet.Key().Cid()
	if err != nil {
		panic(err)
	}
	fmt.Println(tipSetCid)
	hash, err := api.EthHashFromCid(tipSetCid)
	if err != nil {
		panic(err)
	}
	block, err := api2.EthGetBlockByHash(ctx, hash, true)
	if err != nil {
		panic(err)
	}
	fmt.Println(block)
```

**Comment by jennijuju** [comment]
oh we have an issue for this! so... so not splitstore.. but more of.. we dont think tipset CID is ever put in the block store in the first place lololol

**Comment by arajasek** [comment]
https://github.com/filecoin-project/lotus/pull/9904 for the non-splitstore part of this issue.

**Comment by raulk** [comment]
I've renamed this issue to align with what should be covered. I think this is best assigned to @arajasek, so will reassign.

**Comment by Stebalien** [comment]
Or maybe @vyzo? @arajasek has a lot on his plate right now.

**Comment by jennijuju** [comment]
i sus this shall be resolved by https://github.com/filecoin-project/lotus/issues/9799

**Comment by arajasek** [comment]
So there's 3 parts to this:

- making sure we actually preserve CIDs, done in #[9904](https://github.com/filecoin-project/lotus/pull/9904)
- making sure splitstore GC these CIDs, done in #[9960](https://github.com/filecoin-project/lotus/pull/9960)
- making sure snapshots contain this information, not yet done
  - @jennijuju has a proposal that i like, which is to simply calculate and persist these CIDs on snapshot import -- she will open a lotus issue for that

**Comment by jennijuju** [comment]
> she will open a lotus issue for that
https://github.com/filecoin-project/lotus/issues/9977

**Comment by arajasek** [comment]
Handing over to Jennifer, who will close when lotus 9977 lands.

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/pull/10042 is the last piece. will make sure lotus pr lands so closing this now
