### ISSUE TITLE
EVM: Restrict handling and calling methods < 1024

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1056]
Under FRC0042, methods < `2^24` are for "internal use". Specifically, internal use by the actor author.

- Many of these methods only allow themselves to be called from off-chain actors at the moment anyways.
- The APIs tend to be unstable (things like submitting proofs, etc.)

Furthermore, we need to reserve at least a few more methods for internal EVM calls.

Proposal:

1. Restrict CALLACTOR to methods >= 1024.
2. Handle all methods < 1024 internally and _don't_ fallback on InvokeContract (rejecting any unsupported methods).

I'm proposing 1024 as:

1. This leaves part of the "internal use" range EVM contract authors.
2. This matches the internal port range found in unix systems.

**Comment by Stebalien** [comment]
cc @raulk and @vyzo

**Comment by Stebalien** [comment]
> This should let us punt on https://github.com/filecoin-project/ref-fvm/issues/1001 for now.

Ok, so, it's a _little_ trickier because we currently have things like the multisig that will forward arbitrary message parameters. We're saved in this _exact_ case because `InvokeContractDelegate` can only be invoked by "self", but it's still sketch.

**Comment by raulk** [comment]
> We're currently treating methods < 1024 as "internal"

Request for clarification: by "we" you mean the built-in actors API reengineering effort, right? i.e. that effort is reserving the the < 1024 range for methods unaddressable by user actors.

**Comment by raulk** [comment]
And that range is a subset of the wider _reserved_ FRC42 range (24 bits). Are we planning to specify the < 1024 restriction somewhere?

**Comment by raulk** [comment]
If I'm understanding the above correctly, this makes sense to me.

**Comment by raulk** [comment]
Reading FRC42, how does the 1024 restriction here relate to the 256 restriction specified there?

> New and existing actors can use values < 256 for internal conventions.

**Comment by Stebalien** [comment]
Update:

1. We'd like to restrict EVM->EVM calls <1024.
2. As it stands, payment channels and/or multisigs may make it possible to work around any limitations we put in place here, at least in some cases.

**Comment by Stebalien** [comment]
> I think that's left over from earlier proposals. But we can move to reserving 256. (I chose 1024 because unix).

Answer: yes. 256 was left over, the real answer is `2^24`.

**Comment by Stebalien** [comment]
Multisig is no longer an issue.
