### ISSUE TITLE
Eth JSON RPC API: Support the API in "lotus light"

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1071]
We currently don't support the Ethereum JSON-RPC API in "lotus light", but we really should.

**Comment by jennijuju** [comment]
@Stebalien  this feels like a lotus ticket?

**Comment by Stebalien** [comment]
It is. We just keep all the tickets we expect to work on here so we can track them. We'll create a lotus ticket to discuss the actual implementation.

**Comment by jennijuju** [comment]
with https://github.com/filecoin-project/lotus/pull/9863 this should work

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/lotus/pull/9863#issuecomment-1376302527
