### ISSUE TITLE
Remove negative gas charges

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1077]
We currently have two negative gas charges:

1. `invoke` (the total charge is positive, but we give a rebate in https://github.com/filecoin-project/ref-fvm/blob/1cdba0f93bf110fbfc04221eddfbf6b99dbf97a6/fvm/src/gas/price_list.rs#L161).
2. `self_destruct`

We should just get rid of the concept entirely.

**Comment by mriise** [comment]
remove as in change gas from an int? or just never charge negative values?

**Comment by Stebalien** [comment]
As in, never charge negative values for any reason.

**Comment by Stebalien** [comment]
Moving this to M2.2 because we're not using this inside EVM actors.

**Comment by Stebalien** [comment]
Fixed.
