### ISSUE TITLE
CBOR issues from audit!

### ISSUE THREAD

**Issue by laudiacay** [filecoin-project/ref-fvm#108]
https://hackmd.io/eThp9-pyR0WfLJjBynFntA?view#Findings---CBOR

We should look at these!

**Comment by raulk** [comment]
@Stebalien with the new CBOR serde library, can we consider this done? If not, what are the remaining items?

**Comment by Stebalien** [comment]
This is mostly irrelevant because we're doing an atomic switch. The listed issues were all about consensus differences.

But I'll self-assign and go through the list.

**Comment by dignifiedquire** [comment]
this link doesn't work anymore, are there still issues that are relevant from it?

**Comment by Stebalien** [comment]
@dignifiedquire you need to sign in. Then I can try to share a read key with you.

**Comment by dignifiedquire** [comment]
got access
