### ISSUE TITLE
Test: Check exit codes when we run out of memory

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1115]
We need a test-case that covers all possible OOM cases.

1. If we run out of memory while executing (I think we have one?).
2. If we run out of memory because we can't allocate a new wasm instance (we definitely don't have one).

**Comment by maciejwitowski** [comment]
@aakoshh is there any chance you'll be able to help with this?

**Comment by vyzo** [comment]
Not sure how to test for 1 -- what kind of test do you have in mind?
