### ISSUE TITLE
FIP: TipsetCid FIP

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1120]
We need to write a FIP for tipset CIDs:

- Motivating them.
- Defining the lookback limits.

We also need to _decide_ on those. Right now, we're using finality (900 epochs) but we may want more, we may want less.

**Comment by raulk** [comment]
And figure out a way to retain them in the splitstore, and make sure they are generated when importing snapshots, because they won't be included in those.

**Comment by jennijuju** [comment]
is this only a nice-to-have for nv18? asking cuz 

> figure out a way to retain them in the splitstore,and make sure they are generated when importing snapshots, 

need to understand if there is any work needs to be done here from the lotus side.

**Comment by Stebalien** [comment]
> figure out a way to retain them in the splitstore,and make sure they are generated when importing snapshots,

This part is a "really nice to have" but "technically we can ship without it 🤞 I think...".
