### ISSUE TITLE
EVM: Foundry tooling - `forge script` fails with `RejectCallerWithCode` when deploying contracts

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1124]
### Problem:
We are trying to deploy Medusa on Wallaby using [Foundry deployment scripts](https://book.getfoundry.sh/tutorials/solidity-scripting). These deployment scripts fail with:
```
Error:
Failed to deploy script:
Execution reverted: EvmError: RejectCallerWithCode (gas: 0)
```
I believe this `RejectCallerWithCode` error is related to [EIP-3607: Reject transactions from senders with deployed code](https://eips.ethereum.org/EIPS/eip-3607).

### How to reproduce:
1. [Install Foundry](https://book.getfoundry.sh/getting-started/installation)
2. Clone this basic repo https://github.com/medusa-network/wallaby-foundry-test-repo
3. Fund an account with the wallaby faucet and add the private key to a .env file: `PRIVATE_KEY="wallaby-private-key"`
4. Run `make testnet_deploy`, which tries to deploy the SampleContract to wallaby and fails

### Ideas
Because EOA accounts in FEVM are represented by Filecoin actors (and have code associated with them), perhaps the EOAs are interpreted as smart contracts when trying to create transactions?

However, I am able to deploy the same contracts using Hardhat, so there is something specific to Foundry + RPC response from wallaby that is erroring.

I don't have clear evidence, but I have a feeling that the error originates when simulating transactions in Foundry's rEVM implementation. I think there may be a discrepancy in an RPC response from Wallaby compared to other EVM JSON RPCs, and Foundry uses that response in some transaction simulation resulting in `EvmError: RejectCallerWithCode (gas: 0)`; I don't think the error comes directly from the Wallaby GLIF rpc node, but it would be good to check the error logs if possible.

Maybe the `eth_getCode` RPC response has a slightly differing behavior? Maybe certain addresses are characterized as a smart contract rather than an EOA in FEVM vs. other EVM chains?

Here are other issues in foundry related to `RejectCallerWithCode` https://github.com/foundry-rs/foundry/issues?q=is%3Aissue+RejectCallerWithCode

**Comment by mur-me** [comment]
Hi, I've contacted @jaeaster in PM, will post updates later

**Comment by jaeaster** [comment]
After more research, it looks like `forge script`:
1. deploys the script smart contract to its local EVM.
2. runs the deployment script in it's local EVM to generate the transactions
3. sends the generated transactions to the Wallaby RPC.

I think the error happens in step (1). And it seems like it runs its own EVM locally, but with the blockchain state forked from Filecoin/FEVM.

So my newest theory is (Filecoin state + Foundry rEVM) => Some address is interpreted to have code when it shouldn't (again, possibly related to Filecoin actors?)

The address deploying the script smart contract in step (1) is hardcoded as 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38

Source: https://github.com/foundry-rs/foundry/blob/master/evm/src/lib.rs#L41

And this seems to be the last relevant log line before the `RejectCallerWithCode` EVM revert occurs
```
2022-11-18T17:07:31.315677Z TRACE foundry_evm::executor: deploying contract sender=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
```
Source of log entry in foundry code: https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/mod.rs#L396

**Comment by raulk** [comment]
I believe it's the last hypothesis that is at play here. We have deployed a fix to Wallaby now, where non-code addresses return 0x instead of 0x00. Could you try to reproduce again?

**Comment by jaeaster** [comment]
Yes - this commit fixed it
https://github.com/filecoin-project/lotus/commit/ad3bfc3e0fdaf80610103edae990f92574fca63b

Thanks @raulk and team for responding to this and fixing very quickly!
