### ISSUE TITLE
Milestone 2.2: Ability to deploy WASM actors to Mainnet

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#1144]
eta: 2024Q1
description: Developers will be able to deploy custom smart contracts written in Rust, AssemblyScript, or Go, and compiled to WASM bytecode. SDKs, tutorials, and other developer materials will be generally available. This milestone requires a network upgrade.

**Comment by momack2** [comment]
@maciejwitowski can you update timeline please? From what I'm hearing from Raul, EOQ2 is over-optimistic for this milestone

**Comment by maciejwitowski** [comment]
Yes, changed to Q3.

**Comment by raulk** [comment]
This is technically TBD until the team has time to ship FEVM safely, take a step, assess Wasm scope, and come up with a more detailed timeline. We can put Q3 here so that it shows in the Starmaps thing, but not committing to it at this point.

**Comment by paulgarvey** [comment]
Hey guys, is there an update on Milestone 2.2? Was this completed? 

Also, is there a status on Milestone 3?  - "A series of additional incremental protocol upgrades (besides nv17) to move system functionality from privileged space to user space. The result will be a lighter and less opinionated base Filecoin protocol, where storage markets, deal-making, incentives, etc. are extensible, modular, and highly customizable through user-deployed actors. Enhanced programming features such as user-provided cron, asynchronous call patterns, and more will start to be developed at this stage."

Any status update is much appreciated.

**Comment by Stebalien** [comment]
We took a different approach and focused on EVM support in Filecoin, although the FVM is used for wasm actors in IPC.
