### ISSUE TITLE
eth_getTransactionByHash response contains empty signatures

### ISSUE THREAD

**Issue by lalexgap** [filecoin-project/ref-fvm#1158]
Right now it looks like the transaction signature is returned empty when calling eth_getTransactionByHash:
```
curl https://wallaby.node.glif.io/rpc/v0 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionByHash","params":["0xe303052a586280c099eb550b23559bcc65cb20c8fb9e0c3fe16cbeded0a2f884"],"id":1,"jsonrpc":"2.0"}'
```
```
{"jsonrpc":"2.0","result":{"chainId":"0x7ab7","nonce":"0x0","hash":"0xe303052a586280c099eb550b23559bcc65cb20c8fb9e0c3fe16cbeded0a2f884","blockHash":"0x3fc53c325831f838efcc93e95e775441b44740bb45abb7a54f6a7e9b8e2bd52b","blockNumber":"0x7f63","transacionIndex":"0x0","from":"0xd41298190d223f90c9475aa98852d764ed53550d","to":"0x9f6e424d79cea7e32b852f724e130d2f1c7c99c6","value":"0xa","type":"0x2","input":"0x2fb1d270000000000000000000000000000000000000000000000000000000000000000045f7794d6435dc7cf274a8032bdab5a3871053876fbff394e56505898f4e01760000000000000000000000000000000000000000000000000000000000000804000000000000000000000000000000000000000000000000000000000000000a","gas":"0xa6d7d1","maxFeePerGas":"0x494a8","maxPriorityFeePerGas":"0x493e0","v":"0x","r":"0x","s":"0x"},"id":1}
```
For our use case we don't care about the transaction signature but it does seem to cause the go-ethereum deserialisation to fail:
```json: cannot unmarshal hex string "0x" into Go struct field txJSON.v of type *hexutil.Big```

This means we can't call [TransactionByHash](https://github.com/ethereum/go-ethereum/blob/c2e0abce2eedc1ba2a1b32c46fd07ef18a25354a/ethclient/ethclient.go#L215) to fetch a previous transaction using `go-ethereum`, as it will fail to deserialise the response and return a nil transaction.

**Comment by lalexgap** [comment]
Here's the code that caused the panic: https://github.com/statechannels/go-nitro/blob/1845c9ec3dac7fd643ec15711cac97417f605257/client/engine/chainservice/eth_chainservice.go#L159

**Comment by raulk** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/9837.
