### ISSUE TITLE
EVM 'get_actor_code_cid' precompile is a compatibility hazard

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1171]
Code CIDs will change on upgrade.

We should either:

1. Remove this.
2. Return a synthetic "type" for specific builtin actors. I _wouldn't_ use the same type we use elsewhere but instead coalesce into a few standard types.

Eventually, I expect that we'll have a better "registry" for these things, but not yet.

# Proposal

Replace this precompile with a `get_actor_type` precompile that returns one of:

0. Actor doesn't exist.
1. System (any singleton).
2. Embryo.
3. Account (account / evm account). Also includes the "burn" address.
4. Storage Provider
5. EVM Contract
6. Other (multisig, paych, etc.).

## Implementation

Takes an ID (U256), returns a type (U256).

First, look at the ID. If it's < 99, return 1.

Then, look up the type and map:

1. Embryo -> 2.
2. Account/EVM Account (to be added) -> 3.
3. "Miner" actor -> 4.
4. EVM Contract -> 5.
5. _ -> 6.

**Comment by mriise** [comment]
> First, look at the ID. If it's < 99, return 1.

`if user_id > 99 { return [1] }` ?

**Comment by Stebalien** [comment]
>= 99. Unfortunately, 99 is the "burnt funds account", which is definitely an account.

**Comment by mriise** [comment]
Will the "does not exist" test for if the id exists _at all_ or will it only be for non existant builtin actor id and all other actors get flattened to 1 no matter if they exist or not?

**Comment by Stebalien** [comment]
> Will the "does not exist" test for if the id exists at all or will it only be for non existant builtin actor id and all other actors get flattened to 1 no matter if they exist or not?

Does not exist at all. It's just a convenient way to indicate that.

**Comment by Stebalien** [comment]
(we already do this for the "actor type syscall".
