### ISSUE TITLE
chainid() returns wrong chain Id.

### ISSUE THREAD

**Issue by lalexgap** [filecoin-project/ref-fvm#1182]
It looks like the chainid() assembly function may be returning the wrong chain id for wallaby? It seems to  be returning 31415926 instead of 31415. I've deployed a simple contract to wallaby at `0x2984c0BCf4B7E7Bf8F14dA3DB0809E665Ec30D2D`
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;
pragma experimental ABIEncoderV2;

contract ChainIdGetter {
    function GetChainId() external view returns (uint256) {
        uint256 id;
        /* solhint-disable no-inline-assembly */
        assembly {
            id := chainid()
        }
        /* solhint-disable no-inline-assembly */
        return id;
    }
}
```
I then call the contract function using curl:
```
curl https://wallaby.node.glif.io/rpc/v0 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":null,"to":"0x2984c0BCf4B7E7Bf8F14dA3DB0809E665Ec30D2D","data":"0x33d8a850"}, "latest"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000001df5e76","id":1}
```
 We get a result of 0x001df5e76 (31315926 in decimal) where I was expecting 0x007AB7 (31415)

**Comment by maciejwitowski** [comment]
@lalexgap does it work now?

**Comment by lalexgap** [comment]
> @lalexgap does it work now?

I'm still seeing the same result when hitting the contract using curl. 
```
curl https://wallaby.node.glif.io/rpc/v0 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":null,"to":"0x2984c0BCf4B7E7Bf8F14dA3DB0809E665Ec30D2D","data":"0x33d8a850"}, "latest"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000001df5e76","id":1}
```

Do I need to redeploy the contract?

**Comment by arajasek** [comment]
@maciejwitowski Apologies, the following:

- FVM #1251 
- Actors https://github.com/filecoin-project/builtin-actors/pull/934
- FFI https://github.com/filecoin-project/filecoin-ffi/pull/347
- Lotus https://github.com/filecoin-project/lotus/pull/9838

All of these will be in the next Wallaby reset.

**Comment by raulk** [comment]
This has been delivered in the PRs mentioned above and will go live with Carbonado.1.

**Comment by arajasek** [comment]
@raulk Can we leave this open until we have confirmation that the issue has been fixed? I never actually got a repro, so I'd rather get a :+1: from reporters before closing.

**Comment by raulk** [comment]
I'd rather add an integration test and close the issue. Alternatively, we could have a "Needs verification/test" status in the board. But should avoid keeping fixed issues open, as doing so doesn't give us a good sense of progress, and we don't know when the manual test will happen.

**Comment by geoknee** [comment]
I think this is fixed now. I redeployed a contract [which has a similar getter ](https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/nitro-protocol/contracts/ForceMove.sol#L175-L177) to the OP to wallaby today:


```solidity
    function getChainID() public view returns (uint256) {
        return NitroUtils.getChainID();
    }
    
    // In NitroUtils
    function getChainID() internal view returns (uint256) {
        uint256 id;
        assembly {
            id := chainid()
        }
        return id;
    }
```

Calling it using `curl` gives the desired result:

```
curl https://wallaby.node.glif.io/rpc/v0 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_call","params":[{"from":null,"to":"0x5FbDB2315678afecb367f032d93F642f64180aa3","data":"0x564b81ef"}, "latest"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000007ab7","id":1}
```

**Comment by raulk** [comment]
Thank you for the test/confirmation, @geoknee!
