### ISSUE TITLE
EVM: Jump to JUMPDEST+1

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1184]
Currently, we jump to JUMPDEST, then +1 there. Instead, we should jump to JUMPDEST+1. Specifically:

1. `jump` should return `Ok(dst+1)`.
2. `jumpi` should return `Ok(1 + (test.is_zero() as usize) * dest)`

**Comment by vyzo** [comment]
nice!

**Comment by vyzo** [comment]
jumpi needs to return pc+1 if the condition is falsey.

**Comment by Stebalien** [comment]
Ah, ok, not quite as simple. But still likely faster.
