### ISSUE TITLE
eth_newFilter RPC incompatibility - uses UUID instead of hexstring

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1189]
When one queries EVM logs, the node installs a filter and assigns an ID to that filter. In FEVM, the ids are in UUID format. In other EVM rpc implementations, the ids are hexstrings of length 34 (0x + 32 hex digits). This breaks compatibility with certain tools, like ethers-rs, that expect a hexadecimal.

Example:
```javascript
// ETH mainnet (expected)
const provider = new _ethers.providers.JsonRpcProvider("https://ethereum.publicnode.com")
await provider.send("eth_newFilter", [{}])
=> '0x9b54f543497847192aae8371a69eef67'

// Wallaby (actual)
const provider = new _ethers.providers.JsonRpcProvider("https://wallaby.node.glif.io/rpc/v1")
await provider.send("eth_newFilter", [{}])
=> '2882a03c-6923-4b97-8357-9c83ad3414b9'
```

Relevant code:
FEVM implementation - https://github.com/filecoin-project/lotus/blob/release/fevm-wallaby/chain/events/filter/event.go#L368

Geth implementation - https://github.com/ethereum/go-ethereum/blob/master/rpc/subscription.go#L80

Example error from ethers-rs:
```
Deserialization Error: invalid hex character: -, at 8 at line 1 column 38. Response: "26049097-05e0-47da-bf2e-e35e094ccd10"
```

**Comment by raulk** [comment]
I knew this was going to be an issue :-(

**Comment by nikkolasg** [comment]
This is actually an issue that prevents us from deploying Medusa on FVM. I'm saying this in case you want to evaluate the priority of this issue ;)

**Comment by jaeaster** [comment]
The linked PR is close, but did not fix the issue.

The RPC now returns a json array of 32 bytes.
`"[137,124,8,145,133,18,66,204,160,54,187,102,193,192,80,236,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]"`

What we need is 64 bytes serialized into a 0x-prefixed hexstring of length 32
e.g. `"0xa17d589833554e974549e5f37391f263"`

**Comment by iand** [comment]
Hmm, something not right in the serialization
