### ISSUE TITLE
Make sure we're propagating revert data through the init actor & EAM

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1190]

**Comment by Stebalien** [comment]
Apparently we are, but we _really_ need a test here. And we need to consider the semantics. I.e.:

- Do we propagate errors as-is?
- Do we discard the error number, but propagate the error value?

This is also _kind_ of weird because we don't propagate return values on success...

**Comment by maciejwitowski** [comment]
@Stebalien what is the priority of this?

**Comment by Stebalien** [comment]
High. @mriise has looked at it, but we still need a test _just_ to make sure.
