### ISSUE TITLE
FIP: Predictable address storage

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1191]

**Comment by raulk** [comment]
@Stebalien do we still think that "predictable" is the right term here? To me, whether an address is predictable or not depends on the logic of the Address Manager involved, i.e. it's a context sensitive property more than a protocol-level guarantee?

**Comment by Stebalien** [comment]
No, but I don't have a better name.

**Comment by maciejwitowski** [comment]
@Stebalien which milestone?

**Comment by Stebalien** [comment]
Rolling this into the F4 FIP.
