### ISSUE TITLE
Upgrade Wasmtime

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1198]

**Comment by maciejwitowski** [comment]
Will be closed by https://github.com/filecoin-project/ref-fvm/pull/1412

**Comment by maciejwitowski** [comment]
@Stebalien I see this is being addressed by https://github.com/filecoin-project/ref-fvm/pull/1672 but that PR seems abandoned. What's the status?

**Comment by Stebalien** [comment]
Basically, we had a patch but changes in wasmtime made it difficult to distinguish between different error types. Right now the only error types are "illegal instruction" and "fatal", so we can probably safely fold them into "illegal instruction", but we still need to write some careful tests.

**Comment by Stebalien** [comment]
Needs backport to v2.

**Comment by Stebalien** [comment]
Current status:

1. Re-enabling conformance tests (v3).
2. Need to cut a blockstore release (v3).
3. Backport conformance tests fixes to v2.
4. Remove integration tests from v2.
5. Backport this to v2.

**Comment by Stebalien** [comment]
Ok, this has been released and bubbled all the way to the FVM (and tested by syncing both pre-hygge and post-hygge). I'm declaring it done.
