### ISSUE TITLE
EVM: Require that the call_actor precompile be called with DELEGATECALL

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1201]
Internally, it behaves as if called with delegatecall _anyways_. This will plug a potential security issue where an attacker could "trick" a contract into performing a call it didn't intend (unlikely... but still, it fixes the semantics).

**Comment by Stebalien** [comment]
Design:

1. Pass the call "kind" inside the precompile context instead of "is_static".
2. Check that we're being called with Delegatecall and, otherwise, return some form of "forbidden" precompile error.
3. Instead of relying on static versus non-static call for the "readonly" state, pass the `SendFlags` (from the sdk) in a parameter (likely after the method number?

**Comment by mriise** [comment]
> 2. Check that we're being called with Delegatecall and, otherwise, return some form of "forbidden" precompile error.

At the moment everything gets flattened to a Precompile error, we could abuse ActorError and return an ActorError `USR_FORBIDDEN` or something but thats a bit whack. thoughts?

**Comment by Stebalien** [comment]
Ah, I was thinking of adding a `Precompile::Forbidden` error, unless you can think of another reasonable return value.

**Comment by maciejwitowski** [comment]
@mriise this one is fixed, right?

**Comment by mriise** [comment]
yep :)
