### ISSUE TITLE
Emergency prep: Disable all interactions with the EVM actor

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#1202]
If something is discovered wrong after the FEVM upgrade, we'll probably want to disable all EVM functionality -- no more contract deployments, no interacting with any EVM actor, etc.

We could do this in built-in actors, but @Stebalien's instinct is that it'd be cleaner to do here.

We should have this prepped and ready to go (but not merged anywhere).

**Comment by arajasek** [comment]
@jennijuju suggests implementing this as a flag at the client-VM boundary, and having that flag ready in FVM3. In an emergency, we'd simply switch on the flag at the new network version.

@Stebalien suggests we could use actor bundle overrides to achieve this by simply disabling the EVM actor entirely (eg. swapping it for the embryo actor).

**Comment by jennijuju** [comment]
> @jennijuju suggests implementing this as a flag at the client-VM boundary, and having that flag ready in FVM3. In an emergency, we'd simply switch on the flag at the new network version.

this means only a lotus release is needed upon emergency upgrade, without new fvm or actor releases

**Comment by anorth** [comment]
What kind of think going wrong are you thinking about? Are you worried about wrongness confined to user-deployed actors, or some possibility of that affecting the built-in core functionality? If anyone's worried about the latter, that should motivate more analysis and design such that we're _not_ worried about it?

I'm not suggesting that our failure to imagine something concrete that could go wrong means it can't happen, but different kinds of worries demand different responses. IMO an off-switch is insufficient for any concern about impacts on Filecoin core.

**Comment by jennijuju** [comment]
> If anyone's worried about the latter, that should motivate more analysis and design such that we're not worried about it?

I do have high hope that the amount of audits and testing will give us enough confidence on readiness, however, it's possible something hiding might be missed - having a mitigation plan to help chain restore fast when bad things happen, doesnt hurt imho.

**Comment by maciejwitowski** [comment]
@arajasek is the plan here to have your PR ready just in case we want to use it? This would make it not needed for a code-freeze, correct? cc @Stebalien

**Comment by jennijuju** [comment]
> @arajasek is the plan here to have your PR ready just in case we want to use it? This would make it not needed for a code-freeze, correct? cc @Stebalien

This is something we will land after code freeze, and finalize development during calib period.

**Comment by arajasek** [comment]
Draft PRs and handbooks have been opened
