### ISSUE TITLE
eth_getLogs - Event filter topics do not work

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1207]
When retrieving logs, specifying a topic to filter by a specific event does not work. This effects `eth_getLogs`, `eth_newFilter`, `eth_subscribe` and any other method where you can retrieve logs and filter by a topic.

```javascript
const rpc = 'https://wallaby.node.glif.io/rpc/v1'; 
const provider = new _ethers.providers.JsonRpcProvider(rpc);

const factoryInterface = new _ethers.utils.Interface([
  "event NewDKGCreated(address dkg)"
]);

const factoryAddress = '0x66aa40539213e2a5710c46980041b0c743a4d767';
const fromBlock = 18203;
const toBlock = 18203;
const topics = [
  factoryInterface.getEventTopic("NewDKGCreated")
];

await provider.getLogs({
  address: factoryAddress,
  fromBlock,
  toBlock,
  topics
})

=> []
```

If I exclude the topics, I see the event duplicated 5 times
```javascript
await provider.getLogs({
  address: factoryAddress,
  fromBlock,
  toBlock,
  topics: []
})

=> (5) [{…}, {…}, {…}, {…}, {…}]

{blockNumber: 18203, blockHash: '0xb8864eef3b4fc8b03d7c7469ef95ace27967617d6564953cb8851f28640d3d79', transactionIndex: 0, removed: false, address: '0x66Aa40539213E2a5710c46980041B0c743A4D767', …}

{blockNumber: 18203, blockHash: '0xb8864eef3b4fc8b03d7c7469ef95ace27967617d6564953cb8851f28640d3d79', transactionIndex: 0, removed: true, address: '0x66Aa40539213E2a5710c46980041B0c743A4D767', …}

{blockNumber: 18203, blockHash: '0xb8864eef3b4fc8b03d7c7469ef95ace27967617d6564953cb8851f28640d3d79', transactionIndex: 0, removed: false, address: '0x66Aa40539213E2a5710c46980041B0c743A4D767', …}

{blockNumber: 18203, blockHash: '0xb8864eef3b4fc8b03d7c7469ef95ace27967617d6564953cb8851f28640d3d79', transactionIndex: 0, removed: true, address: '0x66Aa40539213E2a5710c46980041B0c743A4D767', …}

{blockNumber: 18203, blockHash: '0xb8864eef3b4fc8b03d7c7469ef95ace27967617d6564953cb8851f28640d3d79', transactionIndex: 0, removed: false, address: '0x66Aa40539213E2a5710c46980041B0c743A4D767', …}
```

And if I expand any one of those 5 logs, I see the matching topic
```
topics: ['0x910c4ffd91af4d613aaac5d9ebe9951074b1d661ea51abb6ec9bdf419e2140ea']
```

**Comment by jaeaster** [comment]
A couple more notes:

I mentioned that when I use getLogs without a topic filter, I can get the logs I want and I can see that the topic hash is what I expect. So the computation of the topic hash seems to be correct, but the matching/filtering is not.

The fact that there are 5 duplicated log entries is unexpected. And in fact, I made the same query a few hours after I originally made this issue and I saw 7 entries. This behavior should probably be a separate issue, what do you think?

**Comment by iand** [comment]
> I mentioned that when I use getLogs without a topic filter, I can get the logs I want and I can see that the topic hash is what I expect. So the computation of the topic hash seems to be correct, but the matching/filtering is not.
> 

Agree, something is not correct here. I'm investigating


> The fact that there are 5 duplicated log entries is unexpected. And in fact, I made the same query a few hours after I originally made this issue and I saw 7 entries. This behavior should probably be a separate issue, what do you think?

I can't reproduce this, I get just one result

```bash
14:05 $ curl https://wallaby.node.glif.io/rpc/v1 -X POST -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"address":["0x66aa40539213e2a5710c46980041b0c743a4d767"],"fromBlock":"0x471B","toBlock":"0x471B","topics":null}]}'

{"jsonrpc":"2.0","result":[{"address":"0x66aa40539213e2a5710c46980041b0c743a4d767","data":"0x0000000000000000000000002d1f7bc61dc80d43e2ab43c3cb3116d508a3ce0b","topics":["0x910c4ffd91af4d613aaac5d9ebe9951074b1d661ea51abb6ec9bdf419e2140ea"],"removed":false,"logIndex":"0x0","transactionIndex":"0x0","transactionHash":"0x6e10b6c39273d01f96f83c419c9ee236e273c14a555e5f8d3c7142b279c6a576","blockHash":"0xb8864eef3b4fc8b03d7c7469ef95ace27967617d6564953cb8851f28640d3d79","blockNumber":"0x471b"}],"id":1}
```

**Comment by jaeaster** [comment]
> I can't reproduce this, I get just one result

I also get one result now ... time seems to be relevant. And we've observed the result count both grow and shrink. Will update if I figure anything else out related to varying responses.
