### ISSUE TITLE
eth_subscribe RPC incompatibility - uses integer for subscription ID instead of hexstring

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1208]
Similar to the issue described here: https://github.com/filecoin-project/ref-fvm/issues/1189

ethers-rs expects a hexstring for subscription IDs and the infura docs describe the ID to be a hexstring as well
https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/subscription-methods/eth_subscribe#body

**Comment by iand** [comment]
In progress along with #1189 should be a couple of hours to fix
