### ISSUE TITLE
FEVM: expose evm return value in back trace

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/ref-fvm#1210]
when bugging steb about debugging 

```
ERROR: GasEstimateMessageGas error: message execution failed: exit 33, reason: message failed with backtrace:
00: f06 (method 4) -- failed to mint 1000 data cap to client f01005: failed to send mint MintParams { to: Address { payload: ID(1005) }, amount: TokenAmount(1000.0), operators: [Address { payload: ID(5) }] } to datacap: send to f07 method 2 aborted with code 33 (33)
01: f07 (method 2) -- receiver hook aborted when 6 sent TokenAmount(1000.0) to 1005 from 7 with exit code ExitCode { value: 33 } (33)
02: f01005 (method 3726118371) -- contract reverted (33)
```

we realized that the most inner error is not populated or logged -  it would be nice to have the return value in back trace for debugging purpose

**Comment by Stebalien** [comment]
Basically, the backtrace doesn't currently include a value. But we _could_ probably include the value on error, or at least a truncated one.

**Comment by Stebalien** [comment]
So, @vyzo tried and... the return value isn't just a string. It's a "typed" thing that's not self-describing, so there's not much we can do here right now.
