### ISSUE TITLE
Revert 1211

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1217]
We need to revert 1211 and update cid/multihash. Unfortunately, to do this, we need to (in order).

1. [ ] Build abstractions in https://github.com/filecoin-project/filecoin-ffi to abstract over multiple `cid` and `fvm_ipld_blockstore` versions. We currently have absractions over most of the other components, but not these.
    - Specifically, in this case, I'd write a general-purpose `Blockstore2(Blockstore3)` wrapper that wraps a v3 blockstore in a struct that implements the _v2_ interfaces.
3. [ ] Release new minor versions of all IPLD crates in this repo.
4. [ ] Release new "alpha" versions of the `fvm`, `fvm_shared`, and `fvm_sdk` crates.
5. [ ] Update `cid`, `multihash`, `fvm_shared`, and `fvm_sdk` in builtin-actors _next_.
6. [ ] Update all the "v3" crates in the FFI itself.

**Comment by Stebalien** [comment]
@shawnrader: can you implement the first point here? We don't need to upgrade cid/multihash yet to do that. Basically, just introduce an abstraction assuming that:

1. There will be new `fvm_ipld_blockstore` and `fvm_ipld_encoding` releases.
2. That both versions will use different CID types.

Alternatively, you can (in an FVM branch):

1. Revert #1211 (restoring the new CID version).
2. Use `cargo set-version` to _locally_ release new versions (steps 2 and 3 above).
3. Use patches in the FFI to use your local version of the FVM.
4. Then develop the fixes.

This may help because you'll actually be able to test against the FVM as it will exist. If this doesn't make sense, I can also get this started and give you an FVM branch to target.

**Comment by shawnrader** [comment]
I don't have permissions to assign this issue to myself, but I will work on this.

**Comment by shawnrader** [comment]
development branch for filecoin-ffi fvm abstractions: https://github.com/filecoin-project/filecoin-ffi/tree/dependency-cid

**Comment by Stebalien** [comment]
This has been un-reverted in the latest releases.
