### ISSUE TITLE
EVM: Fix EXTCODE* functions to never revert

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1223]
There should be _no_ cases where these revert unless we believe there's a bug in the system itself.

E.g. https://github.com/filecoin-project/builtin-actors/blob/0fc355633f90330003b1c81c766dffe6ccbb4e54/actors/evm/src/interpreter/instructions/ext.rs#L42-L44

But we should check all the other case as well.

**Comment by mriise** [comment]
EXTCODESIZE called on precompiles must not be zero. Solidty versions below `0.8.10` will revert otherwise.
