### ISSUE TITLE
Remove address lookup functionality from verify_signature syscall, just do simple verification

### ISSUE THREAD

**Issue by anorth** [filecoin-project/ref-fvm#1228]
The `verify_signature` syscall has functionality to accept an address that is not a public key address (namely an ID address) and lookup that address to find the addressed built-in account actor and then extract its public key address from state, and then verify the signature according to that address. This functionality has existed for a while, originally motivated as an ergonomic improvement to dealing with the multiple addresses. This was changed in #999 to lookup the address stored in the root Actor object in the state tree ([FIP discussion](https://github.com/filecoin-project/FIPs/discussions/477)), and extended in #1002 "Hack: allow f4-embryos to be used as accounts" to hardcode and special-case delegated addresses under the namespace `10`, intended for the EVM Account Manager actor, thus privileging it.

https://github.com/filecoin-project/ref-fvm/blob/c6a153b9f1dbe6b9bfa880a472239bcb508f2285/fvm/src/kernel/default.rs#L444-L464

**This resolution behaviour is incompatible with account abstraction** and should be removed. Under account abstraction, there is no necessary correspondence between an actor's address and its signing authority. This is obviously the case for smart-contract wallets or any other thing-that-might-authenticate-messages deployed at f2 or f4 addresses. Even actors deployed at an f1/f3 address should eventually be able to upgrade into a smart-contract wallet and change their validation logic. Preventing smart wallets is no-no, and implicitly validating messages with against an address/key other than what the user expects could be a huge vulnerability class.

This is easy to fix. The right way for actors to check authentication by other actors is to use the [FIP-0044](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0044.md) standard authentication function. Signature verification is still a necessary primitive, but it should be _just signature verification_, call straight through to the crypto.

There are only two current callers of `verify_signature`: the built-in account actor in its own implementation of `AuthenticateMessage`, and the verified registry which should be changed to use `AuthenticateMessage` https://github.com/filecoin-project/builtin-actors/issues/922

Thus, if we remove this functionality right away, the only impact is that the submission of a FIL+ datacap revocation request must be sure to use the f1/3 address rather than ID address to refer to the verifier. But if we update the verified registry to use FIP-0044 at the same time, there's no other callers. This may require a FIP.

At a minimum I think the EVM hack should be removed immediately (otherwise you'll need to FIP this behaviour change).

@Stebalien @arajasek

**Comment by Stebalien** [comment]
I completely agree, but I'm not sure if we'll be able to get rid of this for M2.1.

> At a minimum I think the EVM hack should be removed immediately (otherwise you'll need to FIP this behaviour change).

The EVM hack will go away with #1204 no matter what. We'll either:

1. Perform signature verification in wasm (for the Ethereum account type).
2. Fix this issue and introduce a new `verify_signature` primitive. But I kind of doubt that given the time constraints.

**Comment by anorth** [comment]
Do you actually need this hack for anything at the moment? Since there are no calls to the syscall, I have assumed not.

**Comment by Stebalien** [comment]
Right now, no.

**Comment by Stebalien** [comment]
We've dropped the hack.

**Comment by anorth** [comment]
Ok sounds good. Then I assume new syscalls for new signature types in the future.

**Comment by Stebalien** [comment]
Yep.

**Comment by Stebalien** [comment]
Short-term: restrict this syscall to the account actor.

**Comment by anorth** [comment]
> Short-term: restrict this syscall to the account actor.

The verified registry also needs it. But we can restrict to built-ins.

**Comment by Stebalien** [comment]
https://github.com/filecoin-project/builtin-actors/tree/asr/verifreg-authenticate

Assuming that _is_ actually in-scope. It's a bit unclear right now.

**Comment by arajasek** [comment]
> https://github.com/filecoin-project/builtin-actors/tree/asr/verifreg-authenticate
> 
> Assuming that _is_ actually in-scope. It's a bit unclear right now.

That has landed.

**Comment by Stebalien** [comment]
I've filed https://github.com/filecoin-project/ref-fvm/issues/1349 for removing this syscall entirely, but _this_ issue will be fixed by #1348.
