### ISSUE TITLE
EVM: EXTCODEHASH is incorrect

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1229]
see https://eips.ethereum.org/EIPS/eip-1052

TL;DR:
- code hash must be keccak256
- accounts without code have a special "is empty" hash `0xc5d246...``
- accounts that dont exist or are "empty" (see link for the definition) are just 0s
- precompiles are all 0s (it says it _could_ be the "is empty" hash, but im hoping we can just go with 0s)
- (for us) native actors are the keccak hash of [0xfe] https://github.com/filecoin-project/builtin-actors/pull/921#discussion_r1042840904

**Comment by Stebalien** [comment]
> accounts that dont exist or are "empty" (see link for the definition) are just 0s

What? WHAAAAAAAAAAAAAAAAAAAAAAT? WHYYYYYYYYYYYY. This is just. Lol.
