### ISSUE TITLE
Using ethers.js to do transactions get an error: `Transaction hash mismatch from Provider.sendTransaction`

### ISSUE THREAD

**Issue by RokasVaitkevicius** [filecoin-project/ref-fvm#1234]
Hello, I've been trying to push transactions to Filecoin using ethers.js. 

Transaction itself gets pushed and it suceeds, but I get an error:
```
"Transaction hash mismatch from Provider.sendTransaction. (expectedHash=\"0xf6a03042f44aa090ac46a6ef893cb93899c900a34320da103d0ff89d5aec4116\", returnedHash=\"0x7a4946290b38dd86cf955485ad34038974b7e66c5132417045926a727f1e34cf\"
```

Based on discussions I had in Filecoin slack, it's because Filecoin uses the message hash as the transaction hash, but ethers.js calculates it locally.

I was asked to raise this here in github as a potential issue.

**Comment by jennijuju** [comment]
Hi thanks for reporting! We will be fix and tracking this issue at https://github.com/filecoin-project/lotus/issues/9839
