### ISSUE TITLE
[Tooling] Incorrect Gas Estimation logic

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#1240]
On the Sapphire version of Wallaby, we observed messages* that were incurring miner penalties because their GasLimits did not cover their on chain inclusion.

On further investigation, it appears that their GasLimits are _precisely_ equal to Lotus's estimate of their on chain inclusion cost. Due to a known incompatibility between Lotus and the ref-fvm around early networks, the FVM calculates a higher on-chain inclusion cost than Lotus, leading to the penalty.

The question is why we're seeing messages with GasLimit set equal to Lotus's estimate of the on-chain inclusion cost. This value should be estimated by simulating the message on the FVM and then overestimating a tad, which should produce a value _considerably_ larger than the on-chain inclusion cost.

This is very likely some incorrect tooling that lives outside of Lotus, since a quick examination of the estimation code reveals no issues (at least no places where we just shortcut with the inclusion cost). It might be hard to track down the tooling in question, but maybe we can?

*eg: `bafy2bzaceasrdsynp5fdxlsbhyvon6p4a3halktq7npmtbmokpw4qa4isdv32`

**Comment by jennijuju** [comment]
To investigate 

- what are the toolings that are constructing messages?
    - glif wallet? any js library?
- How are they estimating the gas cost?
if fvm PMs can help pointing the tooling developers here to answer the q that would be super useful!

**Comment by ychiaoli18** [comment]
The behavior of Ethereum tools is to call eth_estimateGas and include the response in the tx parameter. We can change the behavior of [EthEstimateGas](https://github.com/filecoin-project/lotus/blob/feat/nv18-fevm/node/impl/full/eth.go#L754) by multiplying the value returned by `GasAPI.GasEstimateMessageGas` by a constant.

**Comment by arajasek** [comment]
@ychiaoli18 Thanks for looking into this! I'm still a little confused, because that doesn't explain why the value being used was the on-chain inclusion cost. If they were calling EthEstimateGas, they should still have gotten a better estimate -- maybe not sufficient for the message to execute successfully, but definitely more than the on-chain inclusion cost.

**Comment by maciejwitowski** [comment]
We discussed that there's no action for engineering team. We should be alert to which tool sends this message and then potentially come back to it. cc @ychiaoli18 will
