### ISSUE TITLE
Review interface of EAM#create

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1255]
Currently this takes a user-supplied nonce under the assumption that:

1. Deploying on arbitrary nonces is inoffensive given that the protocol guarantees no overwriting of contracts.
2. Deploying on non-continguous ranges is fine.
3. The nonce is only provided by trusted sources at this stage.

Where we ultimately end up depends on how the foreign accounts solution shapes up. If (3) holds up, then we're probably fine. But if not, I don't have enough confidence that (1) and (2) are correct.

**Comment by Stebalien** [comment]
Also note: we can _probably_ re-restrict `EAM#create` once we merge the Ethereum EOA PR. We opened it up for the fake account abstraction work.

(but I do think it isn't a security issue).

**Comment by raulk** [comment]
If we do decide to keep it, I'd recommend renaming the field to `index`. `nonce` in this domain very specifically means autoincrementing, contiguous sequences.

**Comment by Stebalien** [comment]
Ok, decisions:

1. Restrict `create` to be callable by the EVM/EthAccount only.
2. Make the nonce nullable (`Option<u64>`).
3. If the nonce is `None`, validate that the caller is an `EthAccount`, and use the message's nonce.
4. If the nonce is `Some(nonce)`, validate that the caller is an EVM actor.

This also works around some annoying race-conditions where "create" messages from accounts need to include the nonce which may get "bumped" between the read and the send.

**Comment by Stebalien** [comment]
Update to the decisions:

# `EAM::create`

- Restrictions: Callable by the EVM only.

# `EAM::create_external`

Add a new method (`EAM::create_external`). That _just_ takes the initcode (no nonce). Use the nonce from the top-level message.

- Restrictions: Callable by EthAccount and Account. To be safe, assert that the caller is also the origin.

# `EAM::create2`

Leave it as it is, for now.

**Comment by raulk** [comment]
The review work has done and has resulted in the change decisions captured in https://github.com/filecoin-project/ref-fvm/issues/1434. Closing this as completed.
