### ISSUE TITLE
EVM: Add an FRC42 endpoint for EVM calls

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1256]
I'm a bit concerned that users will start hard-coding the current InvokeContract method number, making it difficult for "native" actors to implement EVM calling. We can likely punt on this, but that should be an explicit decision.

**Comment by Stebalien** [comment]
So, this is also important for off-chain calls. Right now, we use method 2 which will produce not-so-great errors. Ideally, we'd:

1. Use an RFC42 method number.
2. In either the FVM or lotus, augment the backtrace with some information about _why_ the method may not have been supported (e.g., look for well-known FRC42 method numbers).

**Comment by Stebalien** [comment]
This is also an issue for on-chain calls. Right now, we just invoke method 2 without really thinking about it, which will likely cause issues in the future.

We should implement this now.

**Comment by Stebalien** [comment]
Specifically:

1. Add an FRC42 method for calling.
2. Always use it, even EVM -> EVM.

**Comment by maciejwitowski** [comment]
Closing this after since https://github.com/filecoin-project/builtin-actors/pull/1021 is merged (not sure why the automation didn't do it)
