### ISSUE TITLE
GAS: Determine extern-related costs

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1264]
We're adjusting some of the system call gas but don't have a good way to estimate the actual cost of writing to and reading from the lotus blockstore. We'd like numbers on lotus related things:

- Cost of flushing per-block and per-byte (assuming batch writes).
- Cost of reading per-block and per-byte (assuming sequential reads).

Basically, we need to:

1. Derive the costs above.
2. Subtract the extern gas that we're already charging (21000).
3. Add those costs to the costs determined in https://github.com/filecoin-project/ref-fvm/pull/1242

All together, that should give us _accurate_ costs.

**Comment by Stebalien** [comment]
Importantly, let's add whatever we need to measure these numbers as a test framework in the FFI so we don't have to keep redoing this.

**Comment by Stebalien** [comment]
> I don't think test framework numbers will be directly applicable here, at least not for writes. The time is related to the size of the blockstore (I'm assuming mainnet), and also, there is the cost of discovering links during the deep clone/flush.

For writes, the framework numbers tell us the cost of writing blocks to the write cache only. The ask in this issue is to then determine the appropriate costs for the final flush which, as you noted, needs to take datastore costs + link discovery into account. But, I _think_ we can (for now) just average that over all blocks.

In future versions, I plan on doing that link discovery inside a wasm module on write (not flush). But we don't have that logic yet.

> The way I approached this is by instrumenting the BufferedBlockstore, it would be great if that instrumentation could land in ref-fvm behind a feature flag but I can see arguments against it.

I'm happy to land any instrumentation you have. We've already landed a bunch from @aakoshh.

**Comment by Kubuxu** [comment]
For writes, I wrote this, and I'm running it right now over mainnet sync: https://github.com/filecoin-project/ref-fvm/compare/release/v2...feat/blockstore-write-measure
I would be up for landing something similar behind a feature flag, but I'm not sure by what mechanism to get the number outs (I use a separate file as it saves me from filtering the logs). Any recommendations @aakoshh 

Rough preliminary results from the last 2h running mainnet.
```
> cat blockstore_stats.* | datamash -t, -H mean Duration sstdev Duration mean NBlocks sstdev NBlocks mean Size sstdev Size
mean(Duration),sstdev(Duration),mean(NBlocks),sstdev(NBlocks),mean(Size),sstdev(Size)
0.21809741489944,0.020902861339175,12730.921787709,598.97876997618,18514226.184358,611691.05825299

> cat blockstore_stats.* | datamash -t, -H  ppearson Duration:Size
ppearson(Size)   # correlation between duration and size of the batch in bytes
0.19098702734592

> cat blockstore_stats.* | datamash -t, -H  ppearson Duration:NBlocks
ppearson(NBlocks)  # correlation between duration and size of the batch in number of blocks
0.1441418183822
````

The correlation between the number of blocks or their overall size and the time taken to save is quite low. I hope that, over time the pattern cleans up a bit. As I collect more data, I will perform parameter optimization to achieve the best fit of the model to collected results.

**Comment by aakoshh** [comment]
This is great! I have to look into datamash.

My understanding based on what @Stebalien said was that even the things written by the buffered store aren't directly written to the disk, but some in-memory thing inside Lotus, which will be flushed at the very end, in parallel. So I'm not sure where what `batch_write` really does. 

Why is that that in your statistics, you don't group by the labels, like `read_disk` and `read_buffer`?

**Comment by Stebalien** [comment]
Basically:

1. We buffer into the "buffered store" in the FVM.
2. When we're done, we call "flush". That walks the reachable blocks and sends them over to lotus in "chunks" of at most 4MiB and/or 1024 blocks.
3. Lotus writes them all as a batch.

So I guess it isn't multi-threaded, just bulk writes.

**Comment by aakoshh** [comment]
> but I'm not sure by what mechanism to get the number outs (I use a separate file as it saves me from filtering the logs)

My thoughts:
1. Maybe extend the `ExecutionTrace` to add a new type that captures the number of bytes read/written and the time it took. That way we have a unified approach of gathering traces, whatever they might be. Pass something to the buffered blockstore that allows appending to these. IOHK used what they called [contravariant tracing](https://github.com/aakoshh/metronome/blob/develop/metronome/tracing/src/io/iohk/metronome/tracer/Tracer.scala) which we [specialized and passed around](https://github.com/aakoshh/metronome/blob/develop/metronome/networking/src/io/iohk/metronome/networking/NetworkTracers.scala) to components that needed to log anything, deciding on the format only at the [edge of the application](https://github.com/aakoshh/metronome/blob/develop/metronome/checkpointing/app/src/io/iohk/metronome/checkpointing/app/tracing/CheckpointingNetworkTracers.scala). 
2. Use a [tracing library](https://docs.rs/tracing/latest/tracing/#subscribers) that allows you to decouple event emitters from subscribers, so you don't have to use ad-hoc files, but put the logic of separating out these kind of logs at the application root.
3. Don't use any tracing in code for tracking this IO cost, but look at https://ebpf.io/applications/ to tap into the Linux kernel on any machine we are running a node on, to collect and export interesting events and timings without the application even knowing. See more examples [here](https://medium.com/@zone24x7_inc/ebpf-programming-for-linux-kernel-tracing-30364dde3fb7) and [here](https://www.brendangregg.com/blog/2019-01-01/learn-ebpf-tracing.html).

**Comment by Kubuxu** [comment]
Steb answered the first one,

One point is that at this layer, we don't split into smaller chunks. We batch-write everything discovered in the recursive walk.

> Why is that that in your statistics, you don't group by the labels, like read_disk and read_buffer?

The stats I presented are based on the previous version of the output, which had just the batch_write.
I use datamash for quick, in situ statistical processing to see if I'm outputting something usable or junk. That is why I also looked at the Pearson Correlation coefficient.

**Comment by Kubuxu** [comment]
> Maybe extend the ExecutionTrace to add a new type that captures the number of bytes read/written and the time it took. That way we have a unified approach of gathering traces, whatever they might be.

I designed the initial execution trace but it never reached its full potential for this use-case due to how hard it is to get it out of lotus when running normal block sync. This is something we could fix.

> Use a [tracing library](https://docs.rs/tracing/latest/tracing/#subscribers) that allows you to decouple event emitters from subscribers, so you don't have to use ad-hoc files, but put the logic of separating out these kind of logs at the application root.

I like the tracing lib approach, we've used something like this in lotus as well, primary issue with it was it required specialised collection endpoint and it didn't support straight output of trace events into for example a file. This doesn't seem to be the case for the tracking you mentioned.

> ebpf

ebpf won't give us full view into the overhead of these operations. It will tell us about the iowait, yes but we are interested in the more wholistic view of "how long does this op take, end to end".

**Comment by Kubuxu** [comment]
From the read gas analysis, I suggest increasing the read gas to 187440 per operation and 5.652 per byte, which is +63% increase in flat gas. The scaling cost currently is set at 10gas/b, suggesting an arbitrary value we decided was good enough. If we drop per byte gas to 5.652+0.5 per byte the increase is an average +48% for reads.


Analysis:
https://ipfs.subutai.io/ipfs/QmaiHLkNAdufg3sjDe1ovie4KqYzZnxRTyeaLLNK2wusZa/blockstore-read-gas.html

**Comment by Kubuxu** [comment]
On the other hand the 187400 includes the extern cost which isn't included in `block_open_base` with value of 114617.

**Comment by aakoshh** [comment]
I would we put this cost into `storage_gas`, if it isn’t already, rather than `compute_gas`, so as not to distort the time-vs-gas models in my PRs. 

I know the intention with the former was probably to account for data at rest, but it would be great to keep compute gas for what we can measure during the syscall execution. 

If necessary it could go into a third field, it’s only for tracking anyway.

**Comment by Stebalien** [comment]
@aakoshh I've already renamed "storage" to "other". My plan is to put all the extern costs there as well.

@Kubuxu

- Any progress on flush costs?
- Any idea if our general "extern" cost is remotely accurate?

**Comment by Kubuxu** [comment]
@Stebalien @aakoshh I'm thinking about introducing changes from https://github.com/filecoin-project/ref-fvm/compare/release/v2...feat/blockstore-write-measure behind feature flag or env flag and producing the output via tracing interface: https://docs.rs/tracing/latest/tracing/#subscribers

Would you be for such an approach?
