### ISSUE TITLE
eth_getTransactionBy* - RPC incompatibility, null fields should return 0x0

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1269]
In ethers-rs, when trying to deserialize the response from eth_getTransactionBy(Hash, BlockNumberAndIndex, BlockHashAndIndex), the deserialization fails because the  ECDSA fields (`r`, `s`, `v`) are all equal to `0x`. ethers-rs expects those fields to be populated with some value, namely:
```
"invalid length 0, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 8] bytes"
```

I'm not sure if those fields should be null, but if they are, the RPC should return 0x0. I've tested that filling those fields with 0x0 results in a successful deserialization.

**Comment by Stebalien** [comment]
Yep. We need to be revers-engineering these fields from the signature in https://github.com/filecoin-project/lotus/blob/373b8b3517c6ade6f9d346bfe3c0af30007f2b47/node/impl/full/eth.go#L1483-L1485. But we're not.

**Comment by raulk** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/9837.
