### ISSUE TITLE
Limits: Fetch "vrfdigest" from the client instead of letting the client draw randomness

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1277]
Currently, we:

1. Have an EVM precompile to fetch randomness.
2. Have no real limit on size of the "entropy" we allow.

Honestly, that's _fine_ as long as we charge for the hashing (which we can do). However, the current "extern" APIs pass the entire entropy into lotus and copy it. _That's_ not ok.

Instead, we should:

1. Provide an extern that _just_ returns the VRFDigest (https://github.com/filecoin-project/lotus/blob/1ba2f23efcc99a5ce94057cf2a043ecc3376940a/chain/rand/rand.go#L30) for some given epoch (drand or chain).
2. Do all the heavy lifting in the FVM (so we don't need to copy).

In the _future_, we should replace these syscalls _entirely_ with syscalls that _just_ get the VRFDigest, computing the actual randomness inside the actors.

**Comment by Stebalien** [comment]
Alternatively, we could drop the precompile entirely. But this precompile is likely _very_ useful (e.g., because it allows users to check precommit, windowpost, etc. randomness).

**Comment by Stebalien** [comment]
To be clear:

1. Remove the domain separation tag and entropy from the extern.
2. When we get to https://github.com/filecoin-project/lotus/blob/1ba2f23efcc99a5ce94057cf2a043ecc3376940a/chain/rand/rand.go#L168 or https://github.com/filecoin-project/lotus/blob/1ba2f23efcc99a5ce94057cf2a043ecc3376940a/chain/rand/rand.go#L101, hash the first argument to `DrawRandomness` (with blake2b) and return the 32byte digest.
3. Perform the actual "draw randomness" operation in the FVM itself.

**Comment by Stebalien** [comment]
We could also do the future work now and bundle this into the FIP, now that we're tackling this issue anyways.

**Comment by Stebalien** [comment]
We're currently dropping the precompile, but we should still fix this for M2.2.

So far, @arajasek has done part of this in https://github.com/filecoin-project/filecoin-ffi/pull/348.

**Comment by arajasek** [comment]
https://github.com/filecoin-project/ref-fvm/pull/1842 moves the hashing out of the client into the FVM on `master`. We'll then want to backport this onto the v2 branch, and land BOTH of those in clients.

I'll open a separate issue to describe the consensus-breaking work of moving the hashing further into the actors themselves.
