### ISSUE TITLE
eth_getLogs - Block range filters do not work

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1285]
I'm seeing behavior where I can query for an event and find it
if `fromBlock == targetBlock == toBlock`,
but not when `fromBlock < targetBlock < toBlock`

e.g.
```javascript
await provider.getLogs({
  address: "0xa3743970690B21043c5d14A0c9418DC7bAF33A3d",
  fromBlock: 15638,
  toBlock: 15639,
  topics: []
})
=> []

await provider.getLogs({
  address: "0xa3743970690B21043c5d14A0c9418DC7bAF33A3d",
  fromBlock: 15639,
  toBlock: 15639,
  topics: []
})
=> (3) [{…}, {…}, {…}]
```

**Comment by iand** [comment]
This might already have been fixed by https://github.com/filecoin-project/lotus/pull/9815 which was merged into feat/nv18-events on 8 Dec. What version are you testing against?

**Comment by jaeaster** [comment]
Ahh ok great, looks like it's already fixed.

I'm testing against Wallaby so it's the Sapphire + patches release (on my phone so can't easily grab the direct link)
