### ISSUE TITLE
Testing: Actor creation integration test

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1287]
We need a test-case to test actor creation. Unfortunately, do to the "builtin API restrictions", we can't just cal `Init.Exec` from some random actor on-chain.

So... instead, we need to go through the EAM. Which means we need to write an EVM contract to do this.

**Comment by maciejwitowski** [comment]
@Stebalien shouldn't it be in Post-testnet milestone?

**Comment by Stebalien** [comment]
(yeah, I guess)

I'd perfer it sooner given that I introduced a bug given the lack of a test...

**Comment by Stebalien** [comment]
Was fixed by the "fil-actor-create" integration test.
