### ISSUE TITLE
Gotcha when contracts selfdestruct themselves during construction

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1328]
## Context

We identified this case in Wallaby today.

1. An EEOA sent a message to the EAM to create a smart contract, with the bytecode below.
2. The init code called `SELFDESTRUCT`.
3. The smart contract actor never made it onto the state tree, and we correctly left the gap in the actor ID sequence.

## Observation

Ethereum does not explicitly return any addresses in the return payload during contract creation. In other words, Ethereum never makes any assertions as to whether something was created or not. It's upon the creator to figure out what the address of the contract is, and then go figure if it was created or not.

However, we explicitly return the address of the newly created contract, which can be interpreted as the system asserting that the contract was effectively created. In this case, the contract _was_ created, but it destroyed itself before control was returned from the construction flow, so _effectively_ the contract does NOT exist. This is a considerable gotcha.

## Proposal

Options:

1. Return a `selfdestructed` flag from the EAM.
2. Return an `alive` or similar flag from the EAM, the opposite of the above, if we semantically feel better by tracking effective creation than potential destruction in actor logic.
3. Do nothing in code, but document this sharp edge.

## Bytecode

```
608060405234801561001057600080fd5b506000806000915060648210156101255742604051602001808281526020019150506040516020818303038152906040526040518082805190602001908083835b6020831015156100765780518252602082019150602081019050602083039250610051565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405180910390206001900490507f647ffd5b7935d31db715e3d0a4480e8cbd65382ed1d1140ffd642ff5f32aef2a81604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390a18073ffffffffffffffffffffffffffffffffffffffff16ff5b50506035806101356000396000f3006080604052600080fd00a165627a7a723058204c9b96ab8eb08fdbd1b6b60a0df3c667ed11457c6b7e2c31b95407b3906d9da50029
```

## Reference

Slack thread: https://filecoinproject.slack.com/archives/C03KGBTJ0BY/p1671251838930879

**Comment by Stebalien** [comment]
Once #1221 lands, this won't be as much of an issue as the actor will remain where it is it'll just be marked as "to be deleted at the end of the current transaction".

I believe the current confusion comes more from the fact that the current SELFDESTRUCT implementation is incorrect and immediately deletes the smart contract instead of simply marking it as "deleted". A correct implementation would, as #1221 suggests, mark the smart contract as deleted, only _deleting_ it at the end of the current transaction.

**Comment by raulk** [comment]
Hm, that's orthogonal though. In a nutshell, the issue is that the EAM creation operations return the address of an actor that doesn't exist, with no indication that the actor doesn't actually exist.

**Comment by raulk** [comment]
Nevermind. The actor will continue to exist, so it's acceptable to return its address. However, we may have to recognise this situation in the Ethereum endpoint and elsewhere. Code, nonce and balance should be reported as 0 (unless a subsequent send is received). EXTCODE* operations should behave properly too (return zero size).

**Comment by Stebalien** [comment]
Yeah, this is part of #1221
