### ISSUE TITLE
Logs: Indexing/Filtering bugs

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1345]
1. It looks like we're decoding the value before inserting it, assuming that the value is a cbor-encoded byte array. We should insert the CBOR as-is, and specify CBOR objects in the filters. See https://github.com/filecoin-project/lotus/blob/f4cc5541e4570194e8abdc043964aafdb01f9975/chain/events/filter/index.go#L198
2. We shouldn't have any "trim leading zeros" logic in the event system (https://github.com/filecoin-project/lotus/blob/f4cc5541e4570194e8abdc043964aafdb01f9975/chain/events/filter/index.go#L276). This is an Ethereum API thing. Instead:
    1. We need to trim leading zeros in the ethereum API.
    2. Then cbor-encode as a cbor "bytes".
3. As of f4cc5541e4570194e8abdc043964aafdb01f9975, https://github.com/filecoin-project/lotus/blob/f4cc5541e4570194e8abdc043964aafdb01f9975/chain/events/filter/index_test.go#L18 is broken.

**Comment by raulk** [comment]
(3) is fixed. (1) and (2) will be addressed later.

**Comment by maciejwitowski** [comment]
@raulk could @iand handle this?

**Comment by maciejwitowski** [comment]
Will move to Ian after changes in FIP49

**Comment by iand** [comment]
1 will invalidate existing data in database. Not a big deal at this time but thought I would note it here.

**Comment by iand** [comment]
While adding tests I've encountered various places where values are being compared incorrectly (cbor encoded against raw) or double decoded. I'm fixing them all to so we are consistent and tests pass. Currently the consistent position is that all filters and database entries use raw values and test against cbor-decoded event logs. Once we have the improved test coverage I will change that convention as described in this issue: all internal filters and database entries will use cbor-encoded values and we will encode/decode in the API.

**Comment by iand** [comment]
While adding tests I've encountered various places where values are being compared incorrectly (cbor encoded against raw) or double decoded. I'm fixing them all to so we are consistent and tests pass. Currently the consistent position is that all filters and database entries use raw values and test against cbor-decoded event logs. Once we have the improved test coverage I will change that convention as described in this issue: all internal filters and database entries will use cbor-encoded values and we will encode/decode in the API.

**Comment by iand** [comment]
https://github.com/filecoin-project/lotus/pull/10085 rationalises the cbor encoding hacks and fixed the broken test noted in 3 as a consequence

**Comment by iand** [comment]
https://github.com/filecoin-project/lotus/pull/10085 was merged into https://github.com/filecoin-project/lotus/pull/10083 so this should be fixed when that lands

**Comment by iand** [comment]
https://github.com/filecoin-project/lotus/pull/10083 was merged to 1.20.0 so this should be closed as done
