### ISSUE TITLE
Gas: Reprice state read/write

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1346]
We need to account for the cost of looking actors up in the state-tree, and writing them back.

**Comment by Stebalien** [comment]
Currently, we charge very little for these because we expect heavy caching. However, in an environment where users can manually trigger lookups, this is no longer true.

Unfortunately, given the current number of actors in the network, I'd expect at least 2 IPLD loads (assuming caching) for actor lookups, and likely 4 for address lookups. This comes out to 0.5M and 1M gas, respectively.

That's really expensive. We likely need to find a better approach.

- Some form of database.
- Even more aggressive caching.
- Take caching into account when computing gas costs.

**Comment by Stebalien** [comment]
Ok, so, some benchmarking. We were hoping that the EVM logic would cost more than the expected address lookup costs. From the EVM, it costs ~21801 gas to lookup a balance by ID. That's:

1. 14000 gas for the syscall.
2. ~7801 overhead.

It's ~45792 gas to lookup a balance by address (which, under the hood, resolves an address then looks up an actor). That's:

1. 14000 * 2 gas for the syscalls.
2. ~17891 overhead.

The expected _cost_ to, e.g., lookup an address plus an actor is about 6 IPLD loads (or more) which is at least 1M gas (or ~2 orders of magnitude greater).

So we definitely need to charge here.

**Comment by Stebalien** [comment]
Benchmark: https://github.com/filecoin-project/fvm-bench/pull/7

**Comment by Stebalien** [comment]
Benchmarking required:

1. The average cost, in gas, of an uncached load.
2. The average cost, in bytes, of an update.

Determining the cost of an uncached load may be a _bit_ tricky, unfortunately, due to the caching inside the state tree itself.

Really, it may be easier to _simulate_ these things by:

1. Loading an actual state-tree.
2. Performing increasing numbers of random state reads/writes (well, increasing actor IDs should be random enough given that we hash the keys).

**Comment by Kubuxu** [comment]
Results for updates: https://shuttle-10.estuary.tech/gw/ipfs/bafkreia4ywcghoe57tc5mj455ycboosdoezrfzbwzv445hsfqxizd44yyi/
Also, it includes results for reads, as an update requires a read to perform the write.

Normal gateway link: https://dweb.link/ipfs/bafkreia4ywcghoe57tc5mj455ycboosdoezrfzbwzv445hsfqxizd44yyi , but I'm getting 429 error right now.

**Comment by Kubuxu** [comment]
Let me know if you want an interpolation of the result for a specific number of state updates in a batch, I can interpolate it from the results.

**Comment by Kubuxu** [comment]
Frome sentinel, we learned that, on average, we do 262 state updates per epoch.
Which leads to the following operation having to be performed on expectation per state update:
```
:GetsNo 2.307
:PutsNo 2.307
:PutsBytes 6079.59
```
