### ISSUE TITLE
Write the "empty array" block when constructing a machine

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1359]
We assume it exists, so we should probably write it. Technically, it's guaranteed to exist (for now) as the state-tree root links to an empty CBOR "metadata" object, but it costs us (almost) nothing to just write it once whenever we create a new machine. We can even pre-hash it, so we're just copying some bytes around.

**Comment by maciejwitowski** [comment]
@Stebalien which milestone and priority?

**Comment by Stebalien** [comment]
Low. It's not great, but this won't actually cause any problems.
