### ISSUE TITLE
EVM: Precompile error return value

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1361]
We have been shoving the error message of `StatusCode` into the output of precompiles if they error. This is incorrect behavior, the return value is often nothing in the case of an error. Said error should probably be logged somewhere though.

If we no longer return the error string back to the contract we can't inspect it for expected error values inside of tests written with EVM bytecode. That means while most coverage will be with those style of tests, in order to do failure tests we will need to use normal rust unit tests for native actors like we did for the evm precompiles (unless we some cursed log inspection/parsing things).

**Comment by mriise** [comment]
There are also cases where evm precompiles are supposed to consume the gas they were sent, which we aren't doing at the moment. This is essentially burning gas for no reason, and i'm not to sure if we actually need to do this. Frankly I don't want to, but I've got a suspicion that something somewhere relies heavily on this.

**Comment by mriise** [comment]
Part of this issue needs to be testing the expected error from EVM bytecode, especially for some of the weirder evm precompiles. Tests like that would've prevented this. For native actors we don't have to worry about this as much (we are a lot less weird here) and should be fine to have failure tests as unit tests only.

**Comment by Stebalien** [comment]
Ah, I see. I thought we had already done this.
