### ISSUE TITLE
eth_feeHistory should support two styles of arguments

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1365]
This is really messy Ethereum stuff.

[Infura docs](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_feehistory) specify that this method takes hex encoded integer values.

```
curl https://mainnet.infura.io/v3/YOUR-API-KEY \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"id": 1, "jsonrpc": "2.0", "method": "eth_feeHistory", "params": ["0x5", "latest", []] }'
```

[Alchemy docs](https://github.com/alchemyplatform/alchemy-docs/blob/master/apis/ethereum/eth_feehistory.md) specifies the parameters as decimal.

```
curl https://eth-rinkeby.alchemyapi.io/v2/your-api-key \
-X POST \
-H "Content-Type: application/json" \
-d '{"jsonrpc":"2.0","method":"eth_feeHistory","params":[4, "latest", [25, 75]],"id":1}'
```

Hardhat is sending the latter:

```
POST /rpc/v0 HTTP/1.1
host: localhost:1234
connection: keep-alive
Content-Type: application/json
User-Agent: hardhat 2.12.1
content-length: 80

{"jsonrpc":"2.0","method":"eth_feeHistory","params":[4,"latest",[25,75]],"id":6}HTTP/1.1 500 Internal Server Error
Date: Fri, 23 Dec 2022 12:28:28 GMT
Content-Length: 191
Content-Type: text/plain; charset=utf-8

{"jsonrpc":"2.0","id":6,"error":{"code":-32700,"message":"unmarshaling params for 'eth_feeHistory' (param: *ethtypes.EthUint64): json: cannot unmarshal number into Go value of type string"}}
```

So we need to support both styles.

**Comment by ychiaoli18** [comment]
@raulk It may be clearer if we support both formats in the unmarshal step for the EthUint64. Although it may be incompatible with geth's behavior, I don't think there would be any issue since we support all the geth's behaviors.
