### ISSUE TITLE
EAM: review Create and Create2 caller address extraction

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1367]
Both methods mix in the caller's Ethereum address in the calculation of the smart contract's deployment address (following Ethereum rules). However there's a bit of a rough edge:

1. If the caller has an f410 address, we extract the Eth address from its payload
2. If the caller does not have an f4 address, we use the masked ID style (`0xff.....<id>`).
3. If the caller has an f4 address but it's not under the namespace 10, we error out with USR_FORBIDDEN.

We should either:
1. Not allow (2), or
2. Make (3) default to (2)

But the current state is inconsistent.

**Comment by Stebalien** [comment]
Fixed. The EAM no longer allows anything except the EVM to call these two methods.
