### ISSUE TITLE
EVM: Remove manual error destructuring

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1370]
We occasionally use manual error matching in the EVM (https://github.com/filecoin-project/builtin-actors/blob/e1ef665b2f2dca1448c04c9b439e9cdbc9e0b511/actors/evm/src/interpreter/execution.rs#L255-L259) instead of the question mark operator.

However, the perf issue was apparently fixed in https://github.com/rust-lang/rust/pull/100693, which got included in 1.64 (which we now use). We should verify that these `if let` and `match` statements are no longer performance critical, and remove them.

**Comment by maciejwitowski** [comment]
@Stebalien which milestone and priority?

**Comment by mriise** [comment]
This should be a low-ish priority item since this is code style / cleanliness

**Comment by Stebalien** [comment]
Yep. It's in M2.2.

**Comment by Stebalien** [comment]
And.... no. It might be the `map_err` call, but it's still about 1% slower.
