### ISSUE TITLE
EVM: Audit uses of "runtime.send" and replace them with "system.send"

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1374]
E.g., when getting a contract hash/bytecode. Otherwise, we can't lookup our own contract/bytecode inside the constructor.

**Comment by mriise** [comment]
There is one remaining use of runtime.send in `selfdestruct`. How this opcode behaves for us [isn't fully finalized](https://github.com/filecoin-project/ref-fvm/issues/1221) so it shouldn't block this issue, though we should be keeping this issue in mind while making the implementation for it.
