### ISSUE TITLE
Check on broken assumptions with new return value on error

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/ref-fvm#1381]
From audit

"Looks like we’ve added the ability for failing calls to pass a return value.  Is this reachable in practice with return values from new Fevm actor on failure?  Wondering if this breaks any assumptions from builtin actor code.  If this is reachable we should double check that builtin actor code doesn't rely on non return value assumption."

Unlikely to be a problem but adding for completeness

**Comment by Stebalien** [comment]
>  Is this reachable in practice with return values from new Fevm actor on failure?

Yes.

>  Wondering if this breaks any assumptions from builtin actor code.

Definitely in some cases. I know that we're "bubbling" the return value, e.g., in the init actor because `ActorError` can have a value.

We should definitely look over this more carefully.

**Comment by anorth** [comment]
The extract_send_result shared function propagates the value from sends with failing exit codes, along with the callee's exit code. I think for simplicity we probably shouldn't do this except in cases when we're explicitly expecting a value from a failed call (which is no cases today). But I also can't see a concrete problem with it.
