### ISSUE TITLE
EVM: `PUSH0` opcode EIP-3855

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1400]
https://eips.ethereum.org/EIPS/eip-3855

it is a simple opcode intended to save gas (though I don't think it would do too much for us). The EIP is part of the Shanghai upgrade so we should probably get it in for M2.1 to be ready.

**Comment by maciejwitowski** [comment]
I think we shouldn't address it now because:
- the value of adding this isn't clear and we have to focus on critical items only
- FEVM currently supports EVM up to the Paris fork, we aren't aiming for Shanghai yet

@mriise @Stebalien makes sense?

**Comment by Stebalien** [comment]
Yeah, fair enough. I'd really like to get it in.... but we don't have time, and it's not in the FIP.

**Comment by raulk** [comment]
We might have to implement this. There's a chance that compilers will start using this opcode before the next Filecoin upgrade. (AFAIK Shanghai is planned for March 2023).

**Comment by maciejwitowski** [comment]
Yep, I see your point. This is a quick one so shouldn't be a lot of problem to add it. 
OTOH, with quarterly Filecoin releases, there will be times when we'll need to say that we support `solc` version X but not the latest one, right?
This is a reminder of a bigger-picture discussion we'll need to have in a few weeks probably (after code-freeze craziness).

**Comment by mriise** [comment]
@maciejwitowski can I take this for c.3?

**Comment by maciejwitowski** [comment]
@mriise nope, this is still marked as M2.2. For c.3 adding whole bunch of FVM integration tests and fixing already existing stuff is higher priority.

**Comment by Stebalien** [comment]
(I was bored and this was really easy)

**Comment by raulk** [comment]
Good, one less thing to explain to Solidity devs when they start using a compiler version that generates PUSH0.
