### ISSUE TITLE
Audits: Create issues from audits

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1404]

**Comment by BlocksOnAChain** [comment]
@Stebalien you want me to take this one, we can triage audit reports together, but I can create issues from it, if you like that option.

**Comment by Stebalien** [comment]
I'd rather write up the issues myself (interpreting the results of the audits).

Assuming I can edit/add comments to the reports. I don't want to create issues for things that aren't relevant.

**Comment by BlocksOnAChain** [comment]
got it, makes sense. 
Let me know if I can help with the triage of issues or anything else.

**Comment by Stebalien** [comment]
(ok, I've asked dragon to take this)
(for oak, we already have everything for alex)

**Comment by BlocksOnAChain** [comment]
@Stebalien @maciejwitowski  - All the selected issues from Oak security are now added to the audits label: https://github.com/filecoin-project/ref-fvm/issues?q=is%3Aissue+is%3Aopen+label%3AAudit
I will close the issue.
