### ISSUE TITLE
Security EVM: Check nonce revert behavior on address conflict

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1407]
Specifically, check the following case:

1. Create a new contract A.
2. Have `A` create `B` with `CREATE`.
3. Have `A` self destruct.
4. Re-create `A`.

What happens if `A` calls `CREATE` again? The nonce will get reset to 1.

- Does it forever fail because of an address conflict?
- Does it fail the first time, then succeed? I.e., does the nonce get stored?

**Comment by arajasek** [comment]
@mriise volunteered to take this issue back because I'm a little underwater.

**Comment by Stebalien** [comment]
Solution: The EAM should return very specific exit codes:

1. 33 for "target contract reverted".
2. Anything else meaning that we failed to even create it.

If we get anything but 33 in the EVM, we should revert the nonce change.

**Comment by Stebalien** [comment]
So, it looks like the EVM _does not_ revert the nonce on address conflicts. That means we're doing the same thing in that case.

We _should_ be reverting the nonce when we exceed the stack limit, but I don't think this is an important issue as running out of gas won't revert the nonce.
