### ISSUE TITLE
eth_getLogs can return malformed topics and data

### ISSUE THREAD

**Issue by lalexgap** [filecoin-project/ref-fvm#1420]
Currently we have a contract [deployed to wallaby](https://explorer.glif.io/address/0x5FbDB2315678afecb367f032d93F642f64180aa3/?network=wallabynet) that raises an [event](https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/nitro-protocol/contracts/interfaces/IForceMove.sol#L86).

We're trying to query and parse events for our deployed contract using go-ethereum (which uses the json-rpc API under the hood). However it looks like some of the data we're getting back from the json-rpc API looks malformed. The topic hash and data seem to be incorrect.

Here's the hash we'd expect for the topic for the [event](https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/nitro-protocol/contracts/interfaces/IForceMove.sol#L86):
```
var concludedTopic = crypto.Keccak256Hash([]byte("Concluded(bytes32,uint48)"))
// 0x4f465027a3d06ea73dd12be0f5c5fc0a34e21f19d6eaed4834a7a944edabc901
```

If we call `eth_getLogs` with the topic hash `0x4f46...` and limited to block 3494(0xda6) :

```
curl https://wallaby.node.glif.io/rpc/v0  -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":3,"method":"eth_getLogs","params":[{"address":["0x5FbDB2315678afecb367f032d93F642f64180aa3"],"fromBlock":"0xda6","toBlock":"0xda6","topics":["0x4f465027a3d06ea73dd12be0f5c5fc0a34e21f19d6eaed4834a7a944edabc901"]}]}'
```

This is the result:
```
{
  "jsonrpc": "2.0",
  "result": [
    {
      "address": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      "data": "0x0000000000000000000000000000000000000000000000000000000063bdc405",
      "topics": [
        "0x0000000000000000000000000000000000465027a3d06ea73dd12be0f5c5fc0a",
        "0x000000000000000000000000000000000000000000000000000000f7794d6435"
      ],
      "removed": false,
      "logIndex": "0x0",
      "transactionIndex": "0x1",
      "transactionHash": "0x11f20345e885a9afe8ec27aaaf90e57cf7a70aead598b0f35640923fd1741977",
      "blockHash": "0xb1b949f9f5aa3c31ebf900721ce47dc44410218445c728603fa09ad4f45e47d2",
      "blockNumber": "0xda6"
    }
  ],
  "id": 3
}
```

The topic hashes look incorrect, since we wouldn't expect a hash to contain a bunch of 0s. However it strangely does contain part of the correct topic though:
Expected Topic: 0x4f**465027a3d06ea73dd12be0f5c5fc0a**34e21f19d6eaed4834a7a944edabc901
Received Topic: 0x0000000000000000000000000000000000**465027a3d06ea73dd12be0f5c5fc0a**

The data also doesn't look like we expect, we're expecting a fully populated bytes32 and a uint48. Instead we see a mostly empty bytes32.

If we look at the transaction on the explorer we see the correct [topic hash](https://explorer.glif.io/tx/bafy2bzacedvsbxrrj2h3r76znofseuddvnwr37rvkqbbmnqpuvtcvf3lwpnws/?network=wallabynet) but still the malformed data.

We are making used of [indexed](https://github.com/statechannels/go-nitro/blob/cd34325f023e0cffac68bf880f07ad8574cde242/nitro-protocol/contracts/interfaces/IForceMove.sol#L86) fields on the events, so perhaps that's part of the issue?

**Comment by maciejwitowski** [comment]
@raulk can you please review this issue? (is it a know/duplicated issue, what is the priority of fixing it etc)

**Comment by raulk** [comment]
Will likely be fixed with by the FIP-0049 alignment and covered by the integration tests that @iand is working on.

**Comment by maciejwitowski** [comment]
Can happen after https://github.com/filecoin-project/ref-fvm/issues/1376

**Comment by maciejwitowski** [comment]
It has been addresses 🚀
