### ISSUE TITLE
Add migration for Hyperspace upgrade

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/ref-fvm#1441]
We will kick off hyperspace net with cabonado.2, and perform an upgrde on the network with the final rc. Therefore, we will need  a simple, no-major state change migration & upgrade schedule in lotus.

The work probably would take 1 day of lotus eng.

**Comment by maciejwitowski** [comment]
@jennijuju IIUC we sort of did it yesterday for nv19. Can you help me with thinking how to approach this? (who should do it, when, what is needed exactly).

**Comment by jennijuju** [comment]
> @jennijuju IIUC we sort of did it yesterday for nv19. Can you help me with thinking how to approach this? (who should do it, when, what is needed exactly).

Hi - 
- as discussed it is better for the fvm team to handle this migration work.
- for only migrating the bundle cid see
  -  https://github.com/filecoin-project/go-state-types/pull/153
  - https://github.com/filecoin-project/lotus/pull/10040
-  if we are migration any state, i.e: adding a flag to opt-in/out method 0 send, then we will need additional code for state migration

**Comment by maciejwitowski** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/10243
