### ISSUE TITLE
FEVM | Eth Compliance Test | "`fil_actor_evm::Method::InvokeContract()` entering into infinite loop (random undefined behaviour)"

### ISSUE THREAD

**Issue by shamb0** [filecoin-project/ref-fvm#1448]
Behaviour of `fil_actor_evm::Method::InvokeContract()` with empty message `input_data` needs to be reviewed. Actor is entering into infinite loop (random undefined behaviour).

Below testsuite helps to reproduce the issue.

```
RUST_LOG=trace \
	VECTOR=test_evm_eth_compliance/test-vectors/tests/GeneralStateTests/stQuadraticComplexityTest/Call50000_rip160.json \
	cargo run -p test_fevm_eth_compliance \
	-- statetest
```

**Comment by Stebalien** [comment]
So, this is a compute intensive test and should be run in release mode. When run in release mode:

1. It passes just fine.
2. Takes 10x the block limit in gas per test.

I'm not seeing any non-determinism here.

**Comment by Stebalien** [comment]
(leaving this open till it can be confirmed)

**Comment by shamb0** [comment]
* Execution looks OK, executed use-case with `--release` flag ON. Took around 647 sec to complete the use-case on my machine.

* Issue could be closed, after acceptance review. [Trace file](https://github.dev/shamb0/fevm-eth-compliance-test-trace/tree/main/GeneralStateTests) for reference.
