### ISSUE TITLE
FEVM | Eth Compliance Test | Applicability of the test suite under FEVM context

### ISSUE THREAD

**Issue by shamb0** [filecoin-project/ref-fvm#1449]
Execution of below test suites taking too long for completion. Have to review the test suites for its acceptance.

| Skip ID | Test Suites |
| --- | --- |
| ID-0096 | stQuadraticComplexityTest/QuadraticComplexitySolidity_CallDataCopy.json |

**Comment by Stebalien** [comment]
Running it with release optimizations enabled works just fine. I'm not getting any errors.
