### ISSUE TITLE
Audit: Do a pass over dependancies for unmaintained/depricated crates

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1450]
CI is starting to yell about this now, though mainly for the security issue in wasmtime.

**Comment by maciejwitowski** [comment]
@mriise with the upgrade of Wasmtime to 4.0 do we absolutely need to pass over other dependencies for C.3?

**Comment by maciejwitowski** [comment]
@Stebalien must have for C3?

**Comment by maciejwitowski** [comment]
I'm also wondering what would be the 80/20 rule here. So we discover potential security stuff without working for too long.
