### ISSUE TITLE
Limits: Verify 1MiB Block Limit

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1451]
We need to verify the 1MiB block limit by syncing a node with the change applied. @arajasek has volunteered.

**Comment by Stebalien** [comment]
I'm now logging any block creations over 100KiB. We'll see if I get any hits.

**Comment by arajasek** [comment]
Been running this, it seems very fine so far.

**Comment by Stebalien** [comment]
Same here. I haven't seen anything over 100KiB. Closing.
