### ISSUE TITLE
EVM: propagate syscall error from send

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1452]
`send_generalized` now returnes the syscall error directly. We need to bubble this through the EVM  and:

1. Use it in the call_actor precompile.
2. Consider using it in other cases as well (e.g., actor construction).

**Comment by maciejwitowski** [comment]
@Stebalien is half-step from your PR enough for C.2 or do we need this issue resolved?

**Comment by arajasek** [comment]
Defer to @Stebalien but I think this can be a C.3 thing.

**Comment by maciejwitowski** [comment]
@mriise is this something you can handle this week? Or would @vyzo be a better person? We really need to triage a few more issues and get done this week.
cc @Stebalien
