### ISSUE TITLE
Support Hyperspace ref-fvm version selection in filecoin-ffi

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1458]
The Lotus build for Hyperspace needs to support arbitrary ref-fvm versions for Hyperspace network versions. The Hyperspace network version lineage is entirely independent from mainnet.

Proposal:
- Keep a permanent ntwk/hyperspace branch in filecoin-ffi.
- Use the multifvm abstraction to select a specific minor version of ref-fvm v3 depending on the supplied nv (Hyperspace one).

**Comment by maciejwitowski** [comment]
@jennijuju we can do it post nv18. @raulk thoughts?

**Comment by Stebalien** [comment]
Hyperspace is being retired.
