### ISSUE TITLE
Maximum stack size can be exceeded

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1462]
Prior to executing an opcode, the stack size is checked by calling the Stack::ensure function in `builtin-actors/actors/evm/src/interpreter/stack.rs.` 
If the current stack size is insufficient, the stack size is doubled, possibly increasing the stack size larger than `STACK_SIZE.`

If the `Stack::ensure` function is then called and the required size is less or equal to the current stack size, it will consider the stack size sufficient without checking the size limit. 
This leads to the stack size being increased beyond the intended limit.

_Recommendation for potential solution:_
We recommend that you check the stack size limit before checking if the stack size is sufficient.

**Comment by Stebalien** [comment]
We've rewritten this logic, but the issue was invalid anyways. 

See https://github.com/filecoin-project/builtin-actors/blob/5a4b15b9703f401ac80f7b03cc7cd84cf2fc0a25/actors/evm/src/interpreter/stack.rs#L33-L39
