### ISSUE TITLE
Retrieving the code for non-existing accounts reverts

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1463]
The opcodes `extcodesize`, `extcodecopy`, and `extcodehash` retrieve the bytecode by calling the `builtin-actors/actors/evm/src/interpreter/instructions/ext.rs::get_evm_bytecode_cid` function. However, this function returns an unhandled error in case the address belongs to a non-existent account, leading to the transaction being reverted.

On the contrary, the EVM returns `0` for `extcodesize` and the keccak256 hash of empty data for `extcodehash` (`0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`) if the target address is a non-existent account.

##### Recommendation

We recommend adhering to the EVM behavior and handling returned errors from the `get_evm_bytecode_cid` function.

**Comment by Stebalien** [comment]
Fixed. One more test to cover the final edge case.
