### ISSUE TITLE
Assert does not work as intended

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1464]
The `assert` instruction should consume all the remaining gas (main difference with `require`) running the `0xFE	INVALID` opcode.

Instead, the FEVM implementation returns an error code `33` without charging all the provided gas.

##### Recommendation to fix it:

We recommend implementing a custom behavior for the `assert` instruction in order to consume all the sender-provided gas.

**Comment by Stebalien** [comment]
Closing as won't fix. Instead, we'll document the difference (https://github.com/filecoin-project/ref-fvm/issues/1415#issuecomment-1396234353).
