### ISSUE TITLE
The `LOG` opcodes do not revert in case of a `staticcall`

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1466]
According to the EVM specification, executing `LOG` opcodes is not allowed in a `staticcall` and should revert in this case. However, the FEVM `log` function implementing the `LOG` opcodes in `builtin-actors/actors/evm/src/interpreter/instructions/log.rs` does not check if the current call is a `staticcall`.

**Comment by Stebalien** [comment]
Fixed in https://github.com/filecoin-project/builtin-actors/issues/938.
