### ISSUE TITLE
The `create2` opcode smart contract generation is not supported by FEVM.

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1468]
The FEVM does not support the creation of the smart contract using the `create2` opcode while the EVM does that. This behavior breaks the compatibility of the smart contracts that are expected to work in the FEVM.

##### Recommendation

We recommend fixing the issue to make `create2` opcode compatible in FEVM.

**Comment by Stebalien** [comment]
We have multiple tests validating the `create2` opcode, this issue was likely due to a contract deployment issue on Wallaby.

**Comment by Stebalien** [comment]
No, this was definitely a bug. I'm not sure how it wasn't caught by early builders, but it's definitely a bug...

**Comment by Stebalien** [comment]
Fixed in https://github.com/filecoin-project/builtin-actors/pull/1065.
