### ISSUE TITLE
 Retrieving the code of precompile addresses reverts

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1470]
The opcodes `extcodesize`, `extcodecopy`, and `extcodehash` revert if the target address is a precompile. Given that the FEVM considers all addresses in the range between `0x0` and `0xffff` as precompiles, the aforementioned opcodes revert for those addresses even if they are not precompiles. See `builtin-actors/actors/evm/src/interpreter/instructions/ext.rs::get_evm_bytecode_cid#L59`.

On the contrary, the EVM returns `0` for `extcodesize` and the keccak256 hash of empty data for `extcodehash` (`0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`) if the target address is a precompile.

##### Recommendation

We recommend adhering to the EVM behavior and handling the propagated error with the status code `StatusCode::BadAddress` in the `ext.rs::get_evm_bytecode_cid` function.

**Comment by Stebalien** [comment]
Fixed and tested.
