### ISSUE TITLE
Ethereum addresses in the range between `0x0` and `0xffff` are considered precompiles

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1472]
The FEVM implementation considers an address a precompile if the address is in the range between `0x0` and `0xffff`, as seen in `builtin-actors/actors/evm/src/interpreter/address.rs#L41`. However, it does not verify whether the address is a precompile, potentially leading to unexpected behavior with specific opcodes.

##### Recommendation

We recommend verifying that the address is a precompile before considering it as such.

**Comment by Stebalien** [comment]
Fixed by removing the offending code.
