### ISSUE TITLE
Misleading comment for wasm memory copy costs

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1473]
The comment in `ref-fvm/fvm/src/gas/price_list.rs#L265` states:

> // Don't yet charge anything for copying.

However, there is a cost per byte for copying memory of `Gas::from_milligas(400)`.

##### Recommendation

We recommend updating the comment to reflect the actual cost.

**Comment by Stebalien** [comment]
I'll fix this when I finish updating the gas costs.
