### ISSUE TITLE
Handle funds sent to precompiles

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1474]
1. If the precompile exists, the precompile should forward the funds to the precompile's "eth" address on-chain.
2. If the precompile doesn't exist, the call dispatch logic should send (method 0) the funds to the precompile's "f4" address.

This is stupid, but someone might be using a precompile to burn funds.

**Comment by mriise** [comment]
Should we be deploying EthAccount actors at all precompile addresses as well then? Or are we keeping null address a special case and other common "burn" addresses will be placeholder actors?

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/builtin-actors/pull/1048
