### ISSUE TITLE
EVM: Test output memory region output of call methods

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1475]
~~Need to figure out if this expected behavior for the EVM, but it was certainly unexpected for me.~~

Call family of opcodes write output to memory but we usually just read from returndata instead. We need to test that the specified memory range is being written to as well as truncated in the way that is expected.

**Comment by mriise** [comment]
We are behaving correctly it seems for now, but we should add tests to make sure we are truncating output properly

**Comment by Stebalien** [comment]
@mriise could you add some more details to the description and edit the title? I understand that this is just a testing issue, but I'm not sure what we're trying to test (where, why, etc.).
