### ISSUE TITLE
Mismatch in behaviour between sending to a self-destructed contract vs. an Eth Account

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1500]
I would imagine that sending an arbitrary message to a self-destructed account would lead to the same result as sending it to an EthAccount (i.e. noop logic simply accepting value). However:

- The EthAccount actor does not accept messages on any method numbers other than the constructor.
- A self-destructed contract will silently return an exit code OK with no data.

I think the EthAccount should accept any message sent to it regardless of the parameters or method number.

**Comment by Stebalien** [comment]
EVM -> EVM, the behavior is consistent. When an EVM contract calls an EthAccount, Account, Placeholder, etc., it turns the call into a method 0 send.

However, _off-chain_ sends still behave differently. 

> I think the EthAccount should accept any message sent to it regardless of the parameters or method number.

I wouldn't say _any_ message, but I would say that it should be callable on the FRC0042 `InvokeEVM` method.

**Comment by Stebalien** [comment]
I've filed an issue for this https://github.com/filecoin-project/ref-fvm/issues/1518.

**Comment by maciejwitowski** [comment]
Please don't forget to assign issues to FVM project. Adding them only to the milestone doesn't make them appear on [the FVM board](https://github.com/orgs/filecoin-project/projects/54/views/46)!

**Comment by maciejwitowski** [comment]
@raulk can you describe what exactly must be done here assuming https://github.com/filecoin-project/ref-fvm/issues/1518 has been filed separately?

**Comment by Stebalien** [comment]
Closing in favor of #1518. And yes, @raulk was right. We should just accept any message on EthAccount.

Context: We already have a `UniversalReceiverHook` method that does nothing so this is becoming a pattern.
