### ISSUE TITLE
Remove Hyperspace feature flag

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#1515]
Review and remove feature flag `#[cfg(feature = "hyperspace")]` added eg here https://github.com/filecoin-project/ref-fvm/pull/1512

**Comment by jennijuju** [comment]
i sus this shouold be a before code freeze thing?

**Comment by Stebalien** [comment]
We can do it now, honestly. I added it to avoid having to insert a switch in the FFI, but we'll need to do that anyways.

**Comment by raulk** [comment]
Technically this isn't code freeze material, as it only impacts code quality. But indeed, we can do it after #1627. However, we will need to:

1. Drop the nv guard here.
2. Move it over to filecoin-ffi.
3. _And_ make a patch release over the ref-fvm version on top of which this was committed.

Not sure if it's worth our time _now_.

**Comment by maciejwitowski** [comment]
I'd say it's not worth our time now. We can do it with less pressure after the code-freeze.

**Comment by raulk** [comment]
This was already removed here: https://github.com/filecoin-project/ref-fvm/commit/7c9de90acb2dcbdc8d439faa7995ee738e19e89e.
