### ISSUE TITLE
Implement FRC0042 InvokeEVM on Account & EthAccount

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1518]
This method should do nothing and always return success. There are two parts to this:

1. Implement the methods.
2. Remove the special-casing from the `CALL` opcode.

Unfortunately, we _do_ need to keep the special casing for placeholders (unless something else changes...).

**Comment by maciejwitowski** [comment]
@arajasek is this something quick that you could handle?

**Comment by arajasek** [comment]
@maciejwitowski Yessir! Steb opened a draft PR yesterday with the necessary macro fun, I can take that over the finish line.

**Comment by Stebalien** [comment]
New proposal from @anorth is to just accept any method.
