### ISSUE TITLE
fvm_ipld_car: load_car with existing CarReader failing

### ISSUE THREAD

**Issue by ozwaldorf** [filecoin-project/ref-fvm#1522]
Due to the `CarReader` taking the header bytes on creation; when passing a car reader to `load_car`, the new reader created in load car fails from the header bytes missing.

It would be useful in certain cases to be able to perform checks and or manipulate a car file before loading it into the internal store.

For example, requesting a car file from an arbitrary gateway, you'd want to make sure that the car file you get is for the data you intended for, otherwise you could potentially load a bunch of arbitrary content into the store, only know after the fact, and now need to garbage collect the store

**Comment by Stebalien** [comment]
It sounds like we need a function like:

```rust
pub fn from_parts(header: CarHeader, body_reader: R) -> Result<Self, Error> { ... }
```

Our team doesn't really have time to implement this, but I'm happy to accept a patch!
