### ISSUE TITLE
Recucsive evm call traces contain raw params

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/ref-fvm#1523]
On wallaby we StateCall trace params look like:

```
"Params": "WGTLd4bXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK",
"Params": "WGTLd4bXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK",
"Params": null,
"Params": "y3eG1wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQ==",
"Params": null,
"Params": "y3eG1wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA==",
"Params": null,
"Params": "y3eG1wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABw==", 
```

Subcall params are supposed to be a cbor byte array, but is just a raw array.

From `./lotus state --tipset @3913 compute-state --html`.

Found when debugging https://github.com/filecoin-project/lotus/issues/10038 with @shrenujbansal

**Comment by jennijuju** [comment]
does subcell params are suppose to be cobra byte array only tho?

https://github.com/filecoin-project/builtin-actors/pull/913

**Comment by shrenujbansal** [comment]
> are subcall params suppose to be cobra byte array only tho?
> 
> [filecoin-project/builtin-actors#913](https://github.com/filecoin-project/builtin-actors/pull/913)

Yes, that's the assumption we make everywhere in Lotus today
We need to make the encoding for subcalls consistent and make them a cbor byte array or include the codec in the call so we can properly decode the params

**Comment by Stebalien** [comment]
This has now been fixed in the FVM. However, codec information now needs to be plumbed through the FFI.

**Comment by Stebalien** [comment]
Fixed everywhere.
