### ISSUE TITLE
Eth JSON-RPC / event index: logs not being handled correctly

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1530]
This transaction in Hyperspace as an ERC-20 Burn: https://hyperspace.filfox.info/en/tx/0x7228d2c78caf28b84321e4a506d517cd02611279f8c9a854dec5e293b1816505

It is supposed to generate logs conforming to the `Transfer(address,address,uint256)` ABI.

Filfox correctly reported those logs:

![image](https://user-images.githubusercontent.com/1101242/213917562-2b7c3e18-4f99-4ef6-9364-1d41994f0748.png)

However, Remix IDE did not report those logs correctly. In the past, this has been due to the logs not matching the expected ABI:

![image](https://user-images.githubusercontent.com/1101242/213917600-52bf527b-71f8-4bed-a0e4-9be2db71df45.png)

There is some conversion going wrong somewhere, likely in the Eth JSON-RPC endpoint or the event index.

**Comment by maciejwitowski** [comment]
@raulk can we pass it to @iand ?

**Comment by raulk** [comment]
@iand correct, Remix does not show any logs because it fails to decode them according to the contract ABI.

**Comment by iand** [comment]
Possibly fixed by https://github.com/filecoin-project/lotus/pull/10083, but it's possible that the FVM is not encoding the events properly or they are not readable from Lotus storage. Let's re-test after https://github.com/filecoin-project/lotus/pull/10083 lands

**Comment by raulk** [comment]
This was patched in Glif and Chainstack Hyperspace endpoints to remove the blockers: https://github.com/filecoin-project/lotus/releases/tag/fix%2Fhyperspace-patch-receipt-events-20220123.

**Comment by iand** [comment]
https://github.com/filecoin-project/lotus/pull/10083 was merged so I think this will be fixed. Need to confirm using 1.20.0 branch then we can close this issue as done.
