### ISSUE TITLE
Sending FIL via FEVM on Metamask Mobile fails with Internal JSON RPC Error

### ISSUE THREAD

**Issue by scotthconner** [filecoin-project/ref-fvm#1538]
Adding Hyperspace configuration (https://api.hyperspace.node.glif.io/rpc/v0 or v1) to MetaMask on Android successfully reads contract state from dApps deployed on Hyperspace. tFIL balance shows up in-wallet.

However, sending raw tFIL on the MM mobile app results in "Transaction Error: Internal JSON-RPC error."

My only guess is that Metamask Mobile does some level of validation not done in the browser extension. There might still be lingering CBOR encoding values leaking through  that is causing problems, but I can't be sure because debugging the mobile app is significantly more limited.

The current impact seems low as it only happens on mobile, but its an indicator that something about how the EVM is interacting with clients is still causing JSON RPC issues.

**Comment by maciejwitowski** [comment]
Thanks @scotthconner for exploring unchartered territories. As you said impact is low for now, but we'll keep it in mind.

**Comment by raulk** [comment]
Possibly a usage of batched JSON-RPC calls, since mobile applications tend to be built to reduce latencies. #1047.

**Comment by maciejwitowski** [comment]
Good point, batching is usually _the way_ of sending requests on mobile (both for latency and battery)

**Comment by raulk** [comment]
We have found that the MetaMask Mobile apps use the ConsenSys Codefi APIs. The Filecoin chains have not yet been onboarded onto them:

```
export const TOKEN_END_POINT_API = 'https://token-api.metaswap.codefi.network';
```

This issue is visible when dealing with assets (e.g. tokens and NFTs). We are dealing with that on the FVM Product side of things.

However, what @scotthconner reports here is a native token send, which may or may not be related.

**Comment by raulk** [comment]
@scotthconner I successfully tested native coin transfers in MetaMask Mobile for iOS. Could you please retest on Android? We are aware of the above issue for tokens, but native coin transfers should not be affected.

![image](https://user-images.githubusercontent.com/1101242/219950922-8e35a09a-010b-48ca-9b53-9765b56d95f1.jpeg)

**Comment by scotthconner** [comment]
Native gas sends now work on Android with v1 endpoint. I noticed a considerable lah between the transactions complete notification and the balance update, but a few more blocks and everything looked right.

**Comment by raulk** [comment]
Yea, I noticed the same. We should review if we're applying our deferred execution rules correctly on eth_getBalance in the JSON-RPC. It might just be a MetaMask lag. Perhaps try on Goerli?

**Comment by raulk** [comment]
I was able to send and receive FIL via MetaMask, as well as custom ERC-20 tokens. May have been fixed by the recent addition of Filecoin to Codefi oracles.
