### ISSUE TITLE
Eth JSON-RPC: `from` in eth_getTransactionByHash is not correctly populated

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#1614]
The `from` in eth_getTransactionByHash should be the sender's address but is incorrectly populated as 0x0000000000000000000000000000000000000000

[Link to CircleCI result](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/60/workflows/2a4c82f6-61fc-4676-836c-e8817c353049/jobs/107?invite=true#step-124-56)

Lotus version: af72e6f6a

**Comment by raulk** [comment]
Fixed by https://github.com/filecoin-project/lotus/pull/10151. (For those wondering why the auto-close automation didn't work: this issue was not closed because that PR wasn't merged into the default branch of the repo, i.e. master).
