### ISSUE TITLE
Eth contract testing: Openzeppelin: EVM byte code length is exceeding the maximum allowed of 24576

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#1615]
## CI fails while testing Openzeppelin contracts

[Link to CircleCI result](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/59/workflows/ab6bfd8d-31e2-49de-961d-db992f98812e/jobs/104?invite=true#step-127-3436)

```
  1) Contract: Governor
       "before each" hook for "deployment check":
     Returned error: message execution failed: exit 16, reason: message failed with backtrace:
00: f010 (method 4) -- send to f01 method 3 aborted with code 16 (16)
01: f01 (method 3) -- constructor failed: send to f01115 method 1 aborted with code 16 (16)
02: f01115 (method 1) -- EVM byte code length (28989) is exceeding the maximum allowed of 24576 (16)
 (RetCode=16)
  Error: Returned error: message execution failed: exit 16, reason: message failed with backtrace:
      at Context.<anonymous> (test/governance/Governor.test.js:34:35)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Reproduce Steps
Follow the [README](https://github.com/filecoin-project/fevm-contract-tests/blob/hardhat-kit/README.md) to set up the environment

```
cd ./extern/openzeppelin-contracts
npx hardhat --network test test
```

**Comment by Stebalien** [comment]
The EVM's max code size is 24KiB. Are you sure you aren't importing things you don't need?

**Comment by ychiaoli18** [comment]
The same test pass if run against the hardhat network, a local evm for testing purposes. My hypothesis is that hardhat doesn't check the bytecode length because both the bytecode and deployedByteCote are over 24KiB, but this has to be verified.
