### ISSUE TITLE
Eth contract testing: Openzeppelin: Contract: TransparentUpgradeableProxy

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#1620]
## CI fails while testing Openzeppelin contracts

[Link to CircleCI result (16)](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/59/workflows/ab6bfd8d-31e2-49de-961d-db992f98812e/jobs/104?invite=true#step-127-3604)
[Link to CircleCI result (17)](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/59/workflows/ab6bfd8d-31e2-49de-961d-db992f98812e/jobs/104?invite=true#step-127-3618)

## Reproduce Steps
Follow the [README](https://github.com/filecoin-project/fevm-contract-tests/blob/hardhat-kit/README.md) to set up the environment

```
cd ./extern/openzeppelin-contracts
npx hardhat --network test test
```

**Comment by Stebalien** [comment]
This is now succeeding: https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/135/workflows/f81b48c5-6c67-42ea-8354-ab849474036f/jobs/365

The issue was _probably_ the fact that we weren't running fallback functions on transfer.
