### ISSUE TITLE
Eth contract testing: Openzeppelin: Contract: Address

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#1621]
## CI fails while testing Openzeppelin contracts

[Link to CircleCI result](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/59/workflows/ab6bfd8d-31e2-49de-961d-db992f98812e/jobs/104?invite=true#step-127-3730)

## Reproduce Steps
Follow the [README](https://github.com/filecoin-project/fevm-contract-tests/blob/hardhat-kit/README.md) to set up the environment

```
cd ./extern/openzeppelin-contracts
npx hardhat --network test test
```

**Comment by Stebalien** [comment]
Fixed https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/135/workflows/f81b48c5-6c67-42ea-8354-ab849474036f/jobs/365

**Comment by Stebalien** [comment]
Nvm: https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/135/workflows/f81b48c5-6c67-42ea-8354-ab849474036f/jobs/365?invite=true#step-126-3404

**Comment by Stebalien** [comment]
Turns out we weren't correctly decoding the response when looking up storage slots.

**Comment by Stebalien** [comment]
Verified fixed.
