### ISSUE TITLE
Eth contract testing: Openzeppelin: Contract: DoubleEndedQueue

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#1622]
## CI fails while testing Openzeppelin contracts

[Link to CircleCI result](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/59/workflows/ab6bfd8d-31e2-49de-961d-db992f98812e/jobs/104?invite=true#step-127-4258)
[Link to CircleCI result](https://app.circleci.com/pipelines/github/filecoin-project/fevm-contract-tests/59/workflows/ab6bfd8d-31e2-49de-961d-db992f98812e/jobs/104?invite=true#step-127-4267)

## Reproduce Steps
Follow the [README](https://github.com/filecoin-project/fevm-contract-tests/blob/hardhat-kit/README.md) to set up the environment

```
cd ./extern/openzeppelin-contracts
npx hardhat --network test test
```

**Comment by Stebalien** [comment]
This is just testing the error message.
