### ISSUE TITLE
Timestamp supplied to FVM around null rounds is wrong / needs clarification 

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#1632]
As currently implemented in the reference implementation, the FVM is created with a "timestamp" always corresponding to the non-null round being executed. However, this gets tricky around null rounds, which still have execution (cron) that needs to occur. We need to:

- clarify what the correct behaviour is (see [here](https://github.com/filecoin-project/FIPs/discussions/592#discussioncomment-4852715))
- Fixup clients if necessary (likely necessary).

Note that this doesn't _actually_ have any consequences right now, because none of the Cron operations query the timestamp, but we should align and fixup.

**Comment by raulk** [comment]
Fix merged in https://github.com/filecoin-project/lotus/pull/10189.
