### ISSUE TITLE
Miner is not penalized for messages with an improper gas limit

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1634]
The `DefaultExecutor::preflight_message` function in `ref-fvm/fvm/src/executor/default.rs` does a preliminary check of the message before further processing. Message validity is checked with the `Message::check` function in `ref-fvm/shared/src/message.rs#L32`. The `check` function validates the message gas limit. However, if the check fails, the message fails without penalizing the miner.

##### Recommendation from the audit team:

We recommend penalizing the miner for such invalid messages with an appropriate penalty.

**Comment by jennijuju** [comment]
@arajasek will check on the client lotus side

**Comment by arajasek** [comment]
Yeah, this isn't something the FVM needs to verify, it expects the client to have performed this check already. It's obviously fine that the FVM sanity checks it, but no penalty needs to apply here.

**Comment by Stebalien** [comment]
Thanks!
