### ISSUE TITLE
Improved event syscall API

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1637]
Currently, events are emitted as CBOR objects. Unfortunately, this makes it hard to accurately charge gas for parsing.

**Proposal:**

Emit three buffers:

- `entries`: An array of `[(flags: u64, codec: u64, key_len: u32, value_len: u32), ...]`  (packed). I.e., 24 bytes per event.
- `keys`: A buffer of all keys, concatenated.
- `values`: A buffer of all values, concatenated.

The FVM will:

1. Compute the number of entries as `entries.len() / 24` (or return an error if not a multiple of 24).
2. Charge gas based on the number of entries, the length of `keys`, and the length of `values`.
3. Reconstruct the events from these parameters.

Importantly, this means the FVM can accurately charge gas before parsing anything.

**Comment by aashidham** [comment]
Does this have any product implications with the emission of events? What about event listeners? 

Will this generally make sending events to the event log more or less expensive?

**Comment by Stebalien** [comment]
This won't have any user-facing implications.

This issue is purely security/performance related. Although it may make emitting events less expensive as it may be less expensive to validate them? But that's unclear.
