### ISSUE TITLE
eth_getCode failing on delegated address (2k localnet build)

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/ref-fvm#1641]
I've encountered a regression that is causing `forge script` to fail when running against a localnet with 2k sectors built against `ntwk/hyperspace`:

The address here is new, and I transferred some funds to it via the delegated `t4` address.

```
$ cast rpc --rpc-url=https://glif-fvm-hyperspace-20230203-b46258d.quick.cluster-3.localnet.farm/rpc/v1 eth_getCode 0x3972E844729522d367BFA1D64368346D7ccEEa59 0x1c
Error: 
(code: 1, message: failed to decode EVM bytecode CID: EOF, data: None)
```

It should return "0x".

```
$ lotus version
Daemon:  1.19.1-dev+2k+git.b46258d.dirty+api1.5.0
Local: lotus version 1.19.1-dev+2k+git.b46258d.dirty
```

This was working in a build against `v1.20.0` at commit 60193a2, but not in recent builds there either, so I think it's a regression.

The public hyperspace gateway seems OK:

```
$ cast rpc --rpc-url=https://api.hyperspace.node.glif.io/rpc/v1 eth_getCode 0x3972E844729522d367BFA1D64368346D7ccEEa59 0x1c
"0x"
```

**Comment by Stebalien** [comment]
Yep, thanks for reporting.

**Comment by Stebalien** [comment]
Hm. Actually, I'm not sure what this is. I found _a_ bug, but I'm not sure if it's this one.

**Comment by Stebalien** [comment]
Ah, I see. The issue is that placeholders now return "nothing" for all methods. So we'll then fail on the decode step.

**Comment by jimpick** [comment]
This is preventing me from using `forge script` to deploy contracts, so I'm still using a build from January (before the regression) for the project I'm working on. It would be great to see a fix!

**Comment by Stebalien** [comment]
I'm not sure how this worked before, that's what's confusing me.

**Comment by Stebalien** [comment]
@jimpick https://github.com/filecoin-project/lotus/pull/10246 should fix it (hopefully).
