### ISSUE TITLE
Illegal argument error when calling block.difficulty

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#1648]
This was found as part of [the Bulletproofing program](https://www.notion.so/pl-strflt/block-difficulty-contract-issue-it-will-be-solved-74f8a5084c0a4c1497fd61ec3210081d)

Calling this function 
```
function getDifficulty () public view returns (uint256) {
  return block.difficulty;
}
```
produces this error 

> "message": "failed to apply message: message execution failed: exit 24, msg receipt: , reason: message failed with backtrace:\n00: f010866 (method 3844450837) -- get beacon randomness failed with an unexpected error: illegal argument (24)\n--> caused by: rand::get_beacon_randomness -- cgo extern 'get_beacon_randomness' failed with error code -3 (1: illegal argument)\n (RetCode=24)"

**Comment by maciejwitowski** [comment]
When I'm getting this error in Remix my local lotus shows this error
> 	ERROR	rand	rand/rand.go:164	failed to get beacon entry as expected: cannot draw randomness from the future

**Comment by Stebalien** [comment]
Should be fixed by https://github.com/filecoin-project/lotus/pull/10216, but I haven't tested it.

**Comment by Stebalien** [comment]
Basically, when estimating gas and testing messages, we were passing a chain height in the future with the wrong tipset.
