### ISSUE TITLE
Test: Gas Fuzzing V2

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1667]
Now that we have #1489, let's use those contracts to try to find bugs automatically.

Specifically, let's:

1. Run the contract with some reasonable gas limit.
2. Look at the _gas trace_.
3. Use the gas trace to set limits and force the contract to run out of gas just before/after various points in the trace.
4. Ensure that we always fail with "out of gas" and that nothing else happens.

**Comment by Jacarte** [comment]
Well, this is actually what we are doing in https://github.com/filecoin-project/Fuzzing-FVM  right?

**Comment by Stebalien** [comment]
@Jacarte yes, but this one is targeted and deterministic. I.e., regression testing (this one) versus bug finding (general fuzzing).

**Comment by Jacarte** [comment]
Gotcha
