### ISSUE TITLE
Review and update deprecated dependencies

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#1682]
We updated some dependencies in https://github.com/filecoin-project/ref-fvm/pull/1508 but we still use a few deprecated ones.
Examples provided by @anorth 
- ansi_term (unmaintained 3y)
- mapr (unmaintained - merged back into memmap2)
- memmap (unmaintained/unresponsive - use memmap2?)
- parity-wasm (deprecated by author in favour of wasm-tools)

**Comment by Stebalien** [comment]
- ansi_term and parity-wasm are build dependencies for tests (through substrate-wasm-builder). I'd like to get rid of this (it's keeping us on rust nightly) but it's not really a priority (only a test dep).
- memmap and mapr are dependencies of proofs. I'd like to remove them, but that requires a proofs release. It's not worth wrangling that so close to the release, but I'll ask and see if we can get a release _after_ the release (it's been over half a year at this point).

**Comment by anorth** [comment]
These came to my attention due to transitive dependency in actors, but it seems like they're all only used for testing, so thanks.

**Comment by fridrik01** [comment]
The ansi_term and parity-wasm transitive dependencies are will be gone once we land https://github.com/filecoin-project/ref-fvm/pull/1698. I still think there are some unused imports spread around the project, might be worth looking into

**Comment by Stebalien** [comment]
All of these have been fixed. We still have a couple of unmaintained crates, but nothing serious.
