### ISSUE TITLE
block.difficulty contract issue from FVM bulletproofing program

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1707]
Given the contract:
pragma solidity 0.8.17;contract TestBlockDifficulty {  function getDifficulty () public view returns (uint256) {    return block.difficulty;  }}

Running this on EVM we manage to execute without issues and return some values...

**However, on FVM it fails with "message**": "message execution failed: exit 24, msg receipt: ,
reason: message failed with backtrace:\n00: f01026 (method 3844450837) -- get beacon randomness failed with an unexpected error: illegal argument (24)\n--> caused by: rand::get_beacon_randomness -- cgo extern 'get_beacon_randomness' failed with error code -3 (1: illegal argument)\n (RetCode=24)"

**Comment by BlocksOnAChain** [comment]
CC: @maciejwitowski @Stebalien for visibility and prioritization

**Comment by Stebalien** [comment]
I believe this was fixed a while back. Basically, when estimating gas, we were passing an epoch from the future which caused `block.difficulty` (or `PREVRANDAO`) to try to lookup randomness from the future.

We no longer do that.
