### ISSUE TITLE
Fix Github integration failures due to running out of disk space

### ISSUE THREAD

**Issue by fridrik01** [filecoin-project/ref-fvm#1710]
I have noticed a failing integration test on my PR (https://github.com/filecoin-project/ref-fvm/pull/1698) that is due running out of disk space on the hosted github CI.

The GH [hardware specs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) for these runners list 14GB SSD space - however sometime they _can_ have more disk space than that )

Since our default cargo build and tests generate build artifacts that are awfully close to this limit or even higher then this seems easy to generate flaky tests.

We should update our testing pipeline to minimize binary artifact sizes. For example, there are several huge test binaries  (on_verify_signature, on_event_evm_shapes, etc) that each over 700MB each which we can try strip in our CI tests at least.

**Comment by Stebalien** [comment]
FYI, https://github.com/filecoin-project/ref-fvm/issues/1705 is also likely related.
