### ISSUE TITLE
GAS费比以太坊贵,EVM调用执行速度比以太坊慢，连个查询都要超过7秒才返回，望优化

### ISSUE THREAD

**Issue by cocoyes** [filecoin-project/ref-fvm#1723]
GAS费比以太坊贵,EVM调用执行速度比以太坊慢，连个查询都要超过7秒才返回，望优化
![image](https://user-images.githubusercontent.com/24385018/226550826-c6389c43-198b-4e39-8fbf-356aeb11f68a.png)

**Comment by Stebalien** [comment]
- The gas fees are a different unit, think inches versus centimeters.
- Query times are being optimized.

If you need further support, please ask on slack.
