### ISSUE TITLE
implement logging from actors

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#173]
There's a placeholder `log` syscall to emit arbitrary string-based log messages from actors, tagged with a level/severity. Currently it's not wired through on the kernel side. There are various options here:

1. Make the FVM library write log to disk.
    - Pros: less FFI interface complexity, VM logs across implementations are normalized.
    - Cons: making a embedded FFI library own file handles is a bit dodgy, but I can be convinced.
2. Make the FVM accumulate logs, and return them to the node via the FFI return value.
    - Pros: the node can do whatever it wants with the logs; logs can be better integrated by printing them into the node's logging system.
    - Cons: accumulation in memory means higher memory usage; FFI interface is a bit more complex; no normalized logs across implementations.

This feature should only be available on debug settings through conditional compilation. When debug is off, it should be zero overhead where possible. That is:

- zero overhead in terms of alloc
- zero overhead in terms of WASM bytecode size (i.e. logged strings should not be embedded, and log code should be included).
- zero overhead in terms of IO/compute/gas

**Comment by Stebalien** [comment]
The only remaining part is exposing the log level. I'd like to replace `debug::enabled` with `debug::log_level`.

**Comment by raulk** [comment]
Opened #839 to track the remaining item.
