### ISSUE TITLE
Prepare a branch on top of the latest version which has native actors feature enabled

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#1741]
This is needed for Polyphene for their work on Kythera https://github.com/filecoin-project/devgrants/issues/1154

**Comment by Stebalien** [comment]
Is the request for a devnet? I've merged `master` into `next` in the builtin actors and the m2-native feature seams to work here as well.

I can also build a bundle.

**Comment by maciejwitowski** [comment]
@Stebalien I vaguely remember we discussed it already. Were you able to integrate to Lotus in the end?

**Comment by maciejwitowski** [comment]
@Stebalien turns out there may be changes to this project. We can wait with the branch.

**Comment by Stebalien** [comment]
Ok, https://github.com/filecoin-project/lotus/tree/experimental/fvm-m2 should be all set for devnets (only).

I initially tried to set it up as a new network type, but that was more pain than it was worth. Instead, I'm just replacing devnets with "wasm" devnets, which significantly reduces the diff.
