### ISSUE TITLE
getBlock return an Error

### ISSUE THREAD

**Issue by amncjf** [filecoin-project/ref-fvm#1782]
I in https://api.hyperspace.node.glif.io/rpc/v1 call getBlock (294023) interface, return an Error: Error: requested epoch was a null round, Recommended return:
{
...prevBlock,
parentHash: prevBlock.hash,
blockNumber: prevBlock.blockNumber+1,
}

**Comment by Stebalien** [comment]
There is no block there so no return value will be correct. We have no way of specifying the block miner, etc.

Why do you need this?

**Comment by Stebalien** [comment]
Closing due to https://github.com/filecoin-project/lotus/issues/10909. Let's continue there.
