### ISSUE TITLE
Make flush putMany batches larger

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/ref-fvm#1786]
When initially working on https://github.com/filecoin-project/lotus/pull/10821 I've noticed that statetree flushes do writes in small batches. Would be nice to make those larger

**Comment by Stebalien** [comment]
Basically, right now we put at most 1024 blocks or 4MiB of data:

https://github.com/filecoin-project/filecoin-ffi/blob/64cbc26039b73131e9d9f11a4483a8d1178376f7/rust/src/fvm/blockstore/cgo.rs#L10-L14

We should increase this. There's no reason not to pass up to 100MiB at once and maybe 10k blocks?
