### ISSUE TITLE
`Cid#write_bytes()` make it return number of bytes written

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#180]
So we can get rid of hidiousness like this: https://github.com/filecoin-project/fvm/pull/166/files/5cc4339d6f42d0f231e7aa8534b91d96468837c2#diff-8cecd06403506bae35593d8a965b8d972de46bce54e8ee0d6f3fd5863047e715R86-R97

**Comment by Stebalien** [comment]
We've side-stepped this issue with an intermediate buffer.
