### ISSUE TITLE
irrecoverable errors are recoverable

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#182]
Not all syscall errors need to be returned to the actor via the implicit result code output param. Some syscalls can abort immediately in kernel-land and still produce an exit code on chain. 

These are the `rt.Abortf` inside [Lotus’ runtime](https://github.com/filecoin-project/lotus/blob/master/chain/vm/runtime.go) (sometimes via explicit panic, sometimes via rt.Abort, which in turn panics).

Currently we rely on the actor to rethrow those errors. This is passable for M0 and M1, since only built-in actors are supported, but it's not OK for M2+ since the locus of control for such errors must be in the kernel (trusted domain), and not in the actor (untrusted domain).

Examples:

* CircSupply: https://github.com/filecoin-project/lotus/blob/master/chain/vm/runtime.go#L101 (*) probably should be a fatal error
* Serde error: https://github.com/filecoin-project/lotus/blob/master/chain/vm/runtime.go#L127
* Current balance: https://github.com/filecoin-project/lotus/blob/master/chain/vm/runtime.go#L208 (*) probably should be a fatal error

One way to solve this is to add an `irrecoverable` flag to `SyscallError` (with associated macro syntax) to instruct the syscall handler to immediately abort execution instead of relaying the error to the actor.

**Comment by jennijuju** [comment]
related actor issue https://github.com/filecoin-project/builtin-actors/issues/53
