### ISSUE TITLE
Contract works well on calibration testnet but not on mainnet

### ISSUE THREAD

**Issue by Sunnight-wj** [filecoin-project/ref-fvm#1822]
I deployed a contract which works well on calibration testnet on filecoin mainnet, but found one function not works.I repeatedly checked the source code and make sure that they are consistent on the two chains.I guess it's due to some differences between these two chains.
Anyone know more about it?

**Comment by Stebalien** [comment]
There should be no differences in terms of the EVM implementation but we'd need more information to debug what's actually going on.
