### ISSUE TITLE
fvm2 depends on unmaintained crates

### ISSUE THREAD

**Issue by aatifsyed** [filecoin-project/ref-fvm#1843]
As of `fvm 2.5.0` (https://github.com/filecoin-project/ref-fvm/commit/c06182a776abe62c43681802bf5cdb3b4da4a87c I think), `fvm` depends on unmaintained crates, two of which show up when auditing [forest](https://github.com/ChainSafe/forest):

```console
$ cargo audit
...
Crate:     mach
Version:   0.3.2
Warning:   unmaintained
Title:     mach is unmaintained
...

Crate:     parity-wasm
Version:   0.42.2
Warning:   unmaintained
Title:     Crate `parity-wasm` deprecated by the author
...
```

I see you've removed them in 3.x release train (https://github.com/filecoin-project/ref-fvm/issues/1682), WIBNI to get rid of them for 2.x too

**Comment by Stebalien** [comment]
- We depend on mach through wasmtime, which we can't fix.
- We depend on parity-wasm for wasm instrumentation. We can't change this in the v2 FVM as we can't guarantee that our new instrumentation logic is identical (it may cause consensus issues).

So there's not much we can do about either dependency, unfortunately.
