### ISSUE TITLE
Remove go-interop feature from the AMT

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1856]
I _believe_ this feature exists solely to ensure that gas usage matched go. Now that we compile everything to wasm, we should be able to remove it.

https://github.com/filecoin-project/ref-fvm/blob/9e2b2afa04ce6722ca9ce6eb3d9e3953a54fef3f/ipld/amt/Cargo.toml#L21

https://github.com/filecoin-project/ref-fvm/blob/9e2b2afa04ce6722ca9ce6eb3d9e3953a54fef3f/ipld/amt/src/amt.rs#L487-L547

But I lack the context to say for certain.

**Comment by LesnyRumcajs** [comment]
Currently, Forest doesn't use the `go-interop` feature for `fvm_ipld_amt`. We _might_ need it in the future when dealing more with the pre-FVM network versions, though I'm not sure that a feature flag is the way to go in such a case.

As it stands, I'm okay with removing it and to look for an alternate solution when a need arises.

@lemmih are you okay with this?

**Comment by lemmih** [comment]
Yes, I think we should remove it.

**Comment by Stebalien** [comment]
Note: this _likely_ requires modifying the builtin actors. Anyone from your team want to take this?

**Comment by LesnyRumcajs** [comment]
I believe this would be me! To make sure the workflow between `builtin-actors` and `ref-fvm` is understood by me:
1. Do the change in `ref-fvm`.
2. Do the change in `builtin-actors` with [this](https://github.com/filecoin-project/builtin-actors/blob/fe72aa8e14bc566d661d47625dcdbdd960bf4525/Cargo.toml#L180C8-L180C50) to ensure all is still good.
3. PR with getting rid of `go-interop` in this repo.
4. After merging, nag someone for a release.
5. PR in builtin-actors with the updated `fvm_ipld_amt` version.

Is this correct? Am I missing anything or any other repo the change should be reflected in?

**Comment by Stebalien** [comment]
Yes. Although you may be able to just change the builtin actors first to avoid that dance (as far as I can tell, the change _here_ just involves removing the feature, so you should be able to disable that feature in the builtin actors first).
