### ISSUE TITLE
Implement external iteration for the KAMT

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#1862]
Port the changes in #1833 to the KAMT. This _should_ be fairly straight-forward.

**Comment by lordshashank** [comment]
Hey @Stebalien I am working on this issue, I am implementing writing iter.rs for kamt types referring to that implemented for hamt types, I could not find the load function for node in kamt type so as to implement the Link case for next node as done here for hamt type. Should I have to write the load function for kamt node or am I doing something wrong, would be great if you could  help.

**Comment by Stebalien** [comment]
I am currently on vacation and won't be back for a few weeks. However, I think the answer is no.

See the original implementation in https://github.com/filecoin-project/ref-fvm/pull/1833/files. The `load` function came afterwards and exists to perform more paranoid validation. I'd like to port that as well, but that's a separate task.

**Comment by lordshashank** [comment]
Hey @Stebalien raised a pr resolving this https://github.com/filecoin-project/ref-fvm/pull/1958 . Feel free to review it whenever you get time.
