### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by smpcoin** [filecoin-project/ref-fvm#1868]
legacy transaction is not supported [Method] eth_sendRawTransaction

**Comment by Stebalien** [comment]
It's not supported, yes. You need to use newer tooling.

**Comment by smpcoin** [comment]
@Stebalien So how do I interact with smart contracts through rpc？

**Comment by Stebalien** [comment]
Lotus supports EIP1559 transactions. The quick-start guide is here: https://docs.filecoin.io/smart-contracts/fundamentals/erc-20-quickstart/.

Beyond that, you'll have to ask on slack or the forums (https://github.com/filecoin-project/community/discussions/categories/developers). This is a bug tracker, not a support forum.
