### ISSUE TITLE
CI `ubuntu-latest - test` job sometimes failing `test_debug` check

### ISSUE THREAD

**Issue by jdjaustin** [filecoin-project/ref-fvm#1924]
This is not a consistent failure, but seems to occur randomly. `ubuntu-latest - test` job's `test_debug` check somtimes fails with a mismatched address. See screenshot below:
<img width="1066" alt="Screen Shot 2023-11-15 at 12 00 11 PM" src="https://github.com/filecoin-project/ref-fvm/assets/11778588/c509a69d-54e6-4c03-a25e-be16eff26b03">

**Comment by Stebalien** [comment]
Yeah, so, this is due to the `set_network` test. Unfortunately, rust runs tests in threads not processes.
