### ISSUE TITLE
TODOs from AMT external iterator implementation PR

### ISSUE THREAD

**Issue by jdjaustin** [filecoin-project/ref-fvm#1925]
Capturing a couple TODOs from #1912 in a new issue.

``TODO(jdjaustin): in another PR: remove or refactor version typestate, and refactor `AmtImpl` ``
(needs elaboration from @aatifsyed on reasoning and expectations of desired end result)

`TODO(aatifsyed): is this guaranteed to be acyclic?`

**Comment by Stebalien** [comment]
I'm guessing no action will be taken with respect to this issue, so I'm just going to close it. External iteration works and has been merged.
