### ISSUE TITLE
Make `module` expr in the `fvm_syscalls` macro

### ISSUE THREAD

**Issue by mikevoronov** [filecoin-project/ref-fvm#1979]
Atm `module` in the `fvm_syscall` macro has type `literal` which prevent using variables to set it, although it'd be useful, because the same module name literal is used at least twice: the first is in this macro and the second is in `link_syscalls`. I propose changing its type to `expr` which allow using variables.

**Comment by Stebalien** [comment]
Unfortunately, they have to be literals as they're used in attributes to declare build-time import paths.
