### ISSUE TITLE
Implement FIP-0079 with Backwards Compatibility

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/ref-fvm#2001]
## Description
[FIP-0079](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0079.md), which has been accepted, introduces a syscall for BLS aggregate signatures. It has a PR open in https://github.com/filecoin-project/ref-fvm/pull/1914, but it has not been merged due to concerns about requiring a major FVM version update. 

After some discussion we have leaned towards merging this feature under a feature flag to avoid the need of a major version update. This approach would allow the inclusion of the FIP in the upcoming network upgrade without waiting for other significant changes that necessitate a new FVM version.

### Task 
The current PR is outdated and has a lot of conflicts. We need to created a new branch and copy the PR changes in, make it backwards compatible and add it behind a feature flag.

### References
- FIP-0079: [Syscall for BLS Aggregate Signatures](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0079.md)
- PR Discussion: [Add syscall for BLS aggregate signatures #1914](https://github.com/filecoin-project/ref-fvm/pull/1914)

**Comment by Stebalien** [comment]
Basically:

1. We _can_ make breaking changes to the SDK, as long as we bump the minor version.
2. We _can't_ remove the current `verify_signature` syscall.
3. We _can_ add and use the new `verify_bls_aggregate` syscall.

So, TODO: Bring back the `verify_signature` syscall behind an enabled-by-default feature. E.g. IPC can disable it.

**Comment by rvagg** [comment]
👍 it's good not to break things if we don't really need to, especially if it means shipping features that users are asking for 🚢

**Comment by rvagg** [comment]
This requires an update to FIP-0079 to remove the references to `verify_signature`, correct?
