### ISSUE TITLE
Simplify machine constructor

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#249]
Mainly, it takes too many arguments. Many of these (epoch, base fee, state root, etc.) should be moved to a new struct describing the current Filecoin state.

**Comment by jochasinga** [comment]
May I suggest breaking the `DefaultMachine` constructor into a builder?

```rust
let machine = MachineBuilder::new(config)
    .with_epoch(epoch)
    .base_fee(fee)
    // ...
    .build();
```

This creates an opportunity to have default values for things like epoch and fee, for instance. Also, it would be nice to simplify `Machine` so it implements `Default` so users can just call `Machine::default()` rather than `DefaultMachine`.

**Comment by Stebalien** [comment]
That might be enough. My concern is that many of these don't have reasonable defaults (which is where the builder pattern really shines). In this case, I'd probably pass some form of "network state" object.

**Comment by jochasinga** [comment]
@Stebalien `MachineContext` already wrap most of the data that are passed into the constructor of `DefaultMachine` that it can just take the context as a parameter:

```rust
pub fn new(
        config: Config,
        context: MachineContext,
        network_version: NetworkVersion,
        state_root: Cid,
        blockstore: B,
        externs: E,
    ) -> anyhow::Result<Self>;
```

Or introducing another struct `NetworkConfig` (or `NetworkState`) that wraps the rest of the state, shortening the list of parameters:

```rust
struct NetworkConfig {
    version: NetworkVersion,
    state_root: Cid,
}

// ...

pub fn new(
        config: Config,
        context: MachineContext,
        network: NetworkConfig,
        blockstore: B,
        externs: E,
    ) -> anyhow::Result<Self>;
```

**Comment by jochasinga** [comment]
With further inspection, it seems `Config` has a default implementation and most of the arguments are for building `MachineContext`. What do you think if the API is focus on `MachineContext`?:

```rust
struct MachineBuilder;
impl MachineBuilder {
    pub fn new(context: MachineContext, blockstore: B, externs E) -> anyhow::Result<&mut Builder>;
    pub fn config(&mut self, config: Config) -> &mut Builder;
    // This will use Config::default()
    pub fn build() -> DefaultMachine;
 }
```

Where `network_version` (the only "orphan" argument) can be part of `Config`:

```rust
pub struct Config {
    // existing fields
    network_version: NetworkVersion,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            // other defaults
            network_version: NetworkVersion::stable(),   // default to latest
        }
    }
}
```

**Comment by jochasinga** [comment]
@Stebalien bumping for visibilty.

**Comment by Stebalien** [comment]
- The builder doesn't add much.
- The machine context is a bit of a mashup:
    - It derives the price list from the epoch.
    - It derives takes the debug flag from the config.

I think we made a mistake marking this as a "good first issue". It's a low-priority refactor, but the right solution is non-obvious.

**Comment by Stebalien** [comment]
But I do owe you an apology, I should have relabeled this the second I saw that the obvious builder solution wouldn't work.
