### ISSUE TITLE
Audit Fatal Errors

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#262]
Currently, we have a lot of "fatal" errors. I.e., errors that users shouldn't be able to cause and that mean we should abort everything because something is very wrong.

However, it's generally best to continue if at all possible, only returning a fatal error if either:

1. The node really can't continue.
2. The error is clearly an issue with the local machine (e.g., missing state, fail to put state, etc.).

On the other hand:

1. We should generally assume that errors in rust-crypto are _not_ fatal, but instead somehow related to the proof itself.
2. If we fail to lookup some actor when we shouldn't, that likely means that there is a bug in the network, but it's better to let the network continue and let that single actor fail rather than halt the network.
3. If we fail to serialize/deserialize, we should always assume this is some localized error.

**Comment by jennijuju** [comment]
- [ ] https://github.com/filecoin-project/ref-fvm/issues/341

**Comment by raulk** [comment]
@jennijuju ^^ I think the issue you linked is unrelated.

**Comment by Stebalien** [comment]
This is what we discussed on the call yesterday. Basically, we need to audit these carefully and:

1. When possible, don't have a "fatal" error.
2. When not, convert to an "assertion failed" error and abort the message (but not the chain).
3. Only fail with a truly fatal error if the node is totally borked.

But a first pass would be to make sure that all of our fatal errors are _actually_ fatal, and try to make up codes for the ones that may not be.

**Comment by Stebalien** [comment]
We now convert fatal errors to on-chain exit codes. I've also gone and audited all errors in https://github.com/filecoin-project/ref-fvm/pull/576.
