### ISSUE TITLE
Optimize actor performance

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#265]
Performance is going to be pretty critical. We need to investigate things like:

1. [ ] Trade-offs between "z", "s" and "3" optimization levels (for actors).
2. [ ] Passing different optimization options to wasmtime.
3. [ ] Enabling simd in wasmtime.
4. [ ] Performing SHA256 hashing (used inside HAMTs) via a syscall instead of inside WASM.
5. [ ] Actor optimizations (e.g., some cases could benefit from using btrees instead of hashmaps/sorting).
6. [ ] Syscall overhead (does our syscall glue optimize out well?).

**Comment by raulk** [comment]
@Stebalien I suspect you already analyzed these AIs:

>  Trade-offs between "z", "s" and "3" optimization levels (for actors).
>  Passing different optimization options to wasmtime.

Mind posting your discoveries?

**Comment by Stebalien** [comment]
> Trade-offs between "z", "s" and "3" optimization levels (for actors).

I haven't. Well, I tried, but it turns out that the wasm builder was ignoring our flags when I last tried.

**Comment by raulk** [comment]
@Stebalien which of these investigations are still pending? I think we should track the open ones as issues in builtin-actors.

**Comment by Stebalien** [comment]
There really isn't much use in tracking this.
