### ISSUE TITLE
Hash digest syscall

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#270]
Currently, we have a single `hash_blake2b` syscall. I'd like to consider a more general `hash` function:

```rust
mod crypto {
    pub fn hash(multihash_code: u64, data: *const u8, data_len: u32, digest: *mut u8, digest_len: u32) -> u32 /* bytes written to digest */;
}
```

This would let us easily support arbitrary multihash codes in the FVM itself. NOTE: it would not write a _multihash_ to `digest`, just the digest part.

Pros:

1. Easier to deploy code that's generic over hash functions without having to upgrade it later.
2. Smaller API surface.
3. Multihash native.

Cons:

1. No static "not supported error". But we're going to run into the same problem with IPLD codecs. IMO, we should have a static "requires" section in the WASM module to export dependencies like this.

**Comment by raulk** [comment]
This is happening in M2, not M1.
