### ISSUE TITLE
Prefer ActorID where possible

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#289]
Currently, we have quite a few places in the code where we:

1. Resolve an actor address into an actor ID.
2. Turn it back into an `Address`.

Ideally, we'd:

1. Store ActorIDs in state (smaller).
2. Use actor IDs in all syscalls except `resolve_address`:
    1. Easier to reason about gas usage.
    2. More efficient when the address has already been resolved.

However, this is a significant refactor and likely isn't worth it for now.

**Comment by anorth** [comment]
Replaced by https://github.com/filecoin-project/builtin-actors/issues/56.

We can't do this without a state migration.

**Comment by anorth** [comment]
Re-open if you want to change the syscall APIs
