### ISSUE TITLE
Add a syscall to obtain the originator of a call

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#300]
The `msg_caller` syscall returns the immediate caller, i.e. the actor that called the current actor. This is all that built-in actors have needed up until now.

However, it's useful for expose the originator of the call (i.e. the account actor whose transaction initiated the call stack) for many use cases, e.g. escrow, loans, DeFi-like cases, staking, pledging, etc.

As a sidenote: Ethereum has two distinct opcodes for this: [`CALLER`](https://www.ethervm.io/#33) and [`ORIGIN`](https://www.ethervm.io/#32), so at minimum we will need this capability for EVM compatibility.

**Comment by Stebalien** [comment]
NOTE: We'll likely need a case where the origin is "system".

**Comment by dtynn** [comment]
hi~
is [this](https://github.com/dtynn/ref-fvm/commit/00fe1e0673b7c8f415a6ee726564cfe7ae7cee56) ok for the issue?

btw, is a `ActorID(0)` enough for the origin "system", or we should define it separately like
```
pub enum Originator {
    System,
    Actor(ActorID),
}
```

**Comment by raulk** [comment]
I think this is safer and more efficient than an exporting a static constant for the system address, and assuming than the user will perform a comparison.

**Comment by dtynn** [comment]
then there would be a 
```
pub strcut Originator {
    pub is_system: bool,
    pub actor_id: u64,
}
```

or something like that in the `fvm_shared::sys` ?
