### ISSUE TITLE
conformance tests aren't being run by github actions.

### ISSUE THREAD

**Issue by lemmih** [filecoin-project/ref-fvm#310]
It looks like conformance tests were meant to run on every push but this isn't happening due to a setup oversight.

**Comment by Stebalien** [comment]
They're running: https://github.com/filecoin-project/ref-fvm/runs/5070754008?check_suite_focus=true

**Comment by Stebalien** [comment]
Or maybe not? They're building and it _says_ they're running, but they should be taking longer than that...
