### ISSUE TITLE
Figure out how to handle system "policy"

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#313]
Lotus has a concept of "policy" where we can specify:

1. Minimum verified deal size.
2. Pre-commit delay.
3. Allowed proof types.

Etc...

We use these for testing, dev nets, etc.

Unfortunately, this is all done through global variables. In the rust actors, this is done through compile-time flags.

In the new world, we have a few options:

1. Compile-time flags. We can compile different versions of the actors with different "profiles". This limits us to a fixed set of profiles but we don't _usually_ want to be able to tweak random parameters.
2. Syscalls. We can configure these features at runtime via syscalls.

Rather than increase the syscall API surface, I plan on implementing option 1.

**Comment by Stebalien** [comment]
An alternative proposed by raul is to have some form of debugging syscall for passing "environment" variables to actors. We could either:

1. Always make it available but have it return nothing on mainnet.
2. Make "testing" actors and "mainnet" actors, and only call it from testing actors.

Regardless, I think we still likely want different actors for different profiles, but it would still be useful to have _some_ way to pass arbitrary information in and out of actors.

**Comment by jennijuju** [comment]
this is for interopnet things will be done in the lotus side - lotus will load the rust actor and set the policies
