### ISSUE TITLE
remove monkey-patched crates before releasing

### ISSUE THREAD

**Issue by q9f** [filecoin-project/ref-fvm#324]
- `cs_serde_cbor`
- `cs_serde_bytes`
- ~~`ChainSafe/libp2p-bitswap`~~

ref https://github.com/ChainSafe/forest/issues/1413 and ~~https://github.com/ChainSafe/forest/issues/1421~~

**Comment by jennijuju** [comment]
moving to https://github.com/filecoin-project/ref-fvm/issues/359
