### ISSUE TITLE
Optimize the CGO Blockstore's flush

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#331]
Currently, the CGO-FFI blockstore implements `put_many` by putting each block one-by-one. This means calling into go many times, which is _really_ slow.

**Comment by raulk** [comment]
This was implemented already. @Stebalien can you add a commit hash from the https://github.com/filecoin-project/filecoin-ffi/pull/230 branch for traceability purposes?

**Comment by Stebalien** [comment]
https://github.com/filecoin-project/filecoin-ffi/pull/238
