### ISSUE TITLE
Verify Consensus Fault: halt immediately when out of gas

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#340]
It's currently agnostic to the actual gas remaining, and so could use more gas than actually available before returning. This is okay from a consensus perspective (the message fails in the same way), but it's relatively easy to pass the gas remaining to the node implementation (Lotus, eg), which can then fail at the right time.

**Comment by raulk** [comment]
@arajasek can you confirm that this was fixed with the gas remaining handoff interface? i.e. FVM passes gas remaining to the node in an extern param, and the node returns remaining gas along with the result of the operation? If remaining gas is 0 and the operation failed, we know we ran out of gas?

**Comment by raulk** [comment]
This is not implemented yet. As a result, execution will not halt soon enough.
