### ISSUE TITLE
Pick the per-instance and global memory limits

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#341]
Pick the correct per-instance and global memory limit.

**Comment by raulk** [comment]
For M1 (nv16), we are going with unlimited max pages given that the system can only run trusted logic via builtin system actors. It's not clear with initial pages should be to avoid excessive memory expansion operations.

@Stebalien will your benchmarks yield a good value for initial pages?

For M2, there's a proposal here: https://github.com/filecoin-project/FIPs/pull/317.

**Comment by raulk** [comment]
Need to resurrect this issue for M2.1 (FEVM). In discussions over time we have settled on not charging for memory allocated, but rather for memory expansions. Finding the gas value/formula to charge per expansion will be subject of upcoming work, but for now we should at least set a max pages to a reasonable value (in the past we've discussed 64MiB, 256MiB, or 512MiB, IIRC).

**Comment by Stebalien** [comment]
We're sticking with 2GiB for now. Pending FIP.
