### ISSUE TITLE
Discuss: How do we add more runtimes (adapters) to FVM

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#346]
Based on our talk in Iceland hack week, we determined that we would need to talk about:
- Paths for adding new runtimes to FVM?
- What are the runtimes we want to add in the first place?

We will take it a lower priority for now, but it's totally something we should address as we progress with the FVM development stages.

**Comment by raulk** [comment]
Runtimes are compiled to Wasm and integrated with the Filecoin protocol through hooks, callbacks, etc. and other features provided by the runtime library. For now, we are targeting the EVM, but we're laying solid foundatons for cross-cutting concerns like call translation, addressing, etc. so we can eventually host more runtimes if needed. It's unclear if that will actually happen, it depends on where and how the market moves. There are some runtimes there that interest us, but they have little for various reasons, so we might end up pulling in some of their most compelling features into the native runtime, who knows.
