### ISSUE TITLE
Discuss and Resolve: Role of the Cron in FVM development

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#347]
One of the relevant topics we mentioned in FVM Iceland hack week is that we need to address:

- Cron and how do we use it in FVM, taking into account the Crytpoecon perspective.

We should take into account that this should be addressed after M2
Also,  we should turn it into a FIP at some point.

**Comment by raulk** [comment]
Closing this as it's underspecified and not something we will engage in in the near term.
