### ISSUE TITLE
Discuss: How we can introduce  Lower parts of VM stack (using Consensus/IPFSVM)

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#348]
As a result of our discussion in Iceland, we should start thinking about: Lower parts of VM stack (using Consensus/IPFSVM)

- This is something we should do between M1 and M2 milestones
- We should find a common layer that we can use for IPLD, WASM… they will need to run on the same execution stack
- We need to create a spec that serves (after m1) as the map that people can use to build different stacks for this side of the implementation

**Comment by raulk** [comment]
This won't happen for M1 and M2, it's not a priority for the FVM. The path forward is to extract a foundational abstraction that can serve multiple execution environments (e.g. compute over data, provable compute, IPLD traversals and codecs, etc.), and rebuild the ref-fvm on top of it.

**Comment by raulk** [comment]
This conversation has forked into the IPVM project (Interplanetary VM). There's a cool talk by @expede here: https://noti.st/expede/oq0ULd. We will stop tracking this effort in ref-fvm.
