### ISSUE TITLE
Switch to new CBOR/IPLD/CID libraries.

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#359]
See https://github.com/filecoin-project/ref-fvm/tree/better-cbor

- Switch to the latest CID library that works with serde without the thread-local hack.
- Switch to @vmx's dag-cbor library (a fork of serde's CBOR library).
- Switch to the latest libipld version for link enumeration, removing our custom code.

**Comment by jennijuju** [comment]
This can be tested by resycing the calibration (so not necessary needed for butterfly and early half of the calibration net testing)

**Comment by raulk** [comment]
Fixed by:
- https://github.com/filecoin-project/builtin-actors/pull/65
- https://github.com/filecoin-project/ref-fvm/pull/366

**Comment by raulk** [comment]
@Stebalien Looks like this is fixed -- can you confirm? Please reopen if there are remaining items, and specify which.

**Comment by Stebalien** [comment]
It is _mostly_ fixed. I've filed https://github.com/filecoin-project/ref-fvm/issues/378 for the followup.
