### ISSUE TITLE
Determine/Implement Runtime WASM Limits 

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#361]
Things like:

- Max memory, page limits, etc. - done
- Max stack depth, locals limits. - done
- Globals limits. - https://github.com/filecoin-project/ref-fvm/issues/1038
- Export/import table limits. - https://github.com/filecoin-project/ref-fvm/issues/1038
- Module validation. - https://github.com/filecoin-project/ref-fvm/issues/1038

**Comment by maciejwitowski** [comment]
@aakoshh Assigning you since this is about the system limits.

**Comment by aakoshh** [comment]
Max memory and stack depth are in https://github.com/filecoin-project/ref-fvm/pull/1036
Global limits are in https://github.com/filecoin-project/ref-fvm/pull/1028

I didn't set any table limits at this point.

**Comment by Stebalien** [comment]
Mostly done, but I've filed two followups:

- https://github.com/filecoin-project/ref-fvm/issues/1075
- https://github.com/filecoin-project/ref-fvm/issues/1074
