### ISSUE TITLE
speed of progress

### ISSUE THREAD

**Issue by CodingJzy** [filecoin-project/ref-fvm#367]
Hi, why hasn't there been any news for so long? I remember it was divided into four stages. Didn't I say that V0 stage was completed in the first quarter?

**Comment by raulk** [comment]
@CodingJzy this is an issue tracker for development issues. This is a code repo, not a blog or a comms site. Please refer to the #fvm Slack channel for updates. In short, the non-programmable FVM will be going live in May with nv16 (codenamed Skyr).

Kindly refrain from opening issues like this in the future; they just create noise for the developers actually working on the FVM.
