### ISSUE TITLE
Optimization: Remove bigint

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#372]

**Comment by raulk** [comment]
@Stebalien please explain the optimization thesis here.

**Comment by Stebalien** [comment]
The thesis is: maybe we don't need the bigint crate and can get away with u128 in many cases.

Unfortunately, this won't help with the miner or market actors (which are the _biggest_ actors).

**Comment by Kubuxu** [comment]
It won't work for places where bigint math is used to arrive at approximations. Like `log` or `exp` within actors, maybe we could make better approximations for u128.

Today most of the math is done in Q.128, meaning 128 fractional bits.

**Comment by Stebalien** [comment]
Yeah, this is probably not worth the effort.
