### ISSUE TITLE
Optimization: remove hashing work from inside actors

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#374]
By generalizing the hash function https://github.com/filecoin-project/ref-fvm/issues/270.
IIRC, HAMTs perform hashing inside Wasm.

**Comment by Stebalien** [comment]
See https://github.com/filecoin-project/ref-fvm/issues/270

**Comment by raulk** [comment]
See #636.

**Comment by Stebalien** [comment]
We also need to remove https://github.com/filecoin-project/builtin-actors/blob/ac3d3e8042ebe1c35e6249798b51f5aafdcd5a74/runtime/src/runtime/fvm.rs#L488.

**Comment by raulk** [comment]
@Stebalien that line is only enabled with fake proofs. I think we’re good.

**Comment by Stebalien** [comment]
Ah.... ok, back to the drawing board.

**Comment by Stebalien** [comment]
Fixed.
