### ISSUE TITLE
Define SignedMessage struct

### ISSUE THREAD

**Issue by rllola** [filecoin-project/ref-fvm#445]
I am using `SignedMessage` struct from the chainsafe library. Is there any plan to add it to the lib ? It would help with migration without breaking stuff.

See https://github.com/ChainSafe/forest/blob/main/vm/message/src/signed_message.rs#L13

**Comment by Stebalien** [comment]
(no strong reason not to include it, we'd just rather not include anything we _don't_ need (especially in shared) unless it makes everyone's lives significantly easier)

**Comment by rllola** [comment]
I am actually trying to define it locally but I have encounter an other issue for which I opened a PR (https://github.com/filecoin-project/ref-fvm/pull/446).

I don't have strong reason to have it included beside helping migrating from chainsafe lib to this one. I believe Forest will need this too so instead of everyone having its own implementation having one in this standard lib would avoid issues I guess.

**Comment by raulk** [comment]
A few months later, we can confirm that this struct is not relevant or missed in ref-fvm; it's a client-specific type. An idea here would be for Forest to spin off its common types to an independent crate.
