### ISSUE TITLE
What happens to Wasmtime errors?

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#458]
I'm having a hard time tracing through (a) what the possible Wasmtime errors are, and (b) what happens to those errors (are they fatal and so chain-halting)?

I think we might wanna go over the possible cases and (if they aren't already), lower the severity of such Traps to not be fatal.

**Comment by dignifiedquire** [comment]
We are currently looking into removing downcasting, so I don't think we want to add more cases where we need to do so.

**Comment by arajasek** [comment]
Ack -- I'm gonna rephrase this issue slightly to describe what my concern is.

**Comment by arajasek** [comment]
Looking at it some more, looks like all Wasm Errors get turned into `SysErrActorPanic` exits

**Comment by raulk** [comment]
This is correctly handled as proven by integration tests.
