### ISSUE TITLE
optimizable syscalls

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#506]
## Context

Using the execution tracing framework introduced in #405, we have obtained detailed traces of Wasm execution on nv15. Those traces indicate there's significant repetitiveness in certain syscall paths. Concretely:

- ipld::open => ipld::read (sequence used to read a block from the store)
- ipld::stat => ipld::read (sequence used to read the parameters block)
- ipld::create => ipld::cid (sequence used to create a block and immediately obtain its CID)
- self::root => ipld::open (sequence used to read our state)
- send::send => ipld::stat (sequence used to read a return value)
- paths involving message::* syscalls
- paths involving network::* syscalls

We propose ways to optimize these paths to reduce context switching and potential associated gas costs.

## Optimization 1: Static contextual data

We currently have dedicated syscalls to obtain every one of this fields. Most actors will want to query these fields, so grouping them behind a single syscall, or injecting them into an exported, statically-allocated global, would make this data available without the multiple-syscall overhead.

- caller actor id (u64)
- receiver actor id (u64)
- method number (u64)
- value received (u64, u64)
- current epoch (i64; why isn't this a u64?)
- network version (u32)

Optionally (these attributes are hardly ever used by actors directly and in most cases would go unused):

- base fee (u64, u64)
- circulating supply (u64, u64)

## Optimization 2: optimistically passing buffers to ipld::read

Instead of performing an ipld::stat to first obtain the length of the block to allocate a buffer actor-side, we could allocate an arbitrarily sized buffer. If we guessed the size correctly, we're good. If we guessed it incorrectly, the FVM would return the _real_ size so we can expand the buffer before calling ipld::read again.

In the optimistic outcome, we perform 1 syscall. In the pessimistic outcome, we perform 2 syscalls (just like today) and an extra memory operation.

This is probably worth the tradeoff in the case of message parameters.

## Optimization 3: ipld::open_read

Similar to optimization 2, this new syscall would open a block and perform the read into an optimistically sized buffer. If we guessed the size correctly, we're good. If not, we would get the block handle back with its correct size, so we can allocate an appropriate buffer and call ipld::read.

## Optimization 4: pre-opening the state root

Assuming that most actors want to access their state, the FVM could pre-open their state root block and place it inside a static block handle, which is then set on the static context data from optimization 1.

Alternatively, we could just cache the actor state root CID in static data, and update it on `set_root` calls. This concrete solution would eliminate the `self::root => ipld::open` hot path, but it would not prevent the `ipld::open` for the state object.

---

Thanks to @Kubuxu for co-creating this analysis.

**Comment by Kubuxu** [comment]
Do we want to move on Optimizations 2-4 before M1?

**Comment by Kubuxu** [comment]
Call works like `Call&Open`, return `(id, codec, len)`.

**Comment by Kubuxu** [comment]
> Do we want to move on Optimizations 2-4 before M1?

No
