### ISSUE TITLE
R2: Exit code mismatches

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#54]

**Comment by jennijuju** [comment]
we dont care about exit code  mismatches in M1.

**Comment by raulk** [comment]
This was a Go-Rust interop issue. Because all implementations are now converging to the same actors codebase, this concern no longer exists.

**Comment by raulk** [comment]
There are some cases where the Go errors were more correct than the Rust ones. These won't lead to consensus faults, but semantic correctness is a desired property.

**Comment by raulk** [comment]
All implementations have converged to a single, canonical codebase for actors. That means that no mismatch is possible any longer. We have also cleaned up the exit code situation, and now it's illegal for actors to throw system exit codes.
