### ISSUE TITLE
R3: Inconsistent gas use across implementations

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#55]

**Comment by jennijuju** [comment]
@raulk  - whats need to be done here?

**Comment by raulk** [comment]
No longer applies since:
1. Starting with nv16, all implementations now use the canonicalized built-in actors, and therefore the logic is identical across clients.
2. No operations of this kind are performed in fvm-land (which may vary per implementation going forward) or client-land (obviously different per implementation).
