### ISSUE TITLE
Determine stack size limit approach

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#552]
We need to examine what happens as the recursive stack grows. Today, the only case of this is through multisigs, and we have a stack limit of 4096 (+/- 1). We need to check:

- whether that works (can write a test, or do so manually, or both)
- whether we wanna lower that limit
- whether any config params need to be changed to accommodate.

**Comment by arajasek** [comment]
P0, per @magik6k's guidance.

**Comment by raulk** [comment]
Solution discussed offline:

1. Limiting call depth to 1024.
2. Limit Wasm stack to some good value based on observation (instrumenting the FVM and recording the maximum stack size — can we do that?)
3. Spawning the Machine on a dedicated cached thread with a higher stack limit, calculated from the above + Rust-side stack overhead

Note that Ethereum has a 1024 call depth and max 1024 256-bit stack elements. We should set a policy that allows us to cover that.
