### ISSUE TITLE
Unsupported CPUs

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#600]
- Intel(R) Xeon(R) Gold 6226R CPU
- Common KVM processor

Flags:

- fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm art rep_good nopl extd_apicid pni cx16 x2apic hypervisor cmp_legacy retpoline_amd vmmcall
bogomips
- fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Unfortunately, these CPUs are failing with:

> compilation settings are not compatible with the native host

**Comment by Stebalien** [comment]
Hopefully https://github.com/filecoin-project/ref-fvm/issues/600 will help us debug this.

**Comment by Stebalien** [comment]
Looks like this might be a build issue. We're building in CI, but may need to specify which CPU features we want.

**Comment by Stebalien** [comment]
Ok, this isn't a build issue. This was an issue with wasmtime incorrectly detecting features at runtime: https://github.com/bytecodealliance/wasmtime/pull/4231. It will be fixed in the next wasmtime release, but we may need to patch it.

**Comment by mriise** [comment]
@Stebalien is this fixed by https://github.com/filecoin-project/ref-fvm/pull/963 ?
