### ISSUE TITLE
"life before invoke" in wasm code

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#607]
Currently, code can run before `invoke`, but it'll run out of gas immediately and trap (leading to a fatal error).

We need to either:

1. Properly account for this kind of code.
2. Forbid it.

Ideally, we'd just forbid it. It looks like we can run `wasm-ctor-eval` (from binaryen)?

**Comment by raulk** [comment]
@Stebalien Is this talking specifically about module start functions? What other bytecode can exist _before_ invoke in our case?

**Comment by Stebalien** [comment]
1. The start function.
2. Table initialization functions. See the `expr`s that appear in https://webassembly.github.io/spec/core/syntax/modules.html#syntax-elem.

**Comment by Stebalien** [comment]
I'm centralizing all wasm validation in https://github.com/filecoin-project/ref-fvm/issues/1038.
