### ISSUE TITLE
Perform SHA256 hashes natively via a syscall

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#636]
HAMTs currently perform SHA256 hashing inside the actors (for hashing HAMT keys). We should be doing this via a syscall.

**Comment by mriise** [comment]
`hash(data: &[u8], mh: Code)` ?

**Comment by Stebalien** [comment]
Yep. We have the syscall defined here: https://github.com/filecoin-project/ref-fvm/blob/923a6846c203ceaed06dd683ccc4ed37dd738c68/fvm/src/syscalls/crypto.rs#L48

However, we'll have to change the HAMT constructor to take a hash function so that the HAMT will work both _inside_ and _outside_ of the FVM.

**Comment by Stebalien** [comment]
Fixed
