### ISSUE TITLE
v10 conformance tests

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#638]
We need to add-back conformance tests.

1. Extract conformance tests for v10 (first from calibrationnet, then from mainnet).
2. Make the conformance tests download the bundle from GitHub.

Unfortunately, we can't really do this till we have a stable set of actors as changes to the actors will affect gas usage, breaking the conformance tests.

Although, I guess a half-way step would be to run conformance tests ignoring gas usage.

**Comment by maciejwitowski** [comment]
@Stebalien Do we need it for M2.1?

**Comment by Stebalien** [comment]
Yes. Specifically, we need v10 conformance tests, but fixing this issue will basically get us there.
