### ISSUE TITLE
catch panics anywhere that assumes that the passed-in buffer is exactly 32 bytes in length

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#651]
- [verify_post](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L582)
- [verify_aggregate_seals](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L688-L689)
- [verify_seal](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L997-L998)

**Comment by Stebalien** [comment]
These are done.
