### ISSUE TITLE
support module linking in fvm

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/ref-fvm#665]
at present, in the  tinygo development, we often encounter the problem of some system-level calls in the generated results (this situation is widespread) like fd_write, args_get_size, etc, the current practice is to find where to refere these functions(like os.XX), and Delete these corresponding codes to solve. This requires replacing many libraries and not easy to find sys-ref-code maybe a deep library, .  i am ensure whether this kind of issue exists in the development process of other SDKs.
My idea  deploy pure library code to ipld. Then link  these libraries in wasm.  so we can write a shim library to resolve these issues.

for example

1. Install wasm A get codecidA
2. in wasm B ,  import "codecidA", "methodX".

and in fvm, when run wasmB.  got import list and piece cid import, get from cborstore then instance then link to module B.

also have issue for import name.  i could hack wasm to modify wasi_snapshot_preview1 to a code cid. not a best idea.

@raulk  any ideas and suggestions

**Comment by raulk** [comment]
I'm sorry, but I don't understand what you mean here. Are you saying that Wasm compilation of TinyGo leads to requiring imports of POSIX functions? That's not something we will ever resolve here -- it sounds like the language (Go, TinyGo) is not producing usable Wasm bytecode, honestly.

**Comment by dgryski** [comment]
The tinygo `wasi` target expects the wasm vm to support `wasi_snapshot_preview1`.

**Comment by hunjixin** [comment]
Explanation of why posix was imported

in the os package, there is such initialization code, which will cause import of posix as long as I import this library.
```
// Args hold the command-line arguments, starting with the program name.
var Args []string

func init() {
	Args = runtime_args()
}
```

example:
```
package main

import (
	_ "fmt"
)

func main() {} //nolint

//go:export invoke
func Invoke(_ uint32) uint32 { //nolint
	return 0
}
```

```wat
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $runtime.args_sizes_get (;0;) (type 3)))
  (import "wasi_snapshot_preview1" "args_get" (func $runtime.args_get (;1;) (type 3)))
  (import "wasi_snapshot_preview1" "clock_time_get" (func $runtime.clock_time_get (;2;) (type 6)))
```

i have modified many package which import os package, just remove the code about os, but the standard package (fmt) is  different with them.  it cannot be solved by replacing in gomod, and almost all the packages use fmt package. 

the solution i thought of：
1.   (currently planned)the module(not std) uses replace, the standard package uses the patch. user download the patch to modify the standard library in his local environment. this pactch would change go/tinygo std package
2. support posix mock or enable to link a posix mock when running code in fvm    
3. add fvm/wasm target in tinygo, regard fvm as a OS

@dgryski @raulk

**Comment by raulk** [comment]
@hunjixin Oh, now I see. Indeed, there are `init()` functions in popular packages of the Go std library that end up invoking POSIX functions. The Wasm/WASI compiler translates them to WASI imports. 

**However, the FVM is _not_ a WASI environment and we never expect it to become one.**

The FVM is an embedded, sandboxed execution environment, where the only supported external interactions are via syscalls. FVM actors cannot access POSIX functions -- allowing so would break the blockchain abstraction model (esp. because many of those functions have environmental side effects).

The first two functions are used to process command-line arguments:
* https://docs.rs/wasi/0.9.0+wasi-snapshot-preview1/wasi/fn.args_sizes_get.html
* https://docs.rs/wasi/0.9.0+wasi-snapshot-preview1/wasi/fn.args_get.html

Are you building with a WASI or a Wasm target? i.e. are you calling `tinygo -target=wasm` or `-target=wasi`?

**Comment by hunjixin** [comment]
@raulk  yea, i use wasi target,  wasm target in fact was for running on js.  tinygo generate wasm base on llvm, and llvm generate wasm base on wasi-libc, i can also add a new fvm target and add some mock env  @dgryski  did you think it okay to accept a fvm target?.

**Comment by Stebalien** [comment]
Looks like there's a similar discussion in https://github.com/tinygo-org/tinygo/issues/1383.

**Comment by hunjixin** [comment]
no pure wasm target, the wasm target is real a js wasm.  this behavior maybe flow golang,this issue have been discussion for years,  not a easy work to change this behavior.

on the other hand, it have special properties of go， in this case  init func must be run for args when import or indirect import os package.  It is indeed used in the code,so it is not surprising that import for posix in the wasm result.  if the args  is lazy loaded, the result should not have posix import.  

interesting with  how the rust compile deal with this code
```rs
println!("wasm print")
```
 just ignore the println?

**Comment by mriise** [comment]
> just ignore the println?

with standalone wasm32 rust doesn't import `std` at all, so `println!` can't be imported

**Comment by Stebalien** [comment]
The wasm32-unknown-unknown target (the one we use) discards out stdout and stderr.

**Comment by hunjixin** [comment]
go's wasm32 is quite strange,  its really a  wasm32-unknown-js, maybe i can try to add a new target for wasm32-unkonw-unknown. i would dig the llvm and tinygo behavior.
