### ISSUE TITLE
Gas Tracing

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#671]
Currently, the FVM supports

- Execution tracing. Specifically, tracing of a message's call graph.
- Gas logging. I.e., it can (if trace logging is enabled) log all gas charges.

However, unlike the Lotus VM, the _execution_ trace does not include individual gas charges. This makes debugging gas charges significantly more annoying.

*Proposal*: Extend the execution trace to include:

- Gas numbers (gas consumed up to that point should be sufficient).
- Syscalls.

We _could_ include all gas charges, but that's probably overkill.

**Comment by karim-agha** [comment]
can lotus have cold/warm storage? It helps a lot with parallelization.

**Comment by maciejwitowski** [comment]
@Stebalien Do we need this for M2.1?

**Comment by Stebalien** [comment]
Fixed in #709.
