### ISSUE TITLE
EVM runtime: Consider uint alternative 

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#678]
`uint` crate makes it's bigints from u64, which won't be as efficient as using u32 in wasm32 (collections of u32 _may_ also be faster on x86 due to cache line sizes, but is irrelevant here).

https://github.com/RustCrypto/crypto-bigint provides bigints with pointer-sized words and constant time operations as a bonus

**Comment by karim-agha** [comment]
bad idea.

**Comment by Stebalien** [comment]
wasm32 isn't like x86. It has native support for 64 bit integers and will lower those operations to native 64bit instructions.
