### ISSUE TITLE
FVM M2.1 incremental delivery plan

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#692]
## Context

The FVM team has decided to deliver FVM M2.1 (FEVM) in an incremental fashion. This allows the Filecoin community:

- continuously experiment with FEVM, as it's being built
- test existing Ethereum tooling (e.g. MetaMask, Hardhat, Remix, Foundry, Truffle, etc.)
- adapt existing Filecoin tooling by integrating it with FEVM (e.g. wallets, explorers, etc.)
- test the compatibility of existing Ethereum audited, battle-tested contracts by deploying them to FEVM
- identify and raise bugs as they're being encountered

## Plan

> This is a draft plan -- it is subject to change and refinement as we move along.

![image](https://user-images.githubusercontent.com/1101242/183415725-54deb19f-82c8-4c13-acf8-fcbc2b077bc9.png)

FEVM releases are named after minerals under the different degrees of the [Mohs mineral hardness scale](https://en.wikipedia.org/wiki/Mohs_scale_of_mineral_hardness). We find this framework is appropriate because it establishes progression, provides plenty of attractive codenames to adopt, and aligns with the mental model of maturity/hardness increasing over time as the feature set becomes denser.

- [x] #691
- [x] #801
- [x] #830
- [x] #863
- [x] #903 
- [x] https://github.com/filecoin-project/ref-fvm/issues/939
- [x] https://github.com/filecoin-project/ref-fvm/issues/940
- [x] https://github.com/filecoin-project/ref-fvm/issues/1052
- [x] https://github.com/filecoin-project/ref-fvm/issues/1371
- [x] https://github.com/filecoin-project/ref-fvm/issues/1372

We are not committing to having 10 releases exactly; we may add intermediate releases, merge some, or skip some entirely, as work progressing.

## Upcoming testnets

We are also working with testnet infrastructure providers to set up a dedicated testnet so that early builders, and other curious beings, can get their hands dirty as features are delivered.

This testnet would be the spiritual counterpart to [Wallaby](https://github.com/filecoin-project/testnet-wallaby) (Wasm testnet), but for FEVM. We expect it more unstable and bleeding edge, as FEVM is the active focus of development. We expect frequent resets, potentially even weekly.

**Comment by ancjf** [comment]
This is great for ecosystems on Ethereum migrating to Filecoin.

**Comment by ancjf** [comment]
Thanks, this allows me to test the program as quickly as possible

**Comment by stebansaa** [comment]
at what stage is there full RPC compatibility ?

**Comment by raulk** [comment]
@stebansaa Yes, it's in early stages, so expect dragons! 🐉

**Comment by raulk** [comment]
Incremental delivery has been completed, and we have initiated the mainnet handoff procedure. FVM M2.1 (FEVM) will be on mainnet on March 14th.
