### ISSUE TITLE
Remove built-in Type enum from SDK

### ISSUE THREAD

**Issue by anorth** [filecoin-project/ref-fvm#712]
The built-in actor `Type` enum needs to live in the built-in actors repo (https://github.com/filecoin-project/builtin-actors/issues/520), though a copy is necessary in the FVM too (to avoid importing it from actors).

After https://github.com/filecoin-project/builtin-actors/pull/547, the actors will have no reference to the FVM version of this enum. Remove it from the exported SDK to avoid confusion.

As part of this, change the return/parameter types of these syscall wrappers to pass through the bare i32, rather than wrapping in a `Type`.
- `fvm::actor::get_builtin_actor_type`
- `fvm::actor::get_code_cid_for_type`

Note that in the long run we'll want to get rid of this type concept and have the built-in actors rely on addresses and/or code CIDs to confirm actor identity and access. The syscalls should then be removed (and should never be exposed to non-built-in actors).

**Comment by raulk** [comment]
> Note that in the long run we'll want to get rid of this type concept and have the built-in actors rely on addresses and/or code CIDs to confirm actor identity and access.

I disagree with this:
- not all built-in actors are singletons (e.g. miner, and unfortunately for now, paych and multisig)
- code CIDs change over time and it's fairly reasonable to assume that we can't expect user actors to update their code when built-in actors code CIDs change; therefore we need some form of indirection and that's what the actor type resolves

**Comment by Stebalien** [comment]
Implemented.
