### ISSUE TITLE
Technical design: Logs and events

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#728]
## Context

The Ethereum blockchain has the concept of logs, which are events emitted from smart contracts during execution. Logs contain arbitrary data, and are annotated with zero to four 32-byte topics depending on the opcode used (LOG0..LOG4). The fields from logs (topics, data, emitting address) are added to a 2048-bit bloom filter which is then incorporated to the block header.

The bloom filter is important because it is used by:
1. light clients and wallets to quickly evaluate if a block is of interest depending on what they are looking for.
2. full nodes to service log-related JSON-RPC queries (`eth_getLogs`, `eth_getFilterLogs`, `eth_getFilterChanges`); either in a streaming or polling fashion. Filter support implies tracking state at the node level.

AFAIK logs in Ethereum are not part of the world state, i.e. they are not stored in the state tree (we need to double check this). They are just emitted during execution and consensus is arrived to through the bloom filter, gas used, and other outputs.

## Requirements

The EVM compatiblity in Filecoin will need to support Ethereum logs at the protocol level and the JSON-RPC level.
We should avoid overfitting to Ethereum's needs -- this feature should be available to native actors too and should be generally usable and accessible.

## Possible design direction

At this stage, we do not plan on introducing modifications to the chain data structures, so populating an aggregation of logs in block headers is a no-go. That leaves us with three options:

- Support at the node level, by offering a syscall that traverses an extern, and records logs somewhere in node land.
    - Con: this does not cause a result in commitment of emitted logs (does factor into consensus indirectly through gas fees).
- Support at the FVM level, by offering a syscall that buffers logs and appends to a bloom filter. When finalizing the machine, we'd return the bloom filter and logs to the node. The node can store bloom filters and do whatever with the logs themselves (strema them, cache/store them, or rely on re-execution).
    - Con: this also doesn't result in a chain commitment. However, we could track the bloom filter's content as a field in the system actor, which would be updated implicitly by the FVM on machine finalization.
- Support at the system actor / built-in actor level through a singleton actor. Logs are emitted by calling a LogsActor. The logs actor stores a height => bloom filter mapping and exposes a `GetLogsBloom(height)` to return it. We'd need to add a cron job to prune LogActor entries and limit them to the current finality. Getting the logs would require re-execution and introspection of call parameters through execution traces.

## Light client operation

In Ethereum, light clients monitor block headers containing event bloom filters to determine whether they want to act on a block.
Since Filecoin does not include the logs blooms in a chain structure, Filecoin light clients would operate by receiving the current bloom in the system actor accompanied by a merkle inclusion proof.

**Comment by Stebalien** [comment]
Concrete proposal:

1. Introduce a new `log` that takes a set of log topics and a block ID.
2. Do _NOT_ index anything (yet). Indexing will be handled in a followup FIP.

```rust
fn log(count: u32, topics: *const u8, value: BlockId)
```

Where:

- `count` is the number of topics (1-4 for now).
- `topics` is a byte slice with the length `32*topics`. Each topic is an arbitrary 32bit key `topics[i*32..(i+1)*32]`.
- `value` is a block ID of a value.

Define an event object of the type:

```rust
struct Event {
    actor: ActorID,
    topics: Vec<u8>,
    value: cid.Cid,
}
```

When an event is logged:

1. Make a CID of the `value` block where:
    1. The CID is "inline" if the length of the value is <= 32 bytes.
    3. Otherwise, we hash with blake2b.
2. Record an event object with the caller's ActorID, the specified topics, and the value CID.

When creating a message receipt, pack all events into an AMT in-order and include the AMT root in the receipt.

**Decisions**

- [ ] Are we OK with fixed 32byte topics? That comes from the EVM, but it's a useful constraint.
- [ ] We're storing the value in either an inline CID or an external block because it _might_ be large (and we want the AMT to have predictably sized nodes. Is that OK?
- [ ] Are we OK storing the topics in a single vector (concatenated)? It simplifies things, but users may not like it?

**Comment by raulk** [comment]
_Notes from sync design meeting + concrete proposals_

## Descoping indices

We are moving the indexes out of the scope of this solution. Right now we want to focus on the simplest, extensible solution that: (a) is not overengineered for what we need now, (b) does not back us into a design corner now without sufficient information, (c) is easily extensible in the future.

## Storing raw events

For now, we will be storing the raw events only, allowing clients to experiment and generate indexes client side entirely. The schema of an event is as follows:

```rust
struct Event {
   emitter: ActorID,
   topic: List<String>,
   payload: Cid, // for events emitted from EVM smart contracts, this payload would be CBOR bytes, but it could be anything else 
}
```

During execution, we track two lists:
- One at the Call Manager, an AMT populated by the events emitted during the call stack.
- One at the Machine, an accumulation of the above AMTs into a summary AMT.

When finishing a message, the Call Manager appends its AMT to the Machine AMT, filling in a null value if the message emitted no events. The order in which events appear on the Machine AMT thus matches the order of message application. On a well behaved Filecoin client, this will match the canonical message execution order.

## Commitment on chain

When the Machine is finalized, we compute the CID of the Machine's events AMT and return it to the client for inclusion on the block. Thus, we extend the block header with an extra field:

```rust
struct BlockHeader {
    // ... All existing fields ...
    events: Cid,
}
```

## Patterns of access

While the protocol does not mandate this, clients may wish to cache events in a local database for efficient access. With the structure above, it's possible to access events for a given message or all events for a tipset.

## Ethereum JSON-RPC compatibility

At this stage, we do not track logs blooms and we definitely do not track Ethereum formatted blooms (fixed size keccak256 based hashing). The Ethereum JSON-RPC API will need to recreate the bloom filters on demand (or implementations could choose to do something different if they wish to optimise for faster bloom query).

**Comment by raulk** [comment]
Draft FIP at https://github.com/filecoin-project/FIPs/pull/483.

**Comment by raulk** [comment]
We can consider the technical design phase to have finished, culminating with the FIP draft at https://github.com/filecoin-project/FIPs/pull/483. Closing this issue.
