### ISSUE TITLE
Consider removing SysErrInsufficientFunds

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#740]
Instead, the system could just use `ErrInsufficientFunds` (the user error).

Why keep it?

1. The system doesn't _currently_ generate any non-sys exit codes.
2. This makes it easy to distinguish between "sending account has insufficient funds" and "some actor somewhere says it has insufficient funds".

Why remove it?

1. This is the only exit code duplicated in both the user and system range.
2. The fact that the send syscall returns the InsufficientFunds error code while only the top-level message can fail with the SysErrInsufficientFunds exit code is confusing.

**Comment by raulk** [comment]
I tend to lean towards keeping it; I don't see space for unification of the backing cases.

Note that we now actually have **_three_** cases of "insufficient funds", all of which make sense to me in their context. After all, Filecoin is a blockchain and a cryptoeconomy, and moving value is a pervasive action that happens at various layers.

1. System-level exit code `SYS_INSUFFICIENT_FUNDS` (6) => thrown when a message sends value beyond the available balance of the sender; or when the sender doesn't have sufficient funds to cover message inclusion cost.
2. User-level exit code `USR_INSUFFICIENT_FUNDS` (19) => a well recognised and normalized error condition that actors would want to signal explicitly vs. an assertion failed, or other occluding error.
3. Error number `InsufficientFunds` (5) => returned from the `send` syscall when the actor attempts to send a value exceeding its available balance.

@Stebalien -- feel free to close this if you're happy keeping things as they are.

**Comment by Stebalien** [comment]
Moot.
