### ISSUE TITLE
[idea] FSI: Filecoin Standard Interface

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#772]
Developers will build a lot of things on Filecoin. Since early on, we want to encourage a culture of composability and reusability. One way of achieving this is to create a corpus of "Filecoin Standard Interfaces". We expect these to be defined by the community, but frontloading a bunch of pre-existing interfaces would be useful.

These initial interfaces could be extracted from two reusable components that exist in the protocol today:

- Payment channels
- Multisig wallets

The protocol shouldn't care about the implementation, as long as they adhere to a specific interface and behaviour.

In the future, we expect FSIs for:
- data bounties
- markets
- futures
- replication workers
- etc.

**Comment by Stebalien** [comment]
There are already interfaces for NFTs and ERC20. We likely want more, but they should be discussed in https://github.com/filecoin-project/FIPs/discussions.
