### ISSUE TITLE
Static runtime data access

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#777]
Some runtime data (caller, actor ID, message params, etc.) are _static_. This means we can, in theory, access it without having to cross the VM boundary by copying it into the actor's memory before invoking the actor.

However, there's a trade-off:

1. We can use a static variable, in which case we'll get a bunch of zeros in our compiled module bloating its size. We could try to fix this with compression, but charging gas in that case gets very tricky.
2. We can use multiple static variables letting the actor choose what information it wants. But in the worst-case, this is just slower and less efficient than 1.
3. We can just make FFI calls.
4. We can expose this as one big bulk "metadata" syscall.

See https://github.com/filecoin-project/fvm-project/blob/main/03-impl-notes.md#runtime for some discussion on this topic.

**Comment by raulk** [comment]
This was addressed in https://github.com/filecoin-project/ref-fvm/pull/509. The option we went with was (4) + memoization at the SDK level.
