### ISSUE TITLE
Investigation: Use Yatima's IPLD

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#788]
Well, originally from substrate but extracted into separate crates. This implementation works _without_ the standard library so it should work _much_ better for our use-case.

Eventually I'd like all these implementations merged.

- https://github.com/yatima-inc/sp-cid
- https://github.com/yatima-inc/sp-ipld
- https://github.com/yatima-inc/yatima

**Comment by raulk** [comment]
@Stebalien does this still stand?

**Comment by Stebalien** [comment]
Ah, no. We've ported the changes we cared about.
