### ISSUE TITLE
Figure out how to deal with floating point operations

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#792]
The plan is to forbid floating point operations until making them completely deterministic is well understood and tested. Unfortunately, almost all standard libraries include some floating point operations. Ideally the optimizer would just remove any reference to floating point operations, but we can't necessarily rely on that.

Options:

1. Take a hard-line and forbid floating point operations entirely. Unfortunately, if this instruction happens to get compiled into the program in some "dead" section, the actor will get rejected on deploy.
2. Trap on floating point operation and raise a runtime error. This will provide less ahead-of-time safety, but'll make the system a lot easier to use.

**Comment by expede** [comment]
Hey 👋 Did you end up finding a solution to this? We've been exploring flipping the NaN canonicalization features on in Wasmer, and curious if there's a sharp corner that we haven't thought of for deterministic settings.

**Comment by raulk** [comment]
Yep. We enabled NaN canonicalization at the Cranelift compiler level:

https://github.com/filecoin-project/ref-fvm/blob/fe7fd717472c1704c1fd8be3a30b51f6271e963f/fvm/src/machine/engine.rs#L149
