### ISSUE TITLE
EVM runtime: remove Ethereum gas accounting entirely

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#796]
## Problem

Ethereum gas accounting is not inherently useful in FEVM. Execution is metered and halted based on Filecoin gas. The cost of EVM instructions is covered by execution gas as introduced in [FIP-0032](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0032.md).

In fact, `eth_estimateGas` will return the Filecoin gas required to execute an Ethereum message. As a result, Ethereum wallets will populate the gas limit on the message based on **Filecoin gas**. The `GasSpec` on account abstraction also deals with Filecoin gas.

There is a single place where tracking Ethereum gas is useful: to honour the contract of Ethereum CALL* opcodes, which can take the gas limit as an optional parameter, in which case they constrain the possible Ethereum gas expenditure of the callee.

## Solution A: support Ethereum gas limits in internal calls

This would require us to transmit the gas limit to the receiving actor somehow. The EVM runtime on the destination actor could then use this value to perform local execution halt, and abort with a user-level exit code (e.g. USR_ERR_INTERRUPTED) when a local out of gas happens.

As for the conduit to transmit this piece of information, we could either create a dedicated place for "call metadata" in internal calls, or we could pack the gas limit as part of the call convention. GAS and GASLIMIT opcodes would return Ethereum gas, and we'd need Filecoin specific opcodes for actors that want to handle Filecoin gas (ouch).

This solution is quite disruptive (no matter the variant we choose to implement), it imposes cognitive load on the user (there are now two parallel gas models to reason about, with different execution halt outcomes), and it's hard to unify with Ethereum wallets.

## Solution B: drop Ethereum gas tracking entirely

Remove Ethereum gas tracking entirely from the EVM interpreter. Make GAS and GASLIMIT return Filecoin gas. The gaslimit accepted by CALL is expressed in Filecoin gas. `eth_estimateGas` returns Filecoin gas.

## Proposal

We propose to move forward with Solution B. The tradeoff is that existing Ethereum smart contracts that perform gas calculations or set gas limits in CALLs will have to adapt their values to Filecoin gas, e.g. the well known 21000 gas value used to limit simple transfers would not work anymore. We believe this is an acceptable tradeoff in exchange for not introducing hyperspecialization in the system to model for the specifics of the Ethereum runtime.

**Comment by mriise** [comment]
The FVM team has decided to go with option B.

FEVM will not be doing EVM specific gas accounting, EVM gas opcodes will be using native FIL gas as its values. This _may_ cause some issues if contracts are doing weird things that depend on returned gas values, but for the most part is something we feel is a reasonable tradeoff that will cause only rare issues.
