### ISSUE TITLE
M2.1: Selenium release (r2)

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#801]
## Goal

To make the Filecoin EVM interpreter more performant and feature-complete.

## Implementation scope

This release:
- Revamps the EVM interpreter opcode dispatch mechanism for faster throughput and lower gas consumption.
- Introduces support for Ethereum precompiles
- Introduces support for other basic opcodes
    - BALANCE, SELFBALANCE
    - BLOCKHASH (for now, return randomness until we have a digest of the tipset key)
    - BLOCKNUMBER
    - COINBASE
    - EXTCODESIZE, EXTCODECOPY (introduce a method in the EVM smart actor to return the block CID of the EVM bytecode, so it can be treated as a block through IPLD syscalls)

Deferred:
- Introduces support for `SELFDESTRUCT`
- Introduces support for `REVERT` mechanics (requiring a Filecoin protocol change to allow exit codes to carry return data)

## Work burndown

https://github.com/filecoin-project/ref-fvm/milestone/8

**Comment by karim-agha** [comment]
I would abandon [selfdestruct](https://hackmd.io/@vbuterin/selfdestruct). You have no legacy to support, it's easy for you to abandon it.
