### ISSUE TITLE
Eliminate SELFDESTRUCT

### ISSUE THREAD

**Issue by karim-agha** [filecoin-project/ref-fvm#802]
Bikeshed about why selfdestructing is inferior to update.

**Comment by Stebalien** [comment]
That's a good point. We _could_ just upgrade to a tombstone. The main downside is that it wouldn't prevent funds from being sent to the target actor.

See https://github.com/filecoin-project/FIPs/discussions/436.

**Comment by karim-agha** [comment]
if you will be upfront with it in de docs, that we just don't support sefldestruct, it will make thinks easier. That opcode is useless.
