### ISSUE TITLE
EVM runtime: handle `REVERT`

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#811]
`REVERT` is equivalent to an FVM `abort` syscall. It interrupts the callee but returns control to the caller. However, `REVERT` is capable of returning a payload, which Filecoin disallows in combination with a non-zero exit code (originating in an abort). Thus, supporting this as an abort may require a protocol extension. There are alternative solutions that @Stebalien will document shortly.

**Comment by vyzo** [comment]
Possibly the simplest way to handle this is to return a struct from `InvokeContract` in the `EvmContractActor`, which includes a boolean on whether it was a revert, together with the return value.

**Comment by Stebalien** [comment]
Proposal: Replace `abort` with an `exit` syscall.

```rust
fn exit(code: u32 /* exit code */, value: u32 /* block id */, msg: *const u8, msg_len: u32 /* optional message */);
```

- If `code` is non-zero, revert.
- Always return the value where `0` identifies the "empty" value.
- The message is optional and only for tracing (it doesn't affect consensus).

**Comment by maciejwitowski** [comment]
`REVERT` implementation https://github.com/filecoin-project/builtin-actors/pull/633
As per notes: 
>REVERT doesn't propagate return data yet; this will be fixed in a subsequent pr, as it requires fvm support for aborting with data.
