### ISSUE TITLE
EVM runtime: ID address mask-based pattern-matching

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#821]
EVM actors should be able to refer to other actors through their Ethereum-equivalent addresses (in the f4 address class, design upcoming), but also through ID address (f0).

Discriminating between f4 and f0 addresses would be done through mask-based pattern matching. The Ethereum address length is 160 bits (20 bytes).

## Mask

The proposed mask is:

```
0xff || [0x00; 11] || BE-encoded u64 actor ID
```

We could simplify this to all 0xff, as @Stebalien suggested here: https://github.com/filecoin-project/builtin-actors/pull/586#discussion_r958715247.

## Implementation

- Implement an Address type that aids validation and conversion, as well as eventual f4 address handling.
- Make address-handling opcodes use that type, currently: CALLER, ADDRESS, ORIGIN. Right now they are returning the u64 ID address as-is; they'd need to return a masked address.

**Comment by Stebalien** [comment]
NOTE: we cannot use `[0x00;12] || BE-encoded u64 actor ID` because 0-255 is reserved for precompiles.

**Comment by raulk** [comment]
Was implemented in https://github.com/filecoin-project/builtin-actors/pull/586.
