### ISSUE TITLE
M2.1: Copper release (r3)

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#830]
## Goal
Enable sending funds to existing addresses and CALLing other EVM smart contracts

## Implementation scope

This release:
- Ethereum JSON-RPC sans events, possibly with temporary in-protocol Ethereum signature validation if account abstraction not ready
- [Adds support for `REVERT` opcode](https://github.com/filecoin-project/ref-fvm/issues/811)
- Cross-EVM contract calls (to enable sending funds to existing addresses), including METHODNUM opcode #805
- Implement missing opcodes
	- #689
	- #838 
- Account abstraction progress
- Extensible addressing progress

## Work burndown

https://github.com/filecoin-project/ref-fvm/milestone/9

**Comment by maciejwitowski** [comment]
Update:

- REVERT implementation https://github.com/filecoin-project/builtin-actors/pull/633
✅ with caveat
>REVERT doesn't propagate return data yet; this will be fixed in a subsequent pr, as it requires fvm support for aborting with data.

- Cross-EVM contract calls
✅  https://github.com/filecoin-project/builtin-actors/pull/633

- Implement missing opcodes
    - #689 ??

    - #838 
      - PR draft https://github.com/filecoin-project/builtin-actors/pull/632

- Extensible addressing
  - Spec opened for discussions https://github.com/filecoin-project/FIPs/discussions/459
  - Implementation starting this week
- Account Abstraction
  - 5-15% of implementation done

**Comment by raulk** [comment]
Are we ready to close this issue that we've handed it off? 🎉

**Comment by maciejwitowski** [comment]
Yes! 🚀

**Comment by raulk** [comment]
Copper has arrived!
![ezgif-3-2ba72097d3](https://user-images.githubusercontent.com/1101242/189876050-4e6ad627-9dcb-40ff-b9b8-bab2b66477f8.gif)
