### ISSUE TITLE
EVM runtime: better testing

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#831]
Our current strategy to create unit/integration tests for the EVM actor is to use prepared binary compiled versions of Solidity smart contracts. This won't scale well going forward. It's suitable for coarse grained end-to-end tests (testing entire contracts).

For unit testing I'd like us to have framework to craft EVM contracts ourselves with EVM assembly, right inside the unit test. This makes the logic of the test easy to follow and allow us to cherry-pick which opcodes we want to exercise.

Some options here are:

1. [Huff compiler](https://docs.huff.sh/get-started/compiling/#compiling-contracts-with-the-huff-compiler)
    - A low level assembly-like language that compiles to EVM; would need to check if it can be invoked through macros.
2. Inlining the Solidity code and calling the Solidity compiler from Rust to produce the EVM bytecode
    - This would require solc to be available on the build machine, would be slower, may produce code that's more bloated than it should be, may produce unstable outputs (e.g. a community member recently complained that compiling [SimpleCoin](https://github.com/filecoin-project/testnet-wallaby/issues/2) with some newer version of Solidity generated some opcodes that FEVM doesn't support yet).

**Comment by raulk** [comment]
Here's an extra option. `etk_asm` provides tooling to translate textual EVM assembly into binary EVM assembly. Looks like we could build on top of it: https://quilt.github.io/etk/

**Comment by vyzo** [comment]
I think the best approach is to utilize an assmebler -- [eas](https://github.com/quilt/etk) looks great for this.

I am going to make a contract macro, that takes a contract in eas assmbly form, assembles it, and synthesizes the initcode to install it.

**Comment by vyzo** [comment]
This is now done with the etk assembler.
