### ISSUE TITLE
EVM runtime: implement EXTCODESIZE, EXTCODEHASH, EXTCODECOPY opcodes

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#838]
These require a new public method (`GetBytecode`) on the EVM runtime actor to return the CID of the EVM bytecode of the actor.

That also means we need to change the layout of the state to save the bytecode as a separate RAW-encoded block (or is now the time to add an IPLD multicodec entry for EVM bytecode?).

These opcodes would then assert that the callee is an EVM actor, send the message, and then use `runtime.store().get()` to fetch the block and return the size, hash, or perform the copy.

There are likely more efficient ways to handle this if we fall down to IPLD syscalls, but we're staying high level due to our usage of the Runtime. I'd compromise with a less efficient approach now, as I expect these opcodes will be seldom used.

**Comment by raulk** [comment]
@Stebalien 👀 confirmation of approach would be great.

**Comment by Stebalien** [comment]
Yep, this sounds like the best way forward.

> or is now the time to add an IPLD multicodec entry for EVM bytecode?

Not really worth it (it isn't structured data).

**Comment by pl-kevin** [comment]
These methods are implemented: 
- [x] eth_blockNumber
- [x] eth_accounts
- [x] eth_getBlockTransactionCountByNumber
- [x] eth_getBlockTransactionCountByHash
- [x] eth_getBalance
- [x] net_listening
- [x] net_version

**Comment by raulk** [comment]
Implemented in https://github.com/filecoin-project/builtin-actors/pull/632.
