### ISSUE TITLE
EVM runtime: implement unit tests for precompiles

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#842]
Unit tests for https://github.com/filecoin-project/ref-fvm/issues/695, as per https://github.com/filecoin-project/ref-fvm/issues/695#issuecomment-1235742534.

**Comment by raulk** [comment]
The sha256 precompile earned a unit test here: https://github.com/filecoin-project/builtin-actors/pull/615.
But all other precompiles remain untested.

@maciejwitowski -- what do you think about closing this issue and opening one per precompile that requires a unit test, to track more granularly?

**Comment by maciejwitowski** [comment]
If we think testing all precompiles is big enough that we won't fit all in 1 week, then splitting them is a good idea.
@mriise could you help me and open 1 issue per each precompile which needs testing and add it to the Obsidian release https://github.com/filecoin-project/ref-fvm/milestone/11 ? (I wouldn't like to increase the scope of Iron now after we planned the week).

**Comment by mriise** [comment]
how extensive do we expect precompile tests to be? I dont think having an issue -per precompile, rather just a checklist.

- [x] sha256
- [ ] ec_recover
- [x] ripemd160 https://github.com/filecoin-project/builtin-actors/pull/651
- [ ] identity (this is just `Vec::from(input)`, do we even need a test for this?)
- [ ] modexp
- [x] ec_add
- [x] ec_mul
- [ ] ec_pairing
- [x] blake2f

**Comment by maciejwitowski** [comment]
@mriise thanks! Can we just move the unchecked ones to the new issue or more issues if we know these tests will take more than eg 2-3 days and may not fit all into a single release? The goal is never to have a single issue span multiple releases. Eg this one is assigned to Copper, so we can create a new one and assign it to one of the next releases.

**Comment by mriise** [comment]
This should all be finished in a few hours.

**Comment by karim-agha** [comment]
oh, corporate drone...

**Comment by maciejwitowski** [comment]
Closing this one as it will be addressed in https://github.com/filecoin-project/ref-fvm/issues/879
