### ISSUE TITLE
Handling STATICCALL

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#872]
This is part of https://github.com/filecoin-project/ref-fvm/issues/718 which targets `STATICCALL`.

**Comment by karim-agha** [comment]
Cant you just abort all `set` operations?

**Comment by karim-agha** [comment]
locally

**Comment by Stebalien** [comment]
See https://github.com/filecoin-project/FIPs/discussions/487 for a discussion/proposal on how to implement this.
