### ISSUE TITLE
Benchmark test suite

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/ref-fvm#878]
We need a program that takes a contract and an invocation, and runs it with the specified bundle to output used gas at the very least.
This should be coupled with a set of benchmark contracts, so that we can track progress as we are optimizing things like the EVM actor.

It can use the integration testing framework.

**Comment by Stebalien** [comment]
We'll want to make changes based on this, so I _think_ this will be a "lab week hack project". I've created a new milestone for that.

**Comment by Stebalien** [comment]
https://github.com/filecoin-project/fvm-bench/pull/1
