### ISSUE TITLE
EVM Storage: Test contract

### ISSUE THREAD

**Issue by aakoshh** [filecoin-project/ref-fvm#887]
Part of https://github.com/filecoin-project/ref-fvm/issues/859

Create a Solidity smart contract under `builtin-actors/actors/evm/tests` to support benchmarking the gas consumption of storage operations. 

The contract should have the following state variables:
* a top level simple variable, like a counter; this is to test accessing the same static slot
* a dynamic array; this is to test accessing contiguous slots with a random hash-based offset
* a mapping; this is to test accessing random locations where each key is hash-based

To manipulate those, the contract should have the following methods:
* increment the counter
* append a value to the array
* add key/value pair

These will be called from the test a different number of times and in various order, to measure how much data is retrieved from the block store. 

Add machinery to compile this contract into ABI and bytecode and check them into the repo.

**Comment by Stebalien** [comment]
Nit: it would be nice to benchmark a few different ones independently. I.e.:

- One with a lot of fields.
- One with a few arrays.
- One with lots of large maps.

Etc. I'm concerned that we'll overfit to a single test contract.

**Comment by aakoshh** [comment]
@Stebalien thanks for mentioning more things to test. 

I agree that testing multiple fields could be interesting, it would surely be different with or without key hashing, e.g. 10 fields with hashing are all stored in the root, but 10 fields without hashing are stored 32 levels down. A single field would not show this. We need at least 4 fields to trigger the bucket limit. 

I'm not sure what I would expect from one array vs multiple arrays since they are at different parts of the tree. Maybe the test can show that the cost doubles if we access two arrays, so they are independent. That ratio should not change before and after the update, but we can make sure to preserve it.

Similarly lots of large maps should behave the same as a single large map, but maybe it's worth showing this.
