### ISSUE TITLE
Ethereum JSON-RPC implementation in Lotus related to Ethereum logs

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#908]
- [X] eth_subscribe
- [X] eth_unsubscribe
- [X] eth_getFilterChanges
- [X] eth_getFilterLogs
- [X] eth_newBlockFilter
- [X] eth_newFilter
- [X] eth_newPendingTransactionFilter
- [X] eth_getLogs
- [X] eth_uninstallFilter

**Comment by raulk** [comment]
The one and only @iand landed this in Lotus.
