### ISSUE TITLE
Ethereum JSON-RPC: implement missing methods

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#909]
Implement methods from https://github.com/filecoin-project/ref-fvm/issues/854 which weren't included in previous releases.

## Category A: simple methods

These methods require simple mapping and do not necessitate deeper changes in Lotus.

**_Owned by @ychiaoli18_**

- [x] eth_getTransactionByBlockNumberAndIndex
- [x] eth_feeHistory

## Category B: deeper changes required in Lotus

**Section 1: require tipset hash tracking and mapping:**

**_Owned by @ychiaoli18_**

- [x] eth_getTransactionByBlockHashAndIndex

**Comment by maciejwitowski** [comment]
@ychiaoli18 do you think you will be able handle this in the next 2-3 weeks?

**Comment by raulk** [comment]
All implemented.
