### ISSUE TITLE
refactor `NetworkConfig` and `NetworkContext`

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#913]
There's more refactor/consolidation we'll need to do here between `NetworkConfig` and `NetworkContext`.

`NetworkConfig` is confusing because it actually contains **machine** configuration:

- max call depth
- max wasm stack
- actor debugging
- actor redirects
- builtin overrides

As well as some network attributes which should live in `NetworkContext`:

- network version
- price list

But we don't need to do it _now_.

_Originally posted by @raulk in https://github.com/filecoin-project/ref-fvm/pull/905#discussion_r984526392_

**Comment by Stebalien** [comment]
`NetworkConfig` defines the current network. The network version and the price list are part of the current network config. Basically, the network config is the thing that changes on network upgrades.
