### ISSUE TITLE
EVM runtime: pass chain ID in NetworkContext

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#918]
See https://github.com/filecoin-project/builtin-actors/pull/713#discussion_r985943222.

**Comment by raulk** [comment]
IMO:
- This can happen after feature completeness.
- Not consensus breaking (except for CodeCID change in EVM actor).

**Comment by Stebalien** [comment]
Well, it's _definitely_ consensus breaking. It just won't break smart contracts.

But you're right, we can punt (although it would be easier to just fix this now given how simple it is).

**Comment by Stebalien** [comment]
We'll put this in the "if we have time" pile.

**Comment by Stebalien** [comment]
Er, well, this isn't quite done. We now feed the chain ID into the actors, but we don't actually _use_ it in the EVM. To do that, we need to:

1. Add a `chain_id` method to the actors `Runtime`.
2. Change the `CHAINID` instruction to return the real chain ID.

**Comment by Stebalien** [comment]
We also need to feed the chain ID down from lotus and through the FFI.

**Comment by Stebalien** [comment]
Nvm. I've just field two more issues.

https://github.com/filecoin-project/ref-fvm/issues/1231
https://github.com/filecoin-project/ref-fvm/issues/1230
