### ISSUE TITLE
The tipset_cid syscall bikeshed

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#927]
This syscall currently:

- Takes an offset starting at the current epoch.
- Returns "illegal argument" in almost all error cases.
- Returns "0" (an empty CID) if we try to lookup an epoch before epoch 0.

The bikeshed:

- The _randomness functions_ take an _epoch_, not an offset. Really, this function claims to take an epoch as well but doesn't.
    - We definitely need to add some documentation.
    - Differing from the randomness functions makes _some_ sense as we generally use those functions to "tie" commitments to the chain, but I'm not sure if it's worth the confusion.
- Errors
    - If we're looking back too far, we should use the LimitExceeded error code.
    - If we do take an absolute epoch, we'd return IllegalArgument for "negative" epochs.
    - If we continue to take a relative epoch, we should return IllegalOperation in this case (I think?). This case almost never matters.

@vyzo any strong opinions on any of these cases?

**Comment by Stebalien** [comment]
Note: A good reason not to return "0" in the "too early" case is that this is a very _rare_ error so it'll likely cause bugs that we almost never hit/catch. E.g. https://github.com/filecoin-project/ref-fvm/pull/905/files#diff-3556c1b6ea1155a67ab10be85ca50129720f76b399257f20ce8cabb1f106a0fbR49 will panic in some cases.

**Comment by vyzo** [comment]
I think these are valid, if minor concerns, and we should adjust implementation.

And yes, definitely make the lookup take an absolute epoch:
I propose we stop passing the finality vector and allow arbitrary lookups using an extern instead, and utilizing existing functionality for retrieving tipsets by epoch in clients instead of using ring buffers and the like.

I've been thinking how to hook up the vectors in lotus (it is currently ignored in the ffi barrier, not even an option for it) and everything circles back to dont do it, use GetTipsetByHeight instead.

Also ping @raulk for input here as he was the source of the finality check.

**Comment by Stebalien** [comment]
>  I propose we stop passing the finality vector and allow arbitrary lookups using an extern instead, and utilizing existing functionality for retrieving tipsets by epoch in clients instead of using ring buffers and the like.

I'm not sure if we _can_ allow arbitrary lookback, but I guess that's something to look into. If we _do_, we'd want to allow arbitrary lookback for randomness at the same time.

**Comment by Stebalien** [comment]
note: the FFI cost is _high_ (like, absurdly ridiculously high)

> I've been thinking how to hook up the vectors in lotus (it is currently ignored in the ffi barrier, not even an option for it) and everything circles back to dont do it, use GetTipsetByHeight instead.

I'm happy to take a stab at this to convince myself it's not an option. Even just serializing a buffer to/from CBOR is likely better than constantly crossing the FFI boundary.

**Comment by vyzo** [comment]
ok, lets limit the lookback then. But the foreign boundary cross cost is not a big deal, this is not a frequent call.

**Comment by raulk** [comment]
For M2.1 I think it would be acceptable to have lookbacks as a declared "maybe" item, and only deliver it as a feature enhancement if devs really miss it. My gut feeling is that this feature is infrequently used in Ethereum, likely mostly used as poor man randomness and for inclusion proofs in scenarios like dispute resolution/slashing. For the former, Ethereum has no dedicated randomness opcodes, while Filecoin does, so users would be better served if we exposed precompiles for our randomness syscalls. For the latter, I think it's going to be a while until we see use cases in Filecoin that require inclusion proofs over the tipset (and we'd need to work out the mechanics of those, given the new tipset CID, and deferred execution mechanics in Filecoin...).

**Comment by Stebalien** [comment]
> ok, lets limit the lookback then. But the foreign boundary cross cost is not a big deal, this is not a frequent call.

Fair enough. In that case, I think the reasonable solution is to:

- Limit the lookback for future optimizations. We can always _loosen_ it later.
- Cross the boundary _now_, potentially optimizing later.
