### ISSUE TITLE
Relevant parts (bottom half) of section R2B

### ISSUE THREAD

**Issue by laudiacay** [filecoin-project/ref-fvm#93]
miner::confirm_sector_proofs_valid_internal does not handle internal runtime errors when activating deals in the market actor
In go-actors, an internal runtime error here immediately aborts via panic.
miner::report_consensus_fault does not handle internal runtime errors when rewarding the consensus fault reporter
In go-actors, an internal runtime error here immediately aborts via panic.
See #F17
miner::dispute_windowed_post does not handle internal runtime errors when burning funds
In go-actors, an internal runtime error here immediately aborts via panic.

these are the p0 parts of R2 as agreed on in slack

**Comment by jennijuju** [comment]
immediate task: validate if this is ✅  if not access the priority. @arajasek

**Comment by arajasek** [comment]
Okay, there's no concern here
