### ISSUE TITLE
M2.1 (r9) Sapphire

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#940]
## Goal
Improvements, bugfixes, optimizations.

## Implementation scope
- https://github.com/filecoin-project/filecoin-ffi/issues/335
- https://github.com/filecoin-project/ref-fvm/issues/986 
- https://github.com/filecoin-project/ref-fvm/issues/985 
- https://github.com/filecoin-project/ref-fvm/issues/725 
- https://github.com/filecoin-project/builtin-actors/pull/646
- https://github.com/filecoin-project/ref-fvm/issues/847
- https://github.com/filecoin-project/ref-fvm/issues/878
- https://github.com/filecoin-project/ref-fvm/issues/966
- https://github.com/filecoin-project/ref-fvm/issues/874
- https://github.com/filecoin-project/ref-fvm/issues/1066
- https://github.com/filecoin-project/ref-fvm/issues/956
- https://github.com/filecoin-project/ref-fvm/issues/993
- https://github.com/filecoin-project/ref-fvm/issues/1134
- https://github.com/filecoin-project/ref-fvm/issues/1076
- https://github.com/filecoin-project/ref-fvm/issues/1033
- https://github.com/filecoin-project/ref-fvm/issues/1137
- https://github.com/filecoin-project/ref-fvm/issues/1136
- https://github.com/filecoin-project/ref-fvm/issues/1135
- https://github.com/filecoin-project/ref-fvm/issues/1075
- https://github.com/filecoin-project/ref-fvm/issues/1051
- https://github.com/filecoin-project/ref-fvm/issues/892
- https://github.com/filecoin-project/ref-fvm/issues/891
- https://github.com/filecoin-project/ref-fvm/issues/890
- https://github.com/filecoin-project/ref-fvm/issues/859

## Work burndown

https://github.com/filecoin-project/ref-fvm/milestone/15

**Comment by raulk** [comment]
@maciejwitowski the scope still lists items that were not part of Sapphire. Should we remove them from here?

**Comment by maciejwitowski** [comment]
@raulk I missed it. Done now.
