### ISSUE TITLE
Replace the new_actor_address with a next_actor_address syscall

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#941]
We've discussed two proposals in the past:

1. Combining the `create_actor` and the `new_actor_address` syscalls.
2. Converting the `Constructor` method to a `constructor` wasm endpoint. 

Unfortunately, these two proposals are incompatible as we need to register actor's stable address in the init actor _before_ calling the constructor.

So instead I'd like to propose the following: change `new_actor_address` to `next_actor_address` where `next_actor_address` returns the stable address of the next deployed actor, but doesn't actually update the number of actors created. Instead, we'd leave that to `create_actor`.

Concretely: increment `num_actors_created` inside `create_actor` instead of inside `next_actor_address`.

**Comment by raulk** [comment]
Sounds reasonable. Just wondering how this factors in to salted address generation? "Next" loses applicability in that case?

**Comment by Stebalien** [comment]
Ok, maybe we should just all this `next_f2_address`? Because that's what it _actually_ returns. We only need it because it needs to know how many actors have been created.

**Comment by Stebalien** [comment]
I.e., `f4` addresses don't use this method.
