### ISSUE TITLE
Fix TVX

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#944]
Currently, [tvx](https://github.com/filecoin-project/lotus/tree/master/cmd/tvx) doesn't use the FVM (and so fails to compute the correct gas values). Unfortunately, when made to use the FVM, it trips up over some incomplete state.

I've made an attempt to fix this at https://github.com/filecoin-project/lotus/tree/steb/fix-tvx-fvm, but I was never able to really solve the issue. Unfortunately, this is making it hard to extract test vectors for nv18.

**Comment by maciejwitowski** [comment]
@Stebalien looks like [post code-freeze](https://github.com/filecoin-project/ref-fvm/milestone/19) to me. Wdyt?

**Comment by Stebalien** [comment]
Yeah, that works for me. We won't be extracting test vectors till things stabilize anyways.

**Comment by Stebalien** [comment]
Fixed by @arajasek

**Comment by aakoshh** [comment]
There seems to be some [missing parentheses](https://github.com/filecoin-project/lotus/blob/master/cmd/tvx/extract_message.go#L419-L423) in the TVX code.
