### ISSUE TITLE
EVM: Save state before calling

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#957]
We currently don't save the EVM actor's state before calling another actor. That needs to change.

I.e., right before https://github.com/filecoin-project/builtin-actors/blob/4860e2fcae19a212d4377f6496ad1f36fab6b03b/actors/evm/src/interpreter/instructions/call.rs#L161

**Comment by vyzo** [comment]
I am not convinced _at all_ that this the righr thing to do.
What if the call fails (not revert, but an error), that would leave us with partial state.

**Comment by Stebalien** [comment]
In the EVM, state writes are reflected _immediately_. If an actor wants to revert, they need to revert _everything_ by aborting which they'd do by calling `vm::exit`.

Otherwise, if A calls B calls A, the state will be wrong.

**Comment by Stebalien** [comment]
Closing in favor of #961 (the issue is deeper than that).
