### ISSUE TITLE
EVM Handle "empty" init code during construction

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#960]
A re-entrant call during contract construction may try to execute "empty" init code. We need to handle this.

**Comment by Stebalien** [comment]
By handle it, I mean: we should reject the call.

**Comment by Stebalien** [comment]
Actually, we need to _ignore_ the call. Just return nothing and do nothing.

**Comment by maciejwitowski** [comment]
@Stebalien let's make sure we have milestone assigned + entry in [the checklist](https://github.com/filecoin-project/ref-fvm/issues/936) if it goes to M2.1.

**Comment by Stebalien** [comment]
I already have a fix up for it.

**Comment by Stebalien** [comment]
Ok, so, I half-fixed this (allowed the _stored_ bytecode to be empty). Remaining parts:

1. Allow the initcode itself to be empty.
2. Allow the returned initcode to be empty.
