### ISSUE TITLE
Backport wasmtime 1.0 to FVM 2.0

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#962]
Unfortunately, we can't have multiple wasmtime versions in the same crate due to some linking issues. Given that no custom wasm actors are deployed on the network, upgrading wasmtime itself shouldn't really be a huge issue.

Going forward, we should try to reduce dependence on the specific WASM VM as much as possible. This will involve validating the supported subset of WASM bytecode inside the init actor itself, significantly reducing our exposure to bugs/differences in WASM VMs.

**Comment by Stebalien** [comment]
So, I _put_ this in the "post codefreeze" bucket, but we actually need to get it done before we land https://github.com/filecoin-project/filecoin-ffi/pull/324 (I guess).

In terms of validation, we need to validate a large enough portion of the chain (e.g., a couple of weeks) to be sure that there are no differences.

**Comment by Stebalien** [comment]
Luckily, lotus has already branched their next mandatory release, so this shouldn't be _too_ contentious.

**Comment by mriise** [comment]
fixed by #963 
github just didnt auto-close because of a period. lol.

@Stebalien
