### ISSUE TITLE
EVM: Read Only Sends

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#971]
EVM allows contracts to set calls as readonly, used especially by STATICCALL.

**Comment by mriise** [comment]
related discussion https://github.com/filecoin-project/FIPs/discussions/487

**Comment by Stebalien** [comment]
Turns out there was already an issue for STATICCALL https://github.com/filecoin-project/ref-fvm/issues/872 (had some trouble finding it). Let's stick to that one.

**Comment by Stebalien** [comment]
Reopening because we only implemented this with a hack.

**Comment by Stebalien** [comment]
Er, we have another issue.
