### ISSUE TITLE
EVM: Create a shared crate for common EVM types

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#974]
At least EthAddress, but likely more.

We now have _two_ Ethereum related actors (EVM & EAM) and will soon have at least one more for an Ethereum Account (and possibly a fourth "Virtual" Ethereum Account).

**Comment by maciejwitowski** [comment]
This lands into "highly annoying" zone. We will move it to M2.2. Discussed with @Stebalien
