### ISSUE TITLE
EVM: Provide a way to deploy native actors with Ethereum addresses

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#975]
Currently, all native actors will have "ID-in-Ethereum" address (0xff00.....ID) but won't have a proper _stable_ Ethereum address.

Proposal: Add a `create_native` method to the EAM that behaves like `create2` but creates a native actor instead.

Specifically, it:

1. Computes the address based on the caller, CID, and constructor params.
2. Calls `Init::exec4` with the specified params.

**Comment by maciejwitowski** [comment]
@Stebalien Just checking: M2.2, right?

**Comment by raulk** [comment]
Hm, do we want to support this now so that EVM smart contacts can create things like f4-addressable payment channels and multisigs?

**Comment by Stebalien** [comment]
The idea was to allow EVM actors to reference these actors with "stable" addresses. However.... meh.

**Comment by Stebalien** [comment]
Not a priority, ever.
