### ISSUE TITLE
Implement f4 support in the lotus ethereum API

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#983]
Specifically, we need to handle conversions between "eth" addresses and "f4" addresses.

- [x] Merge https://github.com/filecoin-project/lotus/pull/9511
- [x] Extend https://github.com/filecoin-project/lotus/blob/92fd021a764f01073d94f30b750ddee3694cd50d/api/eth_types.go#L284-L287

There may be other places as well.

**Comment by raulk** [comment]
There are a bunch of other places.

**Comment by raulk** [comment]
Delivered in https://github.com/filecoin-project/lotus/pull/9541.
