### ISSUE TITLE
Propagate return data from `REVERT`

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#985]
This is a continuation of https://github.com/filecoin-project/ref-fvm/issues/811 which was mostly addressed by https://github.com/filecoin-project/builtin-actors/pull/633 with a caveat that

> REVERT doesn't propagate return data yet; this will be fixed in a subsequent pr, as it requires fvm support for aborting with data.

**Comment by Stebalien** [comment]
Depends on https://github.com/filecoin-project/ref-fvm/issues/986
