### ISSUE TITLE
EVM smart contract creation via the EAM

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#992]
## Context

Currently, it is possible to deploy an EVM smart contract by either:

1. Sending an Ethereum transaction with a nil To address and the init code as input data. The JSON-RPC API detects this and invokes the init actor to instantiate the EVM smart contract.
2. Using the `lotus ethereum create-evm-actor` command, which also instantiates the EVM smart contract through the init actor.

## Action

Need to migrate both methods to use the `EAM#CreateActor` method so that an f410 address is generated for these contracts.

## Relates to

#989.

**Comment by raulk** [comment]
For this, I first need to create the relevant types in go-state-types. Fun.

**Comment by Stebalien** [comment]
We have three cases:

1. From an EOEthereumAccount. In this case, lotus should rewrite the transaction to call `EAM::CreateActor` with the current nonce.
2. From a VirtualEthereumAccount (controlled on-chain by an f1 account). In this case... we can probably just use the origin nonce as well?
3. Directly from an f1 account. Not sure? We currently don't allow this (users should call create2 instead) but we could? There really isn't a security issue with users specifying their own nonces here (we'll never "clobber" an existing actor).

**Comment by raulk** [comment]
This has been delivered in https://github.com/filecoin-project/lotus/pull/9541.
