### ISSUE TITLE
EVM: Instruction Tests

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#993]
We need to add better unit tests for our instructions. Many of these instructions may already be covered, but we should check anyways.

- #1541
- #1542
- #1543
- #1544
- #1545
- #1546
- #1547
- #1548
- #1549
- #1550
- #1551
- #1552
- #1553
- #1554
- #1555
- #1556

**Comment by mriise** [comment]
Changing this to be an overall unit test issue
