### ISSUE TITLE
EVM: FIP 0044 for EthAccounts

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#994]
https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0044.md

This is necessary for EVM accounts to be on-par with native accounts. EVM _contracts_ can already implement FIP 0044 using the METHODNUM opcode.

**Comment by raulk** [comment]
AFAIK, this was solved by introducing the `HandleFilecoinMethod` path. This is already specified in the EVM FIP but we can probably do with Solidity sugar for this in https://github.com/Zondax/filecoin-solidity.

@emmanuelm41 I believe this is in scope.

@hammertoe we need to document this!

Reopen if you meant something else here, @mriise.

**Comment by raulk** [comment]
Ah, I see that @Stebalien changed the title -- I was just reading the body. This is necessary for the EEOA, yes, agree.

**Comment by arajasek** [comment]
I'm claiming this, but very happy to have someone beat me to it.

**Comment by jennijuju** [comment]
@maciejwitowski  nudge: this issue was once closed, so it got moved to the "Done" column on the fvm board and we lost track of it. Next time, when we reopen the issue, we should update the project status (we can also create a project board workflow for it)

**Comment by maciejwitowski** [comment]
@jennijuju good catch, thank you!
