### ISSUE TITLE
EVM: Two types of Ethereum Accounts

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#995]
# Proposal

Introduce two Ethereum accounts:

1. An Externally Owned Ethereum Account (or EOEthAccount?). This account would be automatically created on first send from some ethereum address, and would validate off-chain messages.
2. An Virtual Ethereum Account (Proxy account?). This account would be _explicitly_ created by the equivalent `f1` account.

The first case has been discussed extensively so I'm not going to go into any detail. But importantly, in _this_ proposal, an externally owned Ethereum account would _only_ validate off-chain messages and transfer/store funds (it wouldn't serve any other function).

A "virtual" Ethereum account is an Ethereum account created and controlled by some `f1` account.

## Account Creation

To create a virtual account, a user with an `f1` account would invoke `CreateAccount(users_public_key)` on the EAM. The EAM would then:

1. Compute the appropriate `f1` address from the public key, and validate that it matches the caller.
2. Compute the appropriate Ethereum address and deploy a new virtual account at that address (recording the fact that said account is owned by the caller).

NOTE: if an embryo already exists at the target Ethereum address, the new account would be deployed over that embryo gaining control of any funds already sent to that address.

## Sending Messages

The controlling `f1` account would be able to send messages as this "virtual" Ethereum account by-proxy by invoking a `CallActor` method on the virtual Ethereum account with the appropriate:

- Value to be sent.
- To address.
- Message parameters.
- Method number.

## Funds

At the end of the day, a virtual Ethereum account is a different account from the controlling `f1` account and would have a separate pot of funds.

For convenience, we could consider adding a `WithdrawFunds` method to this virtual account to withdraw funds to the controlling `f1` account. However, strictly speaking, this isn't necessary (`CallActor` can be used to do the same thing).

# Background

Logically, there are two ways we could implement Ethereum accounts in Filecoin:

1. As on-chain actors controlled by some other actor (e.g., an externally owned account).
2. As externally owned accounts (e.g., via account abstraction).

The first case makes it easy to send messages from, e.g., lotus, because the "ethereum account" would just proxy messages on behalf of the user (and receive funds on behalf of the user as well).

The second case makes it easy to integrate with existing tooling like metamask.

# History

Really, this all comes down two things:

1. Message validation. Users need to be able to send messages from tools like Metamask that may not know what Filecoin is.
2. Addressing. Users need to be able to send/receive from an "account" with an ethereum style address (derived form a SECP256K1 public key as done in Ethereum).

We've mostly solved the first case through account abstraction. However, while that works great for Metamask users, we also need to support "native" users sending "native" messages.

Our first (well, more like 20th) attempt was to "bind" an Ethereum address to an existing account after the fact. That way, a user with an existing Filecoin account (a "native" user) would be able to "claim" an Ethereum address.

However, this had two downsides:

1. Actors could end up with some arbitrary number of addresses.
2. This address might already "belong" to an embryo (someone may have sent funds to it).

So we shelved that idea and moved on to the next: allowing users to _control_ an Ethereum account from a native (e.g., f1) account. This means an Ethereum account would be both an abstract account (validating off-chain messages) and a proxy (forwarding messages on behalf of the equivalent f1 account).

Unfortunately using the same "account" for two purposes had some security issues: https://github.com/filecoin-project/FIPs/discussions/388#discussioncomment-3825085

That brings us to the third approach, the one described here. Instead of trying to bundle both concepts together, I'm proposing that we introduce two actors, one for each use-case.

**Comment by raulk** [comment]
The virtual account seems to address two flows:

1. Claiming an embryo by sending a Filecoin message (not an Ethereum message) from the same secp256k1 key.
    - I'm mildly confused by this because you had raised in the past that we wanted to avoid using the same key material with two distinct signature payloads (Ethereum and Filecoin formatted messages).
    - I thought it was fine at the time, because the signature scheme was the same (would be more worrisome to use the same key with two different signature schemes).
2. Creating a **brand new** f4 account authenticated by the f1 key so it can act as a proxy? What use cases is this relevant for?

Up until now we have talked about f1 and f4 being effectively segregated, and this seems like a departure from that direction and architecture. Also, I am not convinced this focuses on the right things.

For (1) "claiming an embryo" should not involve sending a Filecoin message as that poses significant friction. Once funds are in an f4 embryo, **_sending_** from that f4 embryo should be enough to transmute that address into an Ethereum EOA. 

Unfortunately this involves cooperation at the ref-fvm level, and concretely, knowledge of the code CID to transmute an embryo to. One possible solution is to make the EAM expose the CodeCID of an external account, for the ref-fvm to use.

Please refer to [discussion on #fvm on Slack](https://filecoinproject.slack.com/archives/C029MT4PQB1/p1666200376369759?thread_ts=1666198465.870539&cid=C029MT4PQB1) on why the Filecoin interation is frictionful.

For (2), I need more clarity on what kind of use cases it is trying to solve.

**Comment by Stebalien** [comment]
We've discussed this a bit in person but I'm still going to respond to make sure we're on the same page.

Virtual accounts support _one_ flow: managing an ethereum account from a filecoin (f1) account. This lets a user create a new ethereum account managed by an existing account in lotus.

Abstract accounts support _one_ flow: managing an ethereum account by sending off-chain messages from said account. This lets a user create a new ethereum account managed by ethereum tools like metamask.

These are two _separate_ things.

> I'm mildly confused by this because you had raised in the past that we wanted to avoid using the same key material with two distinct signature payloads (Ethereum and Filecoin formatted messages).

The concern was _signing_ messages with the same exact key. In this proposal, we'd either sign Filecoin messages (and use a virtual account) or sign Ethereum messages (and use an abstract account) but we'd never sign both types of messages with the same key.

> For (1) "claiming an embryo" should not involve sending a Filecoin message as that poses significant friction. Once funds are in an f4 embryo, sending from that f4 embryo should be enough to transmute that address into an Ethereum EOA.

In this proposal, we'd only send a _filecoin_ message if we wanted to manage the account from, e.g. lotus (controlling the account with an existing f1 account). We'd still support the other flow.

**Comment by maciejwitowski** [comment]
@Stebalien This one got lost in Topaz. Can you set correct milestone and priority?

**Comment by Stebalien** [comment]
We've decided to punt on this as it can be implemented in userspace with an EVM smart contract.

**Comment by Stebalien** [comment]
(also discussed this with @jennijuju yesterday and implementing proper ethereum wallet support in lotus wasn't quite as unappetizing as I had thought)
