### ISSUE TITLE
JSON-RPC API bugs/missing features

### ISSUE THREAD

**Issue by ychiaoli18** [filecoin-project/ref-fvm#996]
### Ethers.js testing: 

- [x] [p0] eth_getBlockTransactionCountByHash and eth_getBlockTransactionCountByNumber may not return the correct number
- [x] [p0] eth_getCode should take block options (https://ethereum.github.io/execution-apis/api-documentation/)
- [x] [p1] eth_getStorageAt test does not pass
- [ ] [p2] cumulativeGasUsed should be implemented
- [ ] [p2] logsBloom are missing in block struct

### Web3.js testing
- [x] [p0] eth_getTransactionReceipt should return null instead of an error when the tx is not found/not mined

**Comment by maciejwitowski** [comment]
@ychiaoli18 do you expect any more work here in M2.1?

**Comment by jennijuju** [comment]
@maciejwitowski can you confirm the status and ownership on this?

**Comment by maciejwitowski** [comment]
Closing this to track left items separately.
