### ISSUE TITLE
Handle f4 addresses in `resolve_to_key_address`?

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#997]
This syscall reaches out into the state of the account actor to grab the pubkey address (f1 or f3). I suspect users will find it more useful to have a `resolve_to_stable_addresses` method which can also return f4 addresses. Right now it's impossible to go from an ID address to one or many f4 address, if they exists, if I'm understanding correctly.

**Comment by Stebalien** [comment]
> Right now it's impossible to go from an ID address to one or many f4 address, if they exists, if I'm understanding correctly.

We now store these in the ActorState object: https://github.com/filecoin-project/FIPs/discussions/477.

But the f4 embryo hack for the lotus hackathon will likely require a change here (at least for now).

**Comment by maciejwitowski** [comment]
@Stebalien Do we need this for M2.1?
